### ISSUE TITLE
As an admin, I want to see the difference between active casetypes and inactive ones

### ISSUE THREAD

**Issue by JurjenBert** [open-zaak/open-zaak#1000]
... so I can find the version i want to view more easily

Now historical and active versions are shown in the same way. The only way to determine which version is the current one, is to look at de date.  

**Description**

![afbeelding](https://user-images.githubusercontent.com/40294293/123978346-15f10f80-d9c0-11eb-8f43-99806c591d15.png)

**Comment by sergei-maertens** [comment]
We could implement this with a sidebar filter that defaults to only active case types

**Comment by pinarje** [comment]
> We could implement this with a sidebar filter that defaults to only active case types

This mentioned above would be very nice. We have the same problem.

**Comment by sergei-maertens** [comment]
There are filters available since the 1.7.x versions :)

![image](https://user-images.githubusercontent.com/5518550/203739853-1c610135-43cb-4bb3-a34e-350072903798.png)
