### ISSUE TITLE
Document is not deleted when using the CMIS-adapter+SOAP-bindings

### ISSUE THREAD

**Issue by joeribekker** [open-zaak/open-zaak#1004]
**General information**
Open Zaak version: 1.4.1, with CMIS-adapter SOAP-bindings

**Describe the bug**
Deleting a document in Open Zaak does not delete the document ijn the DMS if the CMIS-adapter is used.

**To Reproduce**
1. Create zaak, document, zaakdocument-relation
2. Delete document leads to relation being deleted, but not the document itself

**Expected behavior**
Document should be deleted IF there are no more relations to this document.

**Comment by sergei-maertens** [comment]
Fixed via #1189
