### ISSUE TITLE
foutmelding: Geen besluiten aan zaak gekoppeld om brondatum uit af te leiden (zaak aangemaakt vanuit Powerbrowser)

### ISSUE THREAD

**Issue by jgabrieldelft** [open-zaak/open-zaak#1014]
De status van een Evenementenvergunning kan niet op afgehandeld worden gezet vanuit Powerbrowser.
We hebben geen besluiten ingericht in Open Zaak, dus hoe kan een zaaktype hiernaar verwijzen? Of mis ik iets anders?

Logbericht verstuurd aan Open Zaak:
{
  "uuid": "00000000-0000-0000-0000-000000000000",
  "zaak": https://open-zaak.delft.nl/zaken/api/v1/zaken/2821dc19-aeec-4ed7-a9d2-035c2bcc8b1f,
  "statustype": https://open-zaak.delft.nl/catalogi/api/v1/statustypen/e7621159-81f4-4360-8439-12f68939f2c1,
  "datumStatusGezet": "2021-06-28T12:25:39.7072163+02:00",
  "statustoelichting": "Evenementenvergunning STUD Playground d.d. 3-7-2021  Schieweg 15M "
}

Logbericht antwoord Open Zaak:
{
  "type": https://open-zaak.delft.nl/ref/fouten/ValidationError/,
  "code": "invalid",
  "title": "Invalid input.",
  "status": 400,
  "detail": "",
  "instance": "urn:uuid:f40335f9-e29a-4812-b263-1d40ea39d5ce",
  "invalidParams": [
    {
      "name": "nonFieldErrors",
      "code": "archiefactiedatum-error",
      "reason": "Geen besluiten aan zaak gekoppeld om brondatum uit af te leiden."
    }
  ]
}

**Comment by hanspluimers** [comment]
Dit probleem wordt veroorzaakt door het meegestuurde 'zaakresultaattype". Op basis van dat zaakresultaattype wordt geprobeerd om de bewaartermijn van een zaak vast te stellen en in dit geval is daar de datum van het genomen besluit voor nodig. Dus al er geen besluit bij deze zaak geregistreerd kan worden (omdat je in de ZTC geen BesluitType hebt toegevoegd aan dit zaaktype) dan kan die datum niet worden bepaald en krijg je deze melding. Dus als je deze zaak opslaat met een ander zaakresultaat moet het wel goed gaan.

**Comment by jgabrieldelft** [comment]
Een ander resultaat koppelen kan niet, dan klopt het niet.
We hebben gezien dat dit in de iNavigator standaard zit.
Drank en horecawet ontheffing: gebruikt 'ander datum kenmerk' >gaat goed
Evenementenvergunning: gebruikt 'vervaldatum besluit' als startdatum voor vernietiging > gaat niet goed

Voor nu zullen we het handmatig oplossen. Is het dan noodzakelijk om besluitregistraties te implementeren of zijn er nog alternatieven?

**Comment by hanspluimers** [comment]
blijkbaar zit er een fout in de ZTC want het niet toevoegen van de besluittypen betekend dus dat je geen zaakresultaten kunt kiezen waarbij de bewaartermijn wordt bepaald op basis van een besluit. Het lijkt dus het meest logische om wel de besluitenregistratie te gaan implementeren van zeer veel zaken zullen resulteren in een besluit dat je gestructureerd wilt vastleggen dus het niet implementeren van de besluitenregistraties zorgt zeker voor nog meer problemen.

Wij (Roxit) hebben de besluitenregistratie ook geïmplementeerd in onze implementatie van de ZGW-api's.  Besluiten zijn in ieder geval binnen onze VTH-toepassing essentieel en onmisbaar.

**Comment by joeribekker** [comment]
Denk dat @hanspluimers het correct zegt. Volgens mij is dit geen bug maar een ZTC configuratie fout.

Correct me if I'm wrong.

**Comment by sergei-maertens** [comment]
Dit is inderdaad geen bug in Open Zaak, maar een configuratiefout in de catalogi.

Indien een resultaattype afdwingt dat de archiefactiedatum afgeleid wordt uit een besluit, dan moet:

1. catalogusbeheer zorgen dat de relevante besluittypen beschikbaar zijn
2. de applicatie/het proces ervoor zorgen dat er een besluit ontstaat waaruit de archiefactiedatum kan afgeleid worden

**Comment by jgabrieldelft** [comment]
Jullie hebben gelijk. Nadeel is dat onze VTH toepassing Powerbrowser nog geen besluiten API ondersteunt, dus 1-2-3 implementeren van de Bestluiten registratie in OZ gaat niet.
We gaan dus de komende tijd alles handmatig aanpassen als workaround.

**Comment by sergei-maertens** [comment]
Succes en jammer dat het nog geen smooth sailing is!
