### ISSUE TITLE
Creating or updating resources with types from ZTC where concept is True should not be allowed

### ISSUE THREAD

**Issue by stevenbal** [open-zaak/open-zaak#102]
**Describe the bug**
When creating or updating any resource in the components other than ZTC (so ZRC, DRC, BRC, AC and NRC) with *types from ZTC, there should be a validator that checks whether the used *types from ZTC have `concept=false`, if this is not the case for any type, a 400 should be returned

**Comment by annashamray** [comment]
PR - https://github.com/open-zaak/open-zaak/pull/106

**Comment by sergei-maertens** [comment]
Fixed via #106
