### ISSUE TITLE
Filteren van zaken op rol__omschrijvingGeneriek geeft resultaat met dubbele zaken

### ISSUE THREAD

**Issue by andyverberne** [open-zaak/open-zaak#1023]
**General information**
Open Zaak version:  1.3.5

**Describe the bug**
Wanneer een lijst van zaken wordt opgevraagd met de zaak_list operatie en een rol__omschrijvingGeneriek query parameter dan kan het voorkomen dat een zaak 2 keer voor komt in het resultaat.
Voorbeeld van query: GET http://open-zaak-nginx.open-zaak/zaken/api/v1/zaken?rol__omschrijvingGeneriek=behandelaar

Wanneer aan 1 zaak 2 Rollen gekoppeld zijn met een gelijk rol type maar met een verschillend betrokkene type dan komt deze zaak 2 keer voor in het resultaat

**To Reproduce**
1. ... Creer een zaak met daar aan gekoppeld 2 rollen met een verschillend betrokkene type: Medewerker en Organisatorisvche eenheid,  maar met een gelijk rol type: behandelaar
2. ...Haal een lijst met zaken op met als enige filter parameter rol__omschrijvingGeneriek=behandelaar

**Expected behavior**
De zaak met 2 rollen komt maar 1 keer voor in de lijst van zaken

**Comment by joeribekker** [comment]
Helder. Vermoed een JOIN die niet lekker gaat.
