### ISSUE TITLE
Resultaattype selectielijst is "sometimes" incorrect in what it lists.

### ISSUE THREAD

**Issue by joeribekker** [open-zaak/open-zaak#1030]
**General information**
Open Zaak version: 1.4.1

**Describe the bug**
Create a Resultaattype from scratch shows ALL resultaten from the Selectielijst (including from all years since there's no attached zaaktype yet, where the year is configured)

![image](https://user-images.githubusercontent.com/96970/131365018-8f6cf5df-c299-4d0d-8787-4e860848b5d6.png)

**To Reproduce**
1. Create Resultaattype
2. Scroll to Selectielijstklasse
3. Inspect the list of resultaten showing duplicates sometimes (names are to be expected but not the URL)

This is, I think, an underlying issue to the error "This selectielijstklasse is not a valid choice" which happens when a Zaaktype IS actually connected. I suspect cache or cache keys being set incorrectly, or the admin-voodoo-magic (comment in code) to get the zaaktype is going wrong.

![image](https://user-images.githubusercontent.com/96970/131365550-9a140e3a-f03d-4538-bb7e-5ceb983dd27a.png)

I think what helps alot is some Javascript that refreshes this list based on the selected zaaktype

**Expected behavior**
The list of selectieklasses should be correct.

**Comment by sergei-maertens** [comment]
> I think what helps alot is some Javascript that refreshes this list based on the selected zaaktype

I 100% agree - it'll provide for the best user-experience anyway, and let's also just tackle the Zaaktype admin while we're at it. There are too many bugs related to this.

**Comment by sergei-maertens** [comment]
I came across this as part of #1161 as well and noticed that the zaaktype selectielijst year can be `None`, which causes the result of both 2017 and 2020 to be included. That is patched in bc804a92a602bd0fd2865b7bf68019d105928d98

That still leaves the desired improved user experience by refreshing the list with some Javascript though.
