### ISSUE TITLE
OpenZaak is failing on 1 test on api-test.nl

### ISSUE THREAD

**Issue by alextreme** [open-zaak/open-zaak#1035]
**General information**
Open Zaak version: test.openzaak.nl / d306636d657a7207fcbe0d28d0d31c08a221af85

**Describe the bug**
The API testplatform with OpenZaak is failing one test consistently with the following URL. Do we need to switch OpenZaak to the 1.1 or 1.2 Zaken API tests?

https://test.openzaak.nl/zaken/api/v1/rollen?zaak=https://test.openzaak.nl/zaken/api/v1/zaken/fcdbc5d7-7f24-4d77-b2af-ae22d7525215&betrokkene=https://example.com/&betrokkeneType=natuurlijk_persoon&betrokkeneIdentificatie__natuurlijkPersoon__inpBsn={{betrokkeneIdentificatie__natuurlijkPersoon__inpBsn}}&betrokkeneIdentificatie__natuurlijkPersoon__anpIdentificatie={{betrokkeneIdentificatie__natuurlijkPersoon__anpIdentificatie}}&betrokkeneIdentificatie__natuurlijkPersoon__inpA_nummer={{betrokkeneIdentificatie__natuurlijkPersoon__inpA_nummer}}&betrokkeneIdentificatie__nietNatuurlijkPersoon__innNnpId={{betrokkeneIdentificatie__nietNatuurlijkPersoon__innNnpId}}&betrokkeneIdentificatie__nietNatuurlijkPersoon__annIdentificatie={{betrokkeneIdentificatie__nietNatuurlijkPersoon__annIdentificatie}}&betrokkeneIdentificatie__vestiging__vestigingsNummer={{betrokkeneIdentificatie__vestiging__vestigingsNummer}}&betrokkeneIdentificatie__vestiging__identificatie={{betrokkeneIdentificatie__vestiging__identificatie}}&betrokkeneIdentificatie__medewerker__identificatie={{betrokkeneIdentificatie__medewerker__identificatie}}&roltype=https://test.openzaak.nl/catalogi/api/v1/roltypen/90fa46f3-4e45-4c5a-851f-ae1b23d84034&omschrijving=aangepaste omschrijving&omschrijvingGeneriek=adviseur&page=1

**To Reproduce**
https://api-test.nl/server/1/311f69c1-a801-4950-b9a8-6fe3c6815b90/
![2021-09-08_09-56](https://user-images.githubusercontent.com/226839/132469788-0f7170f6-7a16-4133-b022-9c0d2d436294.png)
![2021-09-08_09-57](https://user-images.githubusercontent.com/226839/132469791-2ba9e868-f118-4768-a301-784c036fd91a.png)

**Comment by alextreme** [comment]
Have started a ZGW v1.2 testrun on https://api-test.nl/server/1/a779c380-0cd1-49f0-96b3-ecf82c2de651/5ad6e75e-48e8-46b5-89ad-0ef562863483/

**Comment by alextreme** [comment]
test.openzaak.nl with ZGW 1.2 seems to have more failing tests. @stevenbal feel free to investigate.

**Comment by sergei-maertens** [comment]
that's curious - it does look a lot like the parameter that was a mistake and fixed in a patch release of the standard, see #726

I believe the test suite must be updated.

**Comment by stevenbal** [comment]
I will update the testsuite, I did notice however that the name of the parameter is now slightly different in Open Zaak compared to the reference implementation:
- Open Zaak: betrokkeneIdentificatie__organisatorischeeenheid__identificatie (https://github.com/open-zaak/open-zaak/commit/232ebe1effba6453b743cfeeb4efaf1ba035c358#diff-a44139bd824a9c4ffafcea6f807e8311ae9624e5bc5fdcfa0c1d8529363c36a6L673)
- Ref. implementation: betrokkeneIdentificatie__organisatorischeEenheid__identificatie (https://github.com/VNG-Realisatie/zaken-api/pull/158/commits/d1f2a27777d72fd82bae961c7372678d611f4d5e#diff-b9c28fec6c3f3fa5cff870d24601d6ab7027520f3b084cc767aefd258cb8c40aL1605)

**Comment by sergei-maertens** [comment]
Okay, the parameter in Open Zaak has a bug then, probably related to the camelCase changes and we'll look into that. Ref implementation is correct.

**Comment by stevenbal** [comment]
> test.openzaak.nl with ZGW 1.2 seems to have more failing tests. @stevenbal feel free to investigate.

I think this would be expected, since Open Zaak is not on version 1.2.0 in terms of the API specs (https://github.com/VNG-Realisatie/gemma-zaken/issues/1727 isn't implemented yet in Open Zaak). @sergei-maertens correct me if I'm wrong

**Comment by sergei-maertens** [comment]
That is correct - Open Zaak only does 1.0.x versions of the APIs until there's demand/budget to implement newer versions :-)

**Comment by sergei-maertens** [comment]
This particular failure was fixed via ef3433fa1a4c72fa2ff79e2cf3015715c16c4bc9. There are now other tests failing, but it's on the radar and will be looked into next week probably :)
