### ISSUE TITLE
Question: is it possible to upload a custom 'selectielijst'? 

### ISSUE THREAD

**Issue by OlavAllema** [open-zaak/open-zaak#1038]
A government agency wants to be able to also select a provincial 'selectielijst' in stead of only one for municipalities. We, as Contezza, would like to provide this for them in terms of 'a custom provincial selectielijst' (for the time being; until there is a connection available for Open Zaak with the national one). Question is, is it possible to upload a custom selectielijst?

This is where we want to show the custom selectielijst:
![image](https://user-images.githubusercontent.com/75848616/134184333-a05a961c-5fe7-423f-acc5-a668bb2ef41f.png)
 
 After that, we want to be able to choose the right resultaattypen.

**Comment by shazada** [comment]
Met Sergei gesproken en blijkbaar als je een custom lijst wilt hebben zul je deze endpoints moeten implementeren:

https://selectielijst.openzaak.nl/api/v1/

Beschrijving hiervan is hier te vinden: https://selectielijst.openzaak.nl/api/v1/schema/

**Comment by shazada** [comment]
Wat misschien wel interessant kan zijn om in je eco-systeem een selectie-lijst component mee te nemen. Ik zal even navragen of de selectielijst component (oplossing) ergens verkrijgbaar is.

**Comment by sergei-maertens** [comment]
@shazada yeah it is: https://github.com/open-zaak/vng-selectielijst

it has the usual admin interface where you can enter content, and also supports importing from Excel if you stick to the same format :)

This is the app powering https://selectielijst.openzaak.nl/api/v1/

**Comment by sergei-maertens** [comment]
Closing this issue as the question is answered :)
