### ISSUE TITLE
In the schema of Authorizations the Autorisatie.component enum is not complete

### ISSUE THREAD

**Issue by stevenbal** [open-zaak/open-zaak#105]
**Describe the bug**
In the dropdown menu for `Autorisatie.component` in the API spec of Authorizations (/authorizations/api/v1/schema/#operation/applicatie_create), only the components ZRC, DRC, and BRC are shown and the components AC, ZTC and NRC are missing

![Screenshot from 2019-10-07 15-27-23](https://user-images.githubusercontent.com/29249171/66316178-76e8d200-e917-11e9-8714-2718afa8e4c7.png)

**Comment by annashamray** [comment]
now the discriminator field in the API spec should contains all the values
