### ISSUE TITLE
Datum einde geldigheid zaak

### ISSUE THREAD

**Issue by pinarje** [open-zaak/open-zaak#1055]
**General information**
Open Zaak version: 1.3.5

**Describe the bug**
We hebben zaaktypen in Open Zaak staan die gepubliceerd zijn. Als ik een zaak niet meer wil publiceren, maar ook geen nieuwe versie wil krijg ik een foutmelding. Bijvoorbeeld het zaaktype 'melding openbare ruimte'.  
![9ff49466-2ffe-48c1-8324-4949ab866ae7](https://user-images.githubusercontent.com/93332466/139275169-0a7cbf18-7aaf-485c-b758-5b5c153ec993.jpg)
We willen deze niet meer gepubliceerd hebben staan. In de bijgaande afbeelding heb ik een einddatum ingegeven. Maar als ik dan op 'opslaan' klik krijg ik de 500 melding (zie afbeelding). 
![eedf939f-461e-419e-8084-5fe1a6149577](https://user-images.githubusercontent.com/93332466/139275181-b58ebb86-431c-4f2e-85e0-18ca8fa1a1c6.jpg)

Ik kan dan alleen maar kiezen voor 'nieuwe versie toevoegen', dan wordt deze wel beëindigd maar krijg ik ook een nieuwe versie van dit zaaktype. Dit laatste is dus niet nodig. Ik wil de zaak beëindigen en geen nieuwe versie.

![0a80608f-e2bc-41ae-bfc2-be688f5f2919](https://user-images.githubusercontent.com/93332466/139275201-72ea549c-feb4-490b-818b-1480a45f3126.jpg)

**To Reproduce**
1. Vul einddatum in bij zaaktype in het veld 'Datum einde geldigheid'
2. Klik rechtsonder op opslaan.

**Expected behavior**
Het zaaktype wordt beëindigd (staat niet meer live) zonder foutmelding en zonder nieuwe versie.

**Comment by pinarje** [comment]
Gaan we opzoeken!

**Comment by sergei-maertens** [comment]
This may have been fixed by 1.7.4, need to verify this.
