### ISSUE TITLE
OpenZaak beheeromgeving: tonen additionele informatie in zaken lijstweergave

### ISSUE THREAD

**Issue by alextreme** [open-zaak/open-zaak#1064]
Verzoek vanuit SWF (nr 23 in Taiga) om de lijstweergave van zaken in de OpenZaak beheeromgeving te verbeteren, lijkt mij een quick win:

Graag zou ik in het overzicht van de zaken direct wat meer informatie willen zien.

Pad: [Gegevens-Zaken]

Op dit moment zie je alleen het zaaknummer, startdatum, registratiedatum en einddatum.

Graag zou ik in het overzicht de volgende data toe willen laten voegen:

    om welk zaaktype gaat het?
    wat is de huidige status?
    indien aanwezig: wat is het resultaat?

**Comment by sergei-maertens** [comment]
Zaaktype is not trivial - if we're using an external zaaktype this will be a costly operation to make 100 requests to another system (worst case). We could meet in the middle and only display zaaktype if it's a local zaaktype (probably the most common case)

Current status suffers the same issue as above - if using an external zaaktype, this becomes costly. However, the same middleground can be achieved.

And for result, you guessed it :) the same applies.

Would this be ok?

**Comment by alextreme** [comment]
I wouldn't mind only showing the zaaktype if it's local and otherwise keeping the field blank. It's an admin-improvement so as long as it doesn't impact working with remote zaaktypes it's a step forward in my eyes.
