### ISSUE TITLE
As an IT manager, I want to have instructions on how to deploy Open Zaak

### ISSUE THREAD

**Issue by sergei-maertens** [open-zaak/open-zaak#108]
... so I can manage installation and deployment in my own environment.

**Description**

Technical documentation needs to be compiled to document various installation/deployment scenario's, with attention to:

* [ ] Installatiehandleiding voor op een enkele server
* [x] Installatiehandleiding voor op Kubernetes

**Comment by joeribekker** [comment]
How does this differ from #8 and #9?

I currently see PR #109 which is mostly about raw Linux deployment which will not be a supported method. We offer a (or multiple) Docker container(s) and as an Appliance.

We will need a script to create the Appliance so PR #109 is more background info for me. Let's focus on existing stories and not create our own preferably!

**Comment by sergei-maertens** [comment]
I completely misunderstood the requirements then, I was looking at the
tickets in the project board and didn't see it. Must've glanced over the
other ones :(

**Comment by joeribekker** [comment]
No worries. The work can still be used to create the appliance and you got Sphinx in :)
