### ISSUE TITLE
Deleted IO types do not delete autorisations for that IO type.

### ISSUE THREAD

**Issue by joeribekker** [open-zaak/open-zaak#1081]
**General information**
Open Zaak version: 1.5.0

**Describe the bug**
Deleted IO types do not delete autorisations for that IO type.

**To Reproduce**
1. Create IO type
2. Create autorisations with this IO type
3. Delete UI tyoe
4. Open autorisations
5. A 500 is shown

**Expected behavior**
Autorisations should be deleted for non existing autorisations types, or at least the UI should keep working.

Seems related to #713

**Comment by sergei-maertens** [comment]
I suspect the delete might end up in the `queryset._raw_delete()` code path, and not fire signals because of that.

**Comment by sergei-maertens** [comment]
I've added a test, but could not reproduce the issue anymore (also not manually).
