### ISSUE TITLE
Gepubliceerde zaaktypen kunnen niet worden geëxporteerd

### ISSUE THREAD

**Issue by OlavAllema** [open-zaak/open-zaak#1093]
**General information**
Open Zaak version: 1.3.5

**Describe the bug**
Gepubliceerd zaaktypen kunnen niet geëxporteerd worden, geven 500 foutmelding. Ongepubliceerde zaaktypen kunnen wel geëxporteerd worden. Lastig is, als je een zaaktypen van de testomgeving naar de productie-omgeving wilt brengen, moet je eerst je zaaktypen testen. Daarvoor moet je eerst je zaaktype publiceren. Als je het zaaktype wilt exporteren, moet je weer een nieuwe versie aanmaken. 

- Is de 500-melding een bug?
- Is het altijd zo dat gepubliceerd zaaktypen niet geëxporteerd kunnen worden? Dan is dat een erg onhandige werkwijze en praktisch gezien ook een bug.

**To Reproduce**
1. Ga naar een gepubliceerd zaaktype
2. Kies 'Export'
3. Foutmelding 500

**Expected behavior**
We zouden verwachten dat er een ZIP wordt gemaakt van het zaaktype. Deze zouden we willen kunnen inlezen in de productie-omgeving.

**Comment by OlavAllema** [comment]
Zou iemand een reactie kunnen geven op dit ticket?

**Comment by joeribekker** [comment]
Zou opgelost kunnen zijn in 1.4.0:

> Fixed broken zaaktype export for published zaaktypen (#964)

**Comment by sergei-maertens** [comment]
Verified - on current `main`, exporting of published zaaktypen works. So probably this was fixed since 1.4.0 already indeed.
