### ISSUE TITLE
Rating van docker containers op Artifact Hub

### ISSUE THREAD

**Issue by Hugo-ter-Doest** [open-zaak/open-zaak#1097]
Ik werd er bij de OpenZaak kerngroep op gewezen dat de docker containers van OpenZaak en OpenNotificaties op Artifact Hub een F rating hebben gekregen. Dat heeft niet zozeer met de implementatie of code van OpenZaak te maken, maar met de gebruikte libraries en besturingssysteem. @joeribekker Klopt mijn analyse?

Ik denk dat het belangrijk is om de containers bij te werken naar een nieuwe versie om ervoor te zorgen dat onze containers een betere rating krijgen.

**Comment by sergei-maertens** [comment]
we are formulating a response to this :)

**Comment by joeribekker** [comment]
_Response in Dutch to a Dutch question_

De container en Open Zaak versie op Artifacthub **worden niet ondersteund** door het Open Zaak community team en Artifacthub is **geen officieel kanaal** waarop Open Zaak wordt aangeboden. We raden iedereen aan om altijd het **officiële kanaal te hanteren** en de laatste stabiele versie van [Dockerhub](https://hub.docker.com/r/openzaak/open-zaak/tags) te gebruiken.

Inhoudelijk klopt @Hugo-ter-Doest zijn analyse dat de Artifacthub rating **geen betrekking heeft op de Open Zaak software** maar op een verouderde versie van Open Zaak images. Op Dockerhub zijn nieuwere image versies gepubliceerd dan waar de charts op Artifacthub naar verwijzen om de eenvoudige reden dat de charts nog niet bijgewerkt zijn naar de meest recente versies van Open Zaak. Open Zaak zelf wordt continue bijgewerkt met de laatste security patches. Open Zaak zelf, en de bijbehorende Docker containers, zitten daarom ook al op versie 1.5 terwijl Artifacthub (op dit moment) nog verwijst naar versie 1.4.0 van Open Zaak.

**Hoe komt deze F-rating tot stand op Artifacthub?**

We hebben de score op Artifact hub bekeken en de scan, die leidde tot een F-rating, geanalyseerd.

1. Er wordt een verouderde versie van Open Zaak gebruikt (1.4.0 is 9 maanden oud, terwijl 1.5 al 3 maanden beschikbaar is).
2. De security scan is vrij misleidend omdat de gescande packages niet in context van het gebruik worden bekeken. Stel, er zit een security issue als je een onderliggend stukje software op een bepaalde manier gebruikt. Maar als je het dan niet zo gebruikt speelt het security issue niet. Deze nuance wordt niet gemaakt in de scan en dus vind de scan het een security issue.
3. De onderliggende container van Open Zaak op Artifacthub gebruikt Debian als besturingslaag. Debian is een van de veiligste en meest stabiele besturingssystemen maar bevat wel onnodig veel libraries, zelfs als deze niet gebruikt worden. Ook (en dit is wat technisch) zijn de versies van packages niet representatief in security scans. Dat komt omdat Debian eigen patchlevels toevoegt. Die patchlevels lossen security issues op maar vaak zonder dat ze het versienummer van de software zelf ophogen (omdat alleen het security issue is opgelost, en niet de software is geupdate).

Vrijwel elk populair project scoort een F op Artifacthub. Zelfs de [container voor de Artifacthub-applicatie zelf scoort een een F](https://artifacthub.io/packages/helm/artifact-hub/artifact-hub). Verder scoren MySQL, Keycloak, Kafka, Wordpress, Elasticsearch, Gitlab-runner allemaal een F. Dit wordt allemaal veroorzaakt door de hierboven genoemde punten 2 en 3.

**Gaan jullie er wat aan doen?**

Ja. We willen gebruikers zo goed mogelijk beschermen en helpen. Zelfs als er via onofficiële kanalen Open Zaak wordt aangeboden, willen we daar wat aan doen.

Het Open Zaak community team neemt contact op met de beheerder van de Artifacthub versie, en zal deze overnemen, of proberen te verwijderen. Daarnaast zullen we (om punt 3 aan te pakken) onnodige libraries verwijderen zodat deze ook geen negatieve impact hebben op de rating. Ze zijn immers onnodig.

Ook staat er een PR klaar om de Helm charts (die gebruikt worden door Artifacthub) [te voorzien van Open Zaak 1.5](https://github.com/open-zaak/charts/pull/18) maar deze worden door de community onderhouden.

De score zelf kunnen we wellicht niet veranderen omdat, zoals aangegeven, er geen context is bij een geautomatiseerde security scan. Een juiste score kan alleen bepaald worden door een security analist.

We laten dit issue open totdat bovenstaande is aangepakt.

**Comment by Hugo-ter-Doest** [comment]
@joeribekker Dank voor je heldere uitleg. Bij de volgende bijeenkomst van de OpenZaak Kerngroep kunnen we dit goed uitleggen.

**Comment by bartjkdp** [comment]
Artifacthub host zelf geen versie van Open Zaak maar verwijst naar de Docker image op Dockerhub.

**Comment by sergei-maertens** [comment]
Open Zaak 1.6.0 is now also published in the Helm Charts, and the rating stays "F" on Artifact Hub: https://artifacthub.io/packages/helm/open-zaak/open-zaak/

Per the above reasoning, this is no reason for concern. Looking at the reported vulnerabilities, they are present in libraries that are not actively used by Open Zaak/Open Notificaties, but only present in the base install or some devops tools added to monitor/debug running containers.

I'm closing this issue with the reasoning that the security scans "reveal" false positives that are not actually a problem for Open Zaak itself, a problem that exists with all automated security scanners. Context is important!
