### ISSUE TITLE
Verplicht veld 'Procestermijn' bij resultaattype geeft Error bij importeren zaaktype

### ISSUE THREAD

**Issue by OlavAllema** [open-zaak/open-zaak#1107]
**General information**
Open Zaak version: 1.5

**Describe the bug**
Verplicht veld 'Procestermijn' bij resultaattype geeft Error bij importeren zaaktype. 
Wanneer we een zaaktype willen importeren, krijgen we de volgende foutmelding:
<img width="990" alt="image" src="https://user-images.githubusercontent.com/75848616/156573179-d31588ef-ae4b-43ff-9e3e-de7d1ffb1f69.png">

Er wordt dus gevraagd om het veld 'Procestermijn' leeg te laten. Alleen, als we bij het gedeelte 'Bepaling brondatum archiefprocedure' kiezen voor de afleidingswijze 'Ander datumkenmerk', dan zijn we verplicht om het veld 'Procestermijn' te vullen:
<img width="678" alt="image" src="https://user-images.githubusercontent.com/75848616/156573761-ec2076af-9143-4e40-9d59-4867ae4cf2ea.png">

**To Reproduce**
1. Maak zaaktype aan met procestype 11. 
2. Maak een resultaattype met selectieklasse 11.1.  
3. Dit is een resultaattype met 'een belang na het vervallen van de zaak'. Daarom is het verplicht een andere afleidingswijze te kiezen dan 'Afgehandeld'. 
4. Kies voor 'Ander datumkenmerk'
5. Vul de verplichte velden in (dus ook Procestermijn).
6. Opslaan
7. Exporteer het zaaktype
8. Importeer het zaaktype (in een andere catalogus)
> ERROR 

**Expected behavior**
We verwachten dat de import wel lukt.

**Comment by joeribekker** [comment]
Hmm, vreemd maar klinkt inconsistent naar inderdaad.

**Comment by sergei-maertens** [comment]
Smells like an admin bug indeed - need to validate with the API standard what the correct behaviour is and then either fix the admin or API (wherever the mistake is).

**Comment by OlavAllema** [comment]
Voor de zekerheid, gaat deze mee met 1.6.1?

**Comment by sergei-maertens** [comment]
Dat is het plan, maar ik kan helaas niets beloven!

**Comment by OlavAllema** [comment]
Dit wordt met de dag dringender voor onze klanten, omdat ze nu niet zelf zaaktypen kunnen 'uitrollen naar productie'. Wij moeten dat dan telkens in de backend doen. Zouden jullie daarom de prio voor deze iets omhoog kunnen doen?

**Comment by sergei-maertens** [comment]
Er wordt momenteel gewerkt aan API versie upgrades met een project (en budget) van gemeenten. Dit heeft daarom de hoogste prio. We snappen dat dit een probleem is, maar de bugfix hiervan steunt momenteel 100% op community support wat best-effort is, want op vrijwillige basis.

**Comment by sergei-maertens** [comment]
Patch is now pending review
