### ISSUE TITLE
As developer, I want Open Notificaties to have a retry mechanism

### ISSUE THREAD

**Issue by stevenbal** [open-zaak/open-zaak#1132]
... so it can still send notifications, despite failing the first X times (assured delivery)

**Description**
The [automatic retry mechanism from Celery](https://docs.celeryq.dev/en/stable/userguide/tasks.html?highlight=automatic-retry-for-known-exceptions#automatic-retry-for-known-exceptions) could be used, with exponential backoff set to 5

**Comment by adgerrits** [comment]
In the Change Log I read that the default backend is switched to Redis instead of RabbitMQ. Unike RabbitMQ Redis supports only transient messages so how is reliability en retry handled in situations like a system-crash or reboot?

**Comment by sergei-maertens** [comment]
@adgerrits we still use RabbitMQ as message broker, i.e. the API receives the notification and the asynchronous workers are informed of the "distribute this notification to subscriber X" via RabbitMQ.

We use Redis now for the _result store_, which stores the result of such an asynchronous task. If a retry needs to happen, this is rescheduled through RabbitMQ as it uses the message broker and not the result store. The result store is used to track the return value of the async task and some metadata - and as you can see in the [code](https://github.com/open-zaak/open-notificaties/blob/main/src/nrc/api/tasks.py#L15), we don't have a return value for the task and all relevant error tracking is done in the database.

Finally, redis can be configured to to store snapshots (which it does by default every 15 minutes off the top of my head) - you can lower this to a smaller interval or even every X transactions if my memory serves me well. In those cases, it is also advised to run Redis in append-only mode.
