### ISSUE TITLE
Als kubernetes engineer van een gemeente wil ik graag dat de ansible playbooks voor Openshift omgeving ter beschikking zijn gesteld

### ISSUE THREAD

**Issue by RvdKlip** [open-zaak/open-zaak#1174]
Gemeente Rotterdam gebruikt Ansible als installatietool en OpenShift als managementoplossing voor containers. De Ansible Playbooks zijn hiervoor geschikt gemaakt in samenwerking met Maykin Media.  Het zou fijn zijn als deze playbooks ook ter beschikking worden gesteld aan de community en dit ook als zodanig in de documentatie wordt verteld.

**Comment by sergei-maertens** [comment]
Ik meen me te herinneren dat de nodige changes op gebied van security context etc. al in https://github.com/open-zaak/ansible-collection zitten, maar ik check bij mijn collega om te zien of dit alles is wat nodig is.

**Comment by sergei-maertens** [comment]
De OpenShift-specifieke zaken zoals security contexts + service account aanmaken/specifiëren zijn allemaal ingesloten in de ansible collections die we publiceren en dus beschikbaar voor de community. Uiteindelijk zijn dit nog steeds kubernetes-constructies die ook voor niet-openshift platformen beschikbaar zijn, daarom worden we ook niet als openshift-specifiek aangemerkt in de documentatie.
