### ISSUE TITLE
Als frontend developer wil ik minder calls doen naar OpenZaak, 

### ISSUE THREAD

**Issue by RvdKlip** [open-zaak/open-zaak#1175]
zodat ik de performance optimaliseer, complexiteit reduceer en de foutgevoeligheid/foutafhandeling verlaag (en daarmee het beroep op functioneel beheer verminder). 

Dit kan bijvoorbeeld op niveau van: _Opvragen zaak_ & _Aanmaken van een zaak_

**Opvragen zaak uit OpenZaak**
Om een overzicht op het scherm te maken van een zaak moeten er een aantal calls gedaan worden naar OpenZaak. Voor het tonen van de zaak met: de laatste status, resultaat, 1 document (met naam), aanvrager, 1 zaakobject en 1 eigenschap moeten er in totaal 9 aanroepen gedaan worden naar de zaken API en dan nog 5 à 6 naar de zaak catalogus om URL's te vertalen naar zinnige teksten (v.b. status URL, zaaktype URL). Deze laatste kunnen we eventueel cachen. Zijn er meer documenten, of als er nog geen resultaat is, kan het aantal calls iets meer zijn. Wil je een besluit tonen dan komen er weer een aantal calls bij. 

Als één van deze calls fout gaat dan kan er geen complete zaak getoond worden.
Aanroepen:
•	Zaak
o	ZaakType voor naam van de zaak (Ztc)
•	ZaakInformatieObjecten (Documenten)
o	Per object het enkelvoudigInformatieObject. Hierin staat de naam van het document
•	Rollen voor aanvrager
o	I.v.m. dynamische betrokkene moet ik per type (5x) een Request doen.
o	Per rol het RolType (Ztc)
•	Zaakobjecten (Boom)
•	Eigenschappen
o	Per eigenschap nog de EigenschapType omschrijving (Ztc)
•	Laatste Status
o	StatusType met omschrijving (Ztc)
•	Resultaat
o	ResultaatType voor naam (Ztc)

**Aanmaken van een zaak in OpenZaak.**
Om dezelfde zaak aan te maken zijn 7 REST calls nodig. Als er meer of minder documenten en eigenschappen zijn kan dat meer of minder REST calls zijn. Elk van deze REST calls kan fout gaan. Als dit gebeurt dan staat er maar een halve zaak in OpenZaak. We zetten daarom de status als laatste zodat een BackOffice applicatie niet te vroeg een zaak oppakt.
Voor een applicatie betekent dit ook dat er uitgebreide foutafhandeling nodig is om de gefaalde stappen opnieuw uit te voeren. Al dan niet geautomatiseerd maar uiteindelijk door interventie van functioneel beheer.
Een voorbeeld wat fout kan gaan is het toevoegen van documenten (enkelvoudige data objecten). Hier zijn 2 REST calls voor nodig. De eerste om een document aan te maken en een tweede om het document te koppelen aan de zaak. Gaat de eerste call fout dan is er geen document toegevoegd aan de zaak; gaat de 2e call fout dan zit er wel een document in het zaak systeem maar die is aan geen enkele zaak gekoppeld.

De stappen zijn:
•	Zaak aanmaken (verplicht)
•	Rol; aanvrager toevoegen (procedureel verplicht)
•	Zaakobject toevoegen (zoals een Boom/ ObjectAPI object) (0-n)
•	Eigenschappen toevoegen (0-n)
•	Aanmaken document(en) (0-n). Twee REST calls per document
o	EnkelvoudigInformatieObject (document aanmaken)
o	Informatie Object (document koppelen aan de zaak)
•	Status aanmaken (procedureel verplicht)

In de huidige zaaksystemen van de Gemeente Rotterdam is het mogelijk om al de stappen in 1 Webservice operatie uit te voeren. Het opvoeren van de zaak kan nog steeds fout gaan maar je hebt geen zaken die maar half zijn doorgezet.

**Comment by sergei-maertens** [comment]
Merk ook op dat er bij de standaard een discussie loopt over de lees-performance: https://github.com/VNG-Realisatie/gemma-zaken/discussions/1960
