### ISSUE TITLE
test.openzaak.nl crash: column "request_id" of relation "audittrails_audittrail" does not exist

### ISSUE THREAD

**Issue by sjoerdie** [open-zaak/open-zaak#1186]
**General information**
Open Zaak version: Latest

**Describe the bug**
test.openzaak.nl crash during django migrations:

`psycopg2.errors.UndefinedColumn: column "request_id" of relation "audittrails_audittrail" does not exist`

**Expected behavior**
Not crash

**Comment by sergei-maertens** [comment]
https://github.com/VNG-Realisatie/vng-api-common/pull/201 should fix this :crossed_fingers:

**Comment by sergei-maertens** [comment]
Fix verified - test.openzaak.nl is up again
