### ISSUE TITLE
Creating or updating a resource with invalid resource on urls that have resource validation gives incorrect error code

### ISSUE THREAD

**Issue by stevenbal** [open-zaak/open-zaak#119]
**Describe the bug**
When I try to do a `POST`, `PUT` or `PATCH` on any resource and I try to set the value of an attribute that has resource validation, I get a 400 with bad-url. For example, creating `EnkelvoudigInformatieObject` with an `informatieobjecttype` url that results in 200 but does not point to the correct resource (not an `Informatieobjecttype` in Catalogi API), I get a 400 with error code `bad-url`

**To Reproduce**
Try to create an EIO with for instance `informatieobjecttype` = https://google.com/ (or some other url that does result in 200)

this will return the following error:

```json
{
    "type": "http://localhost:8000/ref/fouten/ValidationError/",
    "code": "invalid",
    "title": "Invalid input.",
    "status": 400,
    "detail": "",
    "instance": "urn:uuid:26a4a0b5-f326-407b-90ed-8cc0a862fd88",
    "invalidParams": [
        {
            "name": "informatieobjecttype",
            "code": "bad-url",
            "reason": "Please provide a valid URL."
        }
    ]
}
```

**Expected behavior**
I would expect a response with error code `invalid-resource` instead of `bad-url`

**Comment by stevenbal** [comment]
Resources for which this is an issue:
- `Zaak.zaaktype`: returns code `bad-url`
- `EnkelvoudigInformatieObject.informatieobjecttype`: returns code `bad-url`
- `ObjectInformatieObject.object`: returns code `bad-url`
- `Besluit.besluittype`: returns internal server error (maybe issue with loose-fk?)

**Comment by annashamray** [comment]
@stevenbal 
About `bad-url` errors
In the issue https://github.com/open-zaak/open-zaak/issues/77 it was decided ok to have one error code for incorrect valued in internal-FK fields.

I'll take a look at 500 error with `besluittype`

**Comment by stevenbal** [comment]
Ok, so should I skip the tests that check for `invalid-resource` on these internal FK fields for now, or will the error codes remain `bad-url`? @sergei-maertens @joeribekker

**Comment by sergei-maertens** [comment]
I'd expect the same behaviour as reference implementation - if ref throws an `invalid-resource`, then open zaak should too.

**Comment by joeribekker** [comment]
The 500 issue was fixed, but can someone verify what Sergei said is the case? If not that should be fixed.

**Comment by annashamray** [comment]
@joeribekker 
I did some ugly workaround tor internal fk to support both 'bad-url' and 'invalid_resource' validation: https://github.com/open-zaak/open-zaak/pull/164 

For external fk as far as I can get it is a WIP (https://github.com/open-zaak/open-zaak/issues/128)

**Comment by sergei-maertens** [comment]
@stevenbal is this okay now after according to the newman tests?

**Comment by stevenbal** [comment]
@sergei-maertens the validation is now correct for internal FK, but for loose fk (`Besluit` in this case), I now get a `bad-url` where a `invalid-resource` would be expected:

```json
{
    "type": "http://localhost:8000/ref/fouten/ValidationError/",
    "code": "invalid",
    "title": "Invalid input.",
    "status": 400,
    "detail": "",
    "instance": "urn:uuid:860d53f5-5eed-4cd0-986c-f04334436919",
    "invalidParams": [
        {
            "name": "besluittype",
            "code": "bad-url",
            "reason": "Bad URL \"https://google.com\" - object could not be fetched. This *may* be because you have insufficient read permissions."
        },
        {
            "name": "besluittype",
            "code": "bad-url",
            "reason": "Bad URL \"https://google.com\" - object could not be fetched. This *may* be because you have insufficient read permissions."
        }
    ]
}
```
