### ISSUE TITLE
As admin i would like a screen which shows which zaakinformatieobjecttypen are related to a specific casetype

### ISSUE THREAD

**Issue by JurjenBert** [open-zaak/open-zaak#1193]
... so I can easily look up the above, since this is a selesction i need to make regularly when editing casettypes. 

The link for this selection - although absent in the admin-  is the following:.
... /admin/catalogi/zaaktypeinformatieobjecttype/

I have favourited the selection in my browser, but since this is one of the screens i visit the most in the admin op open zaak, being able to click ik in the admin would be of added value 

(btw. i find the link, by going clicking toon informatieobjecttypen for a catalogus, en then clicking on any link "toon zaakinformatieobjecten"
![afbeelding](https://user-images.githubusercontent.com/40294293/173033453-04a8a0bf-eb17-47ff-adc2-c5970ff4ad2e.png)

The i delete from the url everything after .../catalogi/zaaktypeinformatieobjecttype/ 
![afbeelding](https://user-images.githubusercontent.com/40294293/173033567-13b56bd3-22c4-4401-bdeb-0169daaa9e4c.png)

Then you get all zaakinformatieobjecttypen. This is the selection i would like to access directly. 
Within this selection i can limit it to a specific version of a  casetype. 

![afbeelding](https://user-images.githubusercontent.com/40294293/173033827-06fa509a-0cab-4be4-b55b-2664efa8f126.png)

**Comment by JurjenBert** [comment]
> Would it help to see this list in the detail page of a zaaktype (version)? Similar to the statustypen/resultaattypen/etc.

@sergei that would be perfect.

**Comment by JurjenBert** [comment]
relates to #1297 and #1298

**Comment by sergei-maertens** [comment]
I'm tentatively adding this to the 1.9.0 release cycle. Note that this is not a guarantee, depending on priorities/amount of other features in this milestone.
