### ISSUE TITLE
As admin, I want the zaakinformatieobjecten to be automatically coupled whith existing informatieobjecten during the import

### ISSUE THREAD

**Issue by JurjenBert** [open-zaak/open-zaak#1194]
Currently when importing a new version of a casetype i have to manually  search a an existing informatieobjecttype for all zaakinformatieobjecten. If the informatieobject does not exist i can use the calue create new. A pull down is provided to make these selections.  

This is problematic because of a number of reasons. First, it is hard to see if the informatieobject exist because the list gets very long after a while (think hundreds), and because existing values are not presented alfabetically.
This means that is takes a lot of effort making all the selections. It is also prone to mistakes, eg because i accidently left a Create new where the informatieobject already exisited. When this happens i lose all my selections and have to start all over again 
This also happens if i coupled all zaakinformatieobjecten correctly, but there is an issue with the startdate of the new version and enddate  of the old version. 

This could be improved strongly by automatically making the selection  of combinations of informatieobject bij zaakinformatieobjecten. If the informatieobject does not exist, the choice should be  Create new. 

This what the start of the import process looks like currently. When the amount of informatieobjecten exceeds 30 or 40 the import is no longer workable.  

![afbeelding](https://user-images.githubusercontent.com/40294293/173031330-57f12616-aec1-4037-8bae-8289e5819b70.png)

**Comment by sergei-maertens** [comment]
I agree that this UI is not... the best :grimacing: Unfortunately, I don't think there are any resources or budget at the moment to pick up this improvement. Our efforts are focused on implementing the latest versions of the APIs as commissioned by another organization, and fixing bugs.

That being said, an initial question:

* How would this work if there are different versions of an informatieobjecttype - what's the logic to select the "right" version?

**Comment by JurjenBert** [comment]
Good point about the different versions. The user story needs some refinement. 
For me this is a must have for proper manegement of casetypes, and i will discuss funding with my superior :)

**Comment by JurjenBert** [comment]
relates to #1279

**Comment by JurjenBert** [comment]
#1086 is superfluous

**Comment by JurjenBert** [comment]
this seems to be happening.
