### ISSUE TITLE
As admin, I want to configure Open Notificaties environment via the admin UI

### ISSUE THREAD

**Issue by stevenbal** [open-zaak/open-zaak#1203]
... so I can easily change the setup without having to alter environment variables and do a new deploy

**Description**
The following variables should be configurable via the admin UI:
- `NOTIFICATION_DELIVERY_MAX_RETRIES`
- `NOTIFICATION_DELIVERY_RETRY_BACKOFF`
- `NOTIFICATION_DELIVERY_RETRY_BACKOFF_MAX`
- `LOG_NOTIFICATIONS_IN_DB`?

**Comment by stevenbal** [comment]
I checked what the status of this is:
- currently the settings for Open Notificaties retry behavior (retrying of sending notifications to subscribers) is only configurable via envvars
- the linked PR (https://github.com/open-zaak/open-notificaties/pull/70) removes these settings and replaces them with admin configurable settings

@annashamray @joeribekker since we now have django-setup-configuration, what would be the correct approach here? I think we might want to keep the envvars, but use them for setup-configuration to configure the model instead of using those settings at runtime

**Comment by joeribekker** [comment]
Refinement:

> I think we might want to keep the envvars, but use them for setup-configuration to configure the model instead of using those settings at runtime

Yes
