### ISSUE TITLE
PUT and PATCH should be possible on resources in Catalogi API

### ISSUE THREAD

**Issue by stevenbal** [open-zaak/open-zaak#121]
**Describe the bug**
Currently it is not possible to do (partial) updates on resources in the Catalogi API, this should be possible

Validation rules should apply to this as described in the [standard](https://github.com/VNG-Realisatie/gemma-zaken/blob/master/docs/_content/standaard/catalogi/index.md#concepten)

see also the PR for this issue in the reference implementation: https://github.com/VNG-Realisatie/gemma-zaaktypecatalogus/pull/75

**Comment by joeribekker** [comment]
@stevenbal Can you port this to Open Zaak?
