### ISSUE TITLE
Creating a new version of a zaaktype is broken

### ISSUE THREAD

**Issue by sergei-maertens** [open-zaak/open-zaak#1211]
**General information**
Open Zaak version: 1.7.0 / latest

**Describe the bug**

It's no longer possible to create a new version of a (published) zaaktype through the admin interface. The admin says "fix the errors below", but no fields are marked as having errors, preventing the user from saving the zaaktype or correcting what's wrong.

This may also apply to documenttype/besluittype, so please double check.

**To Reproduce**
1. Create a zaaktype
2. Publish it
3. Try to create a new version of the zaaktype
4. Observe the cryptic validation error

**Expected behavior**

A new version of the zaaktype is created.

**Comment by stevenbal** [comment]
> This may also apply to documenttype/besluittype, so please double check.

We can only create new versions for `ZaakType`n, right? This doesn't seem to be implemented for documenttype/besluittype
