### ISSUE TITLE
As user of Open Zaak, I want Open Zaak to support Zaken API 1.2

### ISSUE THREAD

**Issue by stevenbal** [open-zaak/open-zaak#1218]
... so I can use the features described in https://github.com/VNG-Realisatie/zaken-api/blob/master/CHANGELOG.rst#120-2021-08-27

**Description**
Features from zaken API 1.2 should be added

Features:
- [x] ZaakObject put/patch/delete ([ref PR](https://github.com/VNG-Realisatie/zaken-api/pull/202))
  - https://github.com/open-zaak/open-zaak/pull/1221
- [x] ZaakEigenschap put/patch/delete ([ref PR](https://github.com/VNG-Realisatie/zaken-api/pull/195))
  - https://github.com/open-zaak/open-zaak/pull/1220
- [x] Zaakobjecten overige definitie ([ref PR](https://github.com/VNG-Realisatie/zaken-api/pull/203))
  - https://github.com/open-zaak/open-zaak/pull/1222

TODO:
- [x] Increment Zaken API version to 1.2 where needed

**Comment by sergei-maertens** [comment]
Aren't most of these things already implemented in https://github.com/open-zaak/open-zaak/pull/1022/? We made that PR from Utrecht which had it in the fork already :grimacing:

**Comment by sergei-maertens** [comment]
While comparing the schema against the VNG schema, it was obvious that the bugfixes that were applied to `1.1.x` were not applied to `1.2.x`, so VNG's 1.2.0 schema contains `ETag` cruft that shouldn't be there.

The crucial new features from 1.2 are implemented and I believe they are correct in our schema and VNG's, but on the other aspects our schema is a bit more correct :grimacing:
