### ISSUE TITLE
As user of Open Zaak, I want Open Zaak to support Documenten API 1.1

### ISSUE THREAD

**Issue by stevenbal** [open-zaak/open-zaak#1223]
... so I can use the features described in https://github.com/VNG-Realisatie/documenten-api/blob/master/CHANGELOG.rst#110-2022-06-30

**Description**
Features from Documenten API 1.1 should be added

Features:
- [x] Caching https://github.com/VNG-Realisatie/gemma-zaken/issues/1096, [PR in reference implementation](https://github.com/VNG-Realisatie/documenten-api/pull/88)
  - https://github.com/open-zaak/open-zaak/pull/1252
- [x] Large file uploads https://github.com/VNG-Realisatie/gemma-zaken/issues/1078, [PR in reference implementation](https://github.com/VNG-Realisatie/documenten-api/commit/b83efeef1db2bb3bb9e1134c2fd1e776cfe262c4)
  - https://github.com/open-zaak/open-zaak/pull/1240
- [x] Add verzoek type to possible ObjectInformatieObject.object_type and kcc to component enum, [PR](https://github.com/VNG-Realisatie/documenten-api/pull/104)
  - https://github.com/open-zaak/open-zaak/pull/1226

**Comment by stevenbal** [comment]
@sergei-maertens documenten 1.1 wasn't implemented in a fork by any chance right? :p https://github.com/open-zaak/open-zaak/issues/1218#issuecomment-1192708411

**Comment by sergei-maertens** [comment]
Not that I'm aware of, but you can see the open PRs yourself :P

**Comment by stevenbal** [comment]
@sergei-maertens question regarding `BestandsDelen` and CMIS: I assume we should store BestandsDelen in the connected DMS as well (requiring a new resource in the CMIS model)? Since it would not be possible to `.save()` a `BestandDeel` to the Django DB, because the related `informatieobject` is unsaved as well

**Comment by sergei-maertens** [comment]
> @sergei-maertens question regarding `BestandsDelen` and CMIS: I assume we should store BestandsDelen in the connected DMS as well (requiring a new resource in the CMIS model)? Since it would not be possible to `.save()` a `BestandDeel` to the Django DB, because the related `informatieobject` is unsaved as well

I did a quick check and afaik Alfresco doesn't necessarily have a maximum file size (though you can configure one). The bestandsdelen approach is to allow uploading large files even with maximum post body sizes at webserver config. In my opinion, we shouldn't create `Bestandsdeel` resource in CMIS, as they only interesting thing is the actual stitched-together file.

So, I would leave the `Bestandsdeel` resource completely in Open Zaak and not put that in CMIS. In the API schema, I don't see a reference to `informatieobject`. Maybe use a nullable FK for that field when not using CMIS, and a UUIDField to store the document UUID for when you are using CMIS?

Note that this will require Open Zaak to have the appropriate storage configured even when using CMIS to store the parts of the files.
