### ISSUE TITLE
As [functioneel beheerder], I want een duidelijkere foutmelding

### ISSUE THREAD

**Issue by SWFTessavdLaan** [open-zaak/open-zaak#1238]
In de openzaakbrug zien we de volgende fout voorbij komen: POST naar OpenZaak: https://.../zgw/documenten/api/v1/enkelvoudiginformatieobjecten niet geslaagd.

Open zaak geeft dan deze fout terug: 
I/O error on POST request for "https://../zgw/documenten/api/v1/enkelvoudiginformatieobjecten": Connection reset; nested exception is java.net.SocketException: Connection reset

Maar deze foutmelding is niet duidelijk. Graag zou ik hier duidelijkere informatie in willen ontvangen. Waarom is deze Post niet geslaagd? Ik vermoed dat de server dan niet bereikbaar is, dus dan zou ik dat graag in de melding willen hebben (+naam van de betreffende server).

**Comment by sergei-maertens** [comment]
Dit soort informatie komt nooit terug in foutmeldingen richting de client - dat is een veiligheidsrisico. Open Zaak ondersteunt het gebruik van Sentry voor fout-aggregatie waar wel gedetailleerde informatie beschikbaar is, en we raden met klem aan om hiervan gebruik te maken.

In dit geval lijkt er inderdaad een probleem te zijn met een achterliggende server, en wordt het foutbericht van die server doorgezet. Best kan je contact opnemen met de service provider die jullie Open Zaak installatie(s) beheert om meer informatie te verzamelen.
