### ISSUE TITLE
Making a webhook subscription from NRC requires the notificaties.publiceren permission

### ISSUE THREAD

**Issue by joeribekker** [open-zaak/open-zaak#1243]
**General information**
Open Zaak version: 1.7.x

**Describe the bug**
Making a webhook subscription from NRC requires the notificaties.publiceren permission (Step Open Zaak 3g), this is not mentioned in the docs nor does it seemed neccessery.

**To Reproduce**
Follow manual.

**Expected behavior**
Should work when following the docs (either adjust docs or code)

**Comment by alextreme** [comment]
op verzoek van @sjoerdie aangepast in #1259
