### ISSUE TITLE
As a user of Alfresco-DRC, I want this solution part of the product suite of Open-Zaak

### ISSUE THREAD

**Issue by shazada** [open-zaak/open-zaak#1246]
so I can use the github repo of Open-Zaak and be up-to-date

**Description**
- The Contezza Alfresco-DRC should become Open Source
- Images should be pushed to hub.docker.com so it can be pulled easily
- The current docker-compose-alfresco should be modified that it uses on default the Alfresco-DRC instead of the CMIS adapter or a new compose file should be made

**Comment by shazada** [comment]
This will be discussed at the next Technical Steering team which takes place on 7th September at 14:00

**Comment by sergei-maertens** [comment]
Discussed in the TSG, repository has been created and access given.

There is a gradual setup planned to get the code and quality of the entire project up to standards matching the open-zaak organization. Let's re-evaluate at the end of the year at the latest to see if those standards have been met.

I recommend using the issue tracker of the new repository to keep track of TODO's :-)
