### ISSUE TITLE
API create/update: Show conflicting identification number when returning a "identificatie-niet-uniek" error

### ISSUE THREAD

**Issue by alextreme** [open-zaak/open-zaak#1256]
## Gegevens aanvrager / information applicant

Organisatie / Organization: Maykin and gemeente SWF
Naam / Name: Alex and @EduardWitteveen  

### Probleem beschrijving / Problem description
This applies at least for the Document API, but most likely also for the Zaak API and Besluiten API.

Currently it isn't clear from the ValidationError raised via the API what the conflicting identification is from a "identificatie-niet-uniek" error. Without looking into Sentry for the identifier and without logging on the client side it isn't possible to determine for which case this error was raised.

Error message as currently logged:

ValidationError {'identificatie': [ErrorDetail(string='Deze identificatie bestaat al voor deze bronorganisatie', code='identificatie-niet-uniek')]}

### Oplossingsrichting / Solution direction
It would be best to have the error message show the conflicting identification when returning the error via the API:

ValidationError {'identificatie': [ErrorDetail(string='Deze identificatie (SWF-12345) bestaat al voor deze bronorganisatie', code='identificatie-niet-uniek')]}

This allows both the client to investigate directly using only the errormessage, and in OpenZaak the conflicting zaak can easily be found in the application log. 

This is an issue to improve maintainability and improve the developer-friendlyness of the APIs.

**Comment by Coperh** [comment]
Potential race condition. See: https://github.com/open-zaak/open-zaak/pull/1677#discussion_r1642893506
