### ISSUE TITLE
EnkelvoudigInformatieObject admin raises errors if CMIS_ENABLED=True

### ISSUE THREAD

**Issue by stevenbal** [open-zaak/open-zaak#1258]
**General information**
Open Zaak version: 1.7.3

**Describe the bug**
When using a DMS to store documents (`CMIS_ENABLED=True`), the Documenten admin list page `/admin/documenten/enkelvoudiginformatieobject/` raises a 500 error:

```
NotImplementedError at /admin/documenten/enkelvoudiginformatieobject/

Not all order keys in ['begin_registratie', 'begin_registratie', 'pk'] are implemented yet.
```

**To Reproduce**
1. Set `CMIS_ENABLED=True` in .env
2. Navigate to `/admin/documenten/enkelvoudiginformatieobject/`

**Expected behavior**
I would expect this page to either:
- Load properly and display some text explaining that the documents are store in the DMS instead
- Not be accessible at all, since it doesn't have any use when CMIS is enabled

**Comment by sergei-maertens** [comment]
It is useful to view the data (to debug things!), so read-only page/view seems appropriate to me.

**Comment by joeribekker** [comment]
@sergei-maertens disagree because this would bring more functions to the admin and we want to get rid of this.

Since documents are managed by a DMS, there should simply be a page stating:
"Documents are disabled and stored externally via CMIS. Use the DMS application to view documents."
