### ISSUE TITLE
Via de beheeromgeving is het niet langer mogelijk om een zaaktype met verlenging te publiceren

### ISSUE THREAD

**Issue by alextreme** [open-zaak/open-zaak#1275]
**General information**
Open Zaak version: 1.7.4

**Describe the bug**
Een zaaktype waarbij verlenging mogelijk is en waarvoor de verlengingstermijn is ingesteld is niet langer te publiceren. Je krijgt de melding:

"'verlengingstermijn' moet ingevuld zijn als 'verlenging_mogelijk' gezet is."

Taiga issue SWF 46, Bevestigd met voorbeeld-zaaktype https://test.openzaak.nl/admin/catalogi/zaaktype/32926/change/

Ik zie dat als ik beide waarden 'verlenging_mogelijk' en 'verlengingstermijn' print dat er tijdens het publiceren eerst een clean() plaatsvindt waarbij verlengingstermijn wel een waarde heeft, maar daarna is de relativedelta() leeg (validationerror in components/catalogi/models/zaaktype regel 321-328 ).

![image](https://user-images.githubusercontent.com/226839/195111343-8582bed3-7601-4869-9a3f-2a6f248e2fef.png)

Wellicht dat dit een relatie heeft met #1273 aangezien beiden met durationfields te maken hebben.

**To Reproduce**
1. Open concept-zaaktype waarbij verlenging mogelijk is
2. Probeer zaaktype te publiceren

**Expected behavior**
Dat je een concept-zaaktype met verlenging_mogelijk en een verlengingstermijn kan publiceren.

**Comment by alextreme** [comment]
Regressietest toegevoegd om het probleem te verduidelijken. Ik ben er nog niet achter waarom de verlengingstermijn op moment van publiceren automatisch wordt geleegd.

**Comment by sergei-maertens** [comment]
Ik heb tijd geblokt om hier volgende week goed naar te kijken
