### ISSUE TITLE
Do validation on external IO

### ISSUE THREAD

**Issue by sergei-maertens** [open-zaak/open-zaak#128]
Currently we only perform some of the validation on external informatieobjecten, this should do _all_ the validaton.

Codebase has been marked with `TODO` - this mostly concerns the checks when closing a case etc.

- [x] Validate that `EIO.status == "gearchiveerd"` when archiving ZAAK
- [x] Validate that `EIO.lock` is empty when closing ZAAK
- [x] Validate that` EIO.indicatieGebruiksrecht` is set shen closing ZAAK

**Comment by Hugo-ter-Doest** [comment]
Is this about validations that are part of the standard?

**Comment by sergei-maertens** [comment]
Correct
