### ISSUE TITLE
As developer I want Oracle database support

### ISSUE THREAD

**Issue by joeribekker** [open-zaak/open-zaak#130]
... so I can use our existing database infrastructure and tooling.

**Description**
Many municipalities use Oracle database 12.1 or higher.

Oracle database is supported by the framework but not by Open Zaak itself due to the use of PostgreSQL specific fields, long (causing duplicates) table names. To remedy this, we need to overhaul the database tables/attributes.

**Comment by Hugo-ter-Doest** [comment]
Eerst werkende registraties op basis van Postgres, daarna support voor andere databases.

**Comment by Hugo-ter-Doest** [comment]
Er is op dit moment geen concrete vraag, daarom naar prio laag. Kan hoger worden geprioriteerd als er behoefte is  vanuit gemeenten.
