### ISSUE TITLE
If a ZaakType is created through the admin panel the doorlooptijd_behandeling & servicenorm_behandeling fields are ignored

### ISSUE THREAD

**Issue by damm89** [open-zaak/open-zaak#1319]
**General information**
Open Zaak version: 1.7.5

**Describe the bug**
Whenever you save a new zaaktype the `doorlooptijd_behandeling` & `servicenorm_behandeling` fields aren't saved. Requires manual intervention from within the django shell to fix.

**To Reproduce**
1. Add new ZaakType through the admin panel.
2. Set a doorlooptijd_behandeling or servicenorm_behandeling.
3. Save the ZaakType.
4. The ZaakType object does not have the value that was set.

**Expected behavior**
The fields to assume the value that they were given.

See also #1325

**Comment by sergei-maertens** [comment]
@annashamray might be related to the earlier publish checks for those duration fields, #1275 and #1264

**Comment by annashamray** [comment]
@damm89 
Hi Daniel! I can't reproduce it at Open Zaak 1.8.1
Could you upgrade to OZ 1.8.1 and try again?

**Comment by damm89** [comment]
Okay that’s good news. We’re bumping to 1.8.x soon.

**Comment by joeribekker** [comment]
@annashamray can you test this on 1.7.5 just to be make sure we can reproduce Daniels' issue.

**Comment by annashamray** [comment]
@joeribekker No, I can't it reproduce it locally using `openzaak/open-zaak:1.7.5` docker image

**Comment by annashamray** [comment]
@damm89 
Could you export catalogi data for me? 
And can you try to reproduce the bug on the clean Open Zaak 1.7.5 instance?

**Comment by damm89** [comment]
Messaged you.

**Comment by damm89** [comment]
Related to fork (not sure how or why but I can reproduce it with the fork and not with the upstream). Can be closed.
