### ISSUE TITLE
Connection errors to Redis on test.openzaak.nl

### ISSUE THREAD

**Issue by Bartvaderkin** [open-zaak/open-zaak#1324]
**General information**
Open Zaak version: test.openzaak.nl

**Describe the bug**
Various API and admin operations generate errors and in Sentry I see Redis connection and transport errors, like:

"Retry limit exceeded while trying to reconnect to the Celery redis result store backend. "

"Error 99 connecting to localhost:6379. Cannot assign requested address."

**To Reproduce**
Do anything that touches redis like starting a Celery task. 

**Expected behavior**
No errors.

**Comment by annashamray** [comment]
It looks like there were some deployment error: `CELERY_*` env vars were not set in the web container. 
it works now.

**Comment by Bartvaderkin** [comment]
Cool, thanks for the solution!
