### ISSUE TITLE
Verlengingstermijn value ignored when publishing a zaaktype through admin panel

### ISSUE THREAD

**Issue by damm89** [open-zaak/open-zaak#1325]
**General information**
Open Zaak version: 1.7.5

**Describe the bug**
Whenever you try to publish a concept zaaktype in the admin panel and `verlenging_mogelijk=True` and `verlengingstermijn=<some-valid-value>` an error is shown saying `verlengingstermijn` needs to be set if `verlenging_mogelijk` is set. Requires manual intervention from within the django shell to fix. (obj.publish() does work)

**To Reproduce**
- Add new ZaakType through the admin panel.
- Set verlenging_mogelijk to True, add a verlengingstermijn (3 maanden in our case).
- Save the ZaakType.
- Publish ZaakType object.

**Expected behavior**
The zaaktype to be published without errors.

**Comment by damm89** [comment]
Messaged @annashamray  the data.

**Comment by sergei-maertens** [comment]
I'd expect [thist](https://github.com/open-zaak/open-zaak/blob/main/src/openzaak/components/catalogi/tests/admin/test_zaaktype_admin.py#L972) test case to cover your scenario. What is different that's causing this problem to still happen?

**Comment by sergei-maertens** [comment]
I'm also fairly certain the underlying cause is the same for this issue and #1319 as they're both dealing with duration fields.

**Comment by damm89** [comment]
Related to fork (not sure how or why but I can reproduce it with the fork and not with the upstream). Can be closed.
