### ISSUE TITLE
As admin i don't want to be able to publish a casetype without a doorlooptijd 

### ISSUE THREAD

**Issue by JurjenBert** [open-zaak/open-zaak#1338]
I can publish (and save) a casetype without a Doorlooptijd even though this seems to be a required field. 
I don't know if it is wrongly labeled as a required field (in bold), or if the corresponding check is missing.  
(tested in Open Zaak version: 1.7.5) 

update: When importing an exported castype, it is required. So i can save and publish a casetype without a doorlooptijd, but i cannot import it into another catalog because the doorlooptijd is missing.

**Comment by alextreme** [comment]
This has been resolved, at least in OZ v1.14:

![image](https://github.com/user-attachments/assets/acb8a732-c002-4219-b0f5-8971153b71e0)
