### ISSUE TITLE
ZTC doesn't allow spaces in zaaktype.eigenschap.specificatie.groep

### ISSUE THREAD

**Issue by MNIJ** [open-zaak/open-zaak#1341]
**General information**
Open Zaak version: 1.8.1
**Describe the bug**
When creating an `Eigenschap` for a Zaaktype in the ZTC, Open Zaak doesn't allow for spaces in the `specificatie.groep` property. It responds with a 400 and the message "Voer alleen letters, cijfers en/of liggende streepjes in."

I can't find a reason in the ZTC or imZTC specification why spaces shouldn't be allowed.

**Comment by sergei-maertens** [comment]
Do you know what the behaviour of the reference implementation is here?

**Comment by MNIJ** [comment]
The reference implementation allows this. See https://catalogi-api.vng.cloud/api/v1/eigenschappen/b148b5b0-b46d-40cb-8eeb-9a5630f2d257 for an example.
