### ISSUE TITLE
As a developer I want Postman tests in CI to work

### ISSUE THREAD

**Issue by annashamray** [open-zaak/open-zaak#1359]
Now Postmane tests in CI are failing: https://github.com/open-zaak/open-zaak/actions/runs/4688321713/jobs/8309422574?pr=1357
It happens because the data (or the ordering of data in Selectielijst API (https://referentielijsten-api.vng.cloud/api/v1/resultaten) was changed

The detailed explanation: 

* Postmane tests fail because one of the initial steps "Create Zaaktype"  returns 400 instead of 201.
* The error appears because we submit strange data in POST:

```
POST localhost:8000/catalogi/api/v1/zaaktypen

{
  "identificatie": "1",
  ...
  "selectielijstProcestype": "{{procestype_url}}"
}
```

* So Open Zaak responses with 400:
```
{
  │   type: 'http://localhost:8000/ref/fouten/ValidationError/',
  │   code: 'invalid',
  │   title: 'Invalid input.',
  │   status: 400,
  │   detail: '',
  │   instance: 'urn:uuid:a50ce0dc-6f22-4b55-8c61-cd32f8182bda',
  │   invalidParams: [
  │     {
  │       name: 'selectielijstProcestype',
  │       code: 'bad-url',
  │       reason: "De URL {{procestype_url}} kon niet opgehaald worden. Foutmelding: Invalid URL '{{procestype_url}}': No scheme supplied. Perhaps yo
  │ u meant http://{{procestype_url}}?"
  │     },
  │     { name: 'selectielijstProcestype', code: 'invalid', reason: 'Voer een geldige URL in.' }
  │   ]
  │ }
```
* The only place where `procestype_url` variable is assigned before this step is "(AC) Get Selectielijstklassen and Procestypen" step
* In this step we request a specific page of the url (GET https://referentielijsten-api.vng.cloud/api/v1/resultaten?page=3 ) and set `procestype_url` global var:
```
if(results[i].procestermijn == \"vast_te_leggen_datum\" && !pm.globals.get(\"selectielijstklasse_procestermijn_vast_te_leggen_datum_url\")) 
{
...
pm.globals.set(\"procestype_url\", results[i].procesType);
}
```
So we set it up only if there is a result with `procestermijn == "vast_te_leggen_datum"` on this page. But now there is no such a result here

The possible explanation is that VNG change the implementation of Selectielijst API from python to go and the ordering is now the same now.

**So the problem arised because:**
* we hardcoded the page number of external Selectielijst API in postman tests
* the external api changed its ordering

It should be fixed in order to keep Postman tests in CI

**Comment by sergei-maertens** [comment]
Looked a bit into this - this affects both `ZGW_OAS_tests.json` and `ZGW_api_postman_tests.json` in https://github.com/VNG-Realisatie/gemma-postman-tests

They both have similar but not identical requests.

Essentially, what they do for `Get Selectielijstklassen and Procestypen` is to try and find records on a page that match each of these:

```
if(results[i].procestermijn == "nihil"
if(results[i].procestermijn == "ingeschatte_bestaansduur_procesobject"
if(results[i].procestermijn == "vast_te_leggen_datum"
```
and sets the respective variables to be used later in the tests.
