### ISSUE TITLE
Performance optimization: list endpoints slow due to permission checks

### ISSUE THREAD

**Issue by stevenbal** [open-zaak/open-zaak#1365]
Master US - https://github.com/open-zaak/open-zaak/issues/1344
Taiga issue 454

Performance testing showed that several list endpoints are slowed down if a JWT without superuser permissions:
- GET openzaak.components.zaken.api.viewsets.RolViewSet  
- GET openzaak.components.zaken.api.viewsets.ZaakInformatieObjectViewSet  
- GET openzaak.components.zaken.api.viewsets.StatusViewSet

Notes:
- determining the `count` for pagination seems to be the bottleneck here as well, in this case because the query contains an `INNER JOIN` on the `zaken_zaak` table, which seems to reduce performance significantly. I tested locally with a simple query: `SELECT COUNT(*) FROM "zaken_rol" INNER JOIN "zaken_zaak" ON ("zaken_rol"."zaak_id" = "zaken_zaak"."identificatie_ptr_id")`, this query takes around 800ms on my machine

**Upd. by Anna**
The optimization is done in several steps (and PRs):
1. use only "pk" in pagination count for all viewsets - PR https://github.com/open-zaak/open-zaak/pull/1405 - **OZ 1.9**
2. optimize authorization filtering (initially developed in PR #1368, then cherry picked into new PR #1406) - **OZ 1.9**
3. introduce fuzzy pagination - https://github.com/open-zaak/open-zaak/pull/1368 - planned for **OZ 1.11**

**Comment by stevenbal** [comment]
I looked into this, I noticed that removing ordering from the authorization query improves performance by quite a bit, but it still remains fairly slow due to the inner join it seems

**Comment by joeribekker** [comment]
I made a ticket for this at VNG: https://github.com/VNG-Realisatie/gemma-zaken/issues/2284

**Comment by annashamray** [comment]
I'll separate this into two parts:
1. optimize pagination.count by removing unnecessary joints
2. introducing `FuzzyPagination`

The first part doesn't create deviations from the standard, but can add some performance boost, so I'll add it in Release 1.9
