### ISSUE TITLE
[FEATURE-REQUEST] Ontsluit ZaakKenmerk via de admin van de Zaak

### ISSUE THREAD

**Issue by alextreme** [open-zaak/open-zaak#1382]
## Gegevens aanvrager 

Organisatie / Organization: Maykin
Naam / Name: Alex
Taiga: DH ZGW #474

### Probleem beschrijving / Problem description

Het viel op dat 'zaakkenmerk' wel via de API maar niet via de admin zichtbaar was

### Oplossingsrichting / Solution direction

Het zou handig zijn om zaakkenmerk als inline te ontsluiten bij een zaak

**Comment by JanBrek** [comment]
Deze wordt steeds interessanter om in de UI te zien omdat dat gebruikers ook beter op de hoogte stelt van deze functionaliteit en deze best handig kan zijn mits goed gebruikt
