### ISSUE TITLE
Improve performance in EIO-list

### ISSUE THREAD

**Issue by joeribekker** [open-zaak/open-zaak#1401]
Version: 1.8.2-performance-fixes

Bestandsdelen seems to be retrieved individually (!) for each EIO because its called via a function and bestandsdelen are not part of the select/prefetch related:

![image](https://github.com/open-zaak/open-zaak/assets/96970/1ee9ff21-19ae-49e1-b346-607ca1b47fe3)

Caused by no prefetch:

![image](https://github.com/open-zaak/open-zaak/assets/96970/258b54c9-bda3-4f39-b3a9-583fccb0103b)

And called here:

![image](https://github.com/open-zaak/open-zaak/assets/96970/f8041583-3db5-4749-a57d-d616876370f7)

**Comment by annashamray** [comment]
@stevenbal Is it the same issue as https://github.com/open-zaak/open-zaak/issues/1363 ?

**Comment by annashamray** [comment]
It should be fixed when https://github.com/open-zaak/open-zaak/issues/1363 is merged

**Comment by joeribekker** [comment]
@annashamray can you doublecheck locally if the bestandsdelen query is not done a zillion times?

**Comment by annashamray** [comment]
I've double checked it. Instead of a zillion DB queries to `Bestandsdeel` model it produces only one now
