### ISSUE TITLE
Resultaat, Rol, Status and KlantContact are missing pagination

### ISSUE THREAD

**Issue by stevenbal** [open-zaak/open-zaak#141]
**Describe the bug**
The resources `Resultaat`, `Rol`,  `Status` and `KlantContact` are currently missing pagination in the API, these resources should all be paginated (just like in the reference implementation)

**Comment by stevenbal** [comment]
There is an issue with `KlantContact` when I try to query by page:

Request: `GET {{zrc_url}}/klantcontacten?page=1`
```json
TypeError at /zaken/api/v1/klantcontacten
'NoneType' object is not callable

Request Method: GET
Request URL: http://localhost:8000/zaken/api/v1/klantcontacten?page=1
Django Version: 2.2.4
Python Executable: /home/steven/Documents/VNG/open-zaak/env/bin/python
Python Version: 3.7.4
```

**Comment by joeribekker** [comment]
Can you also fix this on the reference implementation?

**Comment by annashamray** [comment]
The fix is in `vng_api_common`. After the new version is released I'll add it both to `openzaak` and to the `ZRC`

**Comment by sergei-maertens** [comment]
Pagination was introduced via #170 and #146
