### ISSUE TITLE
As supplier, I want to add new date attributes to Catalogi resources

### ISSUE THREAD

**Issue by annashamray** [open-zaak/open-zaak#1420]
It's a part of Catalogi 1.2 support

Master US - #1411
Related US in VNG: https://github.com/VNG-Realisatie/gemma-zaken/issues/1847, https://github.com/VNG-Realisatie/gemma-zaken/issues/1999, https://github.com/VNG-Realisatie/gemma-zaken/issues/2006
It is also described in the standard doc - https://vng-realisatie.github.io/gemma-zaken/standaard/catalogi/ 

According to Catalogi 1.2 OAS the new dates were added to the following resources
1. [x] Properties `beginGeldigheid` and `eindeGeldigheid` for resources:
   * Eigenschap
   * ResultaatType
   * RolType
   * StatusType
   * ZaakObjectType (new resource)

2. [x] Properties `beginObject` and `eindeObject` for resources:
   * BesluitType
   * Eigenschap
   * InformatieObjectType
   * ZaakType
   * ResultaatType
   * RolType
   * StatusType
   * ZaakObjectType (new resource)

**Questions about the new properties** 
I honestly don't understand the logic behind the properties and their relationship with each other. 
The reference implementation just add all these dates as optional to all the models without any defaults with the only validation  `beginGeldigheid <= eindeGeldigheid` and `beginObject <= eindeObject` 

1. What is the meaning behind `beginGeldigheid` and `eindeGeldigheid` for ZaakType subresources? Does it meant that we introduce versions for them? If yes what is the logic of versioning? Why are they needed for unpublished resources? 
2. What is the relation between `beginGeldigheid` and `eindeGeldigheid` of ZaakType subresources (such as RolType, StatusType etc) and  `beginGeldigheid` and `eindeGeldigheid` of ZaakType? 
    Are they the same? If yes, why are these dates writable for subresources? 
3. What is the meaning of  `beginObject` and `eindeObject`? If they are the actual dates of adding data in the system why are they writable? How is  `eindeObject` filled? 
4. What is the relation between (`beginGeldigheid` and `eindeGeldigheid`)  and  (`beginObject` and `eindeObject`)? Should they be validated against each other somehow?
5. Is there any example how to fill these dates for all Catalogi resources? 
6. **upd. new question**  Is it possible to have several versions of a subresource (like `statustype`) for 1 zaaktype now? if yes should we display all of them?

**Comment by joeribekker** [comment]
> 1. What is the meaning behind `beginGeldigheid` and `eindeGeldigheid` for ZaakType subresources? Does it meant that we introduce versions for them? If yes what is the logic of versioning? Why are they needed for unpublished resources?

> 2. What is the relation between `beginGeldigheid` and `eindeGeldigheid` of ZaakType subresources (such as RolType, StatusType etc) and  `beginGeldigheid` and `eindeGeldigheid` of ZaakType?
>    Are they the same? If yes, why are these dates writable for subresources?

They are NOT the same. The earlier versions basically assumed that they were and therefore these properties didn't exist for the subresources. However, you can now create a new `Zaaktype` version with the same `RolTypes`, `Statustypes`, etc. In that case, the `Zaaktype.beginGeldigheid` gets a new date but the `RolTypes`, `Statustypes`, etc. keep their original `beginGeldigheid` date.

> 3. What is the meaning of  `beginObject` and `eindeObject`? If they are the actual dates of adding data in the system why are they writable? How is  `eindeObject` filled?

Good question: Asked via VNG: https://github.com/VNG-Realisatie/gemma-zaken/issues/2332

> 4. What is the relation between (`beginGeldigheid` and `eindeGeldigheid`)  and  (`beginObject` and `eindeObject`)? Should they be validated against each other somehow?

As far as I can tell, you should see zaaktype versions as a collection, identified by the `zaaktypeidentificatie`. `beginObject` and `eindeObject` simply represent the earliest `beginGeldigheid` and latest `eindeGeldigheid` of this collection.

> 5. Is there any example how to fill these dates for all Catalogi resources?

Not that I can find :(

**Comment by annashamray** [comment]
@joeribekker  Thank you for the answers! I've added one more question in the US description

**Comment by joeribekker** [comment]
Should be tackled via VNG: object-dates are readonly.
