### ISSUE TITLE
As developer, I want to add `Zaakobject.zaakobjecttype` property

### ISSUE THREAD

**Issue by annashamray** [open-zaak/open-zaak#1457]
This is a part of adding support for Zaken API 1.3
Main issue - https://github.com/open-zaak/open-zaak/issues/1407
Related VNG issue - https://github.com/VNG-Realisatie/gemma-zaken/issues/1848

Depends on creating new Catalogi resource `ZaakobjectType` - https://github.com/open-zaak/open-zaak/issues/1419

**Questions**: 
* do we need to add extra validation on `ZaakObject` data in relation to `ZaakObjectType` ? 
* what is relation between `zaakobjecttype` field, `object_type_overige` and `object_type_overige_definitie` ?

**Comment by joeribekker** [comment]
> do we need to add extra validation on ZaakObject data in relation to ZaakObjectType ?

Same as other Catalogi API validators.

> what is relation between zaakobjecttype field, object_type_overige and object_type_overige_definitie ?

Questions asked here: https://github.com/VNG-Realisatie/gemma-zaken/issues/2341
