### ISSUE TITLE
`waarde` of ZAAKEIGENSCHAP is not validated by its EIGENSCHAP SPECIFICATIE

### ISSUE THREAD

**Issue by damm89** [open-zaak/open-zaak#1479]
**General information**
Open Zaak version: 1.8.2

**Describe the bug**
The value of a ZAAKEIGENSCHAP is not validated by the EIGENSCHAP SPECIFICATIE of the EIGENSCHAP.

**To Reproduce**
1. Create ZAAKTYPE
2. Create EIGENSCHAP for ZAAKTYPE (1) with a EIGENSCHAP SPECIFICATIE that has `formaat`: `Datum` (i.e. length must be 8).
3. Create ZAAK of ZAAKTYPE (1)
4. Create ZAAKEIGENSCHAP in ZAAK (3) with `waarde`: `asdasdasdasasd`. 
5. See there is no validation. Not through the admin nor the REST API.

**Expected behavior**
EIGENSCHAP SPECIFICATIE to be used as validation for the `waarde` of ZAAKEIGENSCHAP.

**Comment by joeribekker** [comment]
Refinement: @annashamray please check if this is documented in VNG spec. If not, let's do it and make an issue at VNG at the same time (no pr to VNG needed).

**Comment by annashamray** [comment]
I haven't found anything about `ZaakEigenschap.waarde` validation, so I've created a question in VNG repo - https://github.com/VNG-Realisatie/gemma-zaken/issues/2375
Therefore I'm not sure if it's a bug.

Anyway the validation against Eigenschap.specificatie seems like a very good idea

**Comment by annashamray** [comment]
Michiel from VNG said that there is no such requirement in the standard. So I'll remove "bug" tag from this US and we will treat it as a feature

**Comment by damm89** [comment]
First complaint: currently the `waarde` of a ZAAKEIGENSCHAP can be at least 1001 characters (just did a quick test for that number of characters lol).

The `lengte` of an EIGENSCHAPSSPECIFICATIE can only have a maximum value of 255. 

So currently this will break if any validation is done on an existing ZAAKEIGENSCHAP that already has a value of more than 255 (also, more than 255 is very much desired by our client VGU).

**Comment by joeribekker** [comment]
Well, thats according to the underlying information model. See here: https://www.gemmaonline.nl/index.php/Imztc_2.1/doc/attribuutsoort/eigenschap.specificatie_van_eigenschap.lengte

So, complaints about that part can be directed to VNG :)
