### ISSUE TITLE
As developer, I want to set up a test kubernetes for OpenZaak

### ISSUE THREAD

**Issue by joeribekker** [open-zaak/open-zaak#148]
... so I can do performance tests and create/verify documentation to setup such an environment.

**Description**
We need to set up a temporary kubernetes cluster to do both performance testing, find proper setups, and document our findings.

**Comment by sergei-maertens** [comment]
TODO: documentation

**Comment by sergei-maertens** [comment]
Environment is up and docs are ready for check-in
