### ISSUE TITLE
EIGENSCHAP SPECIFICATIE of `datum` must always have length 8 but zgw_consumers expects a different format

### ISSUE THREAD

**Issue by damm89** [open-zaak/open-zaak#1480]
**General information**
Open Zaak version: 1.8.2

**Describe the bug**
Related to: https://github.com/open-zaak/open-zaak/issues/1479
If you create a EIGENSCHAP that has EIGENSCHAP SPECIFICATIE with `formaat`: `Datum` its length _must_ be 8.
This should allow any length of any iso8601 date format (within the limits of the python version). Same for the `formaat`:`Datumtijd`.

**To Reproduce**
1. Create ZAAKTYPE
2. Create EIGENSCHAP with EIGENSCHAP SPECIFICATIE with `formaat`: `Datum`.
3. Try to enter a different length than 8.

**Expected behavior**
Open zaak to allow any valid iso8601 format for dates and datetimes as limited by the iso8601 formats supported by the standard `date` and `dateutil` packages in the python version.

**Comment by alextreme** [comment]
Discussed with Team Bron, @annashamray noted that in the ZGW API standard ISO 8601 isn't used for dates. The VNG ZGW API specifies dates as a 8-length field. See also:

https://github.com/VNG-Realisatie/gemma-zaken/issues/2106
