### ISSUE TITLE
As developer, I want to locate the performance bottlenecks on k8s

### ISSUE THREAD

**Issue by joeribekker** [open-zaak/open-zaak#149]
... so I can create User Stories to fix them or fix the configuration parameter immediately.

**Description**
Based on the initial results done by #17, we need to locate the issues (hotspots) that can be identified and create User Stories to fix the issues.

Let's focus on the technical performance tests since they are underlying the functional performance tests. Since most technical performance tests showed the same behaviour over all resources, we can take a single resource as starting point.

The following things need to be tested and measured on k8s. Tested against an endpoint that causes no database IO.

| Param                | Value          | Req./sec. | Error % |
|----------------------|----------------|-----------|---------|
| SSL-key              | RSA-4096       |           |         |
|                      | EC-256         |           |         |
| Loadbalancer type    | Traefik        |           |         |
|                      | Nginx          |           |         |

Using the optimum settings above, the database connections can be tweaked. Should be tested on k8s against an endpoint that causes database IO such as `/api/v1/zaken/<some uuid>`:

| Param                | Value          | Req./sec. | Error % |
|----------------------|----------------|-----------|---------|
| Database connections | default (*1)     |           |         |
|                      | double default |           |         |

\*1) [Depends on memory](https://stackoverflow.com/questions/51084907/how-to-increase-the-connection-limit-for-the-google-cloud-sql-postgres-database). With 2x n2-std-2 we have 16 GB of memory which comes down to 250 connections. You can overrule this with a flag.

**Comment by sergei-maertens** [comment]
Some key takeaways from keeping the hardware a constant:

* nginx ingress performs about 45% better than Traefik
* more replicas in the backend reduce the error rate substantially
* we're mostly CPU-bound, not memory bound

A lot of CPU resources go to fluentd (logging in kubernetes itself), so while the cluster is 4vCPU, it's rather 3.3-3.5 vCPU actually available. Of that, Traefik happily consumes 1.5-1.8vCPU, leaving only about 2 CPU for actual application load.
