### ISSUE TITLE
As developer, I want to restore descriptions for model.TextChoices

### ISSUE THREAD

**Issue by annashamray** [open-zaak/open-zaak#1490]
**Description**
After django choices were removed in https://github.com/open-zaak/open-zaak/issues/1418, the descriptions for some enums were sacrificed
Let's bring them back

**Tasks**:
* [x] restore descriptions in `commonground-api-common`
* [x] restore descriptions in `openzaak`

**Comment by Coperh** [comment]
Depends on: https://github.com/maykinmedia/commonground-api-common/pull/17 to be merged and released.

**Comment by Coperh** [comment]
Now waiting for https://github.com/maykinmedia/commonground-api-common/pull/19 to be merged.

**Comment by joeribekker** [comment]
Release 0.12.1 was approved. Anna will tag it to make the lib version available.
@Coperh can then continue with this PR/ticket.

**Comment by annashamray** [comment]
Commonground-api-common 1.12.1 is released

**Comment by Coperh** [comment]
Bug in commonground causes generate schema to crash. Issue with list of tuples.

https://github.com/maykinmedia/commonground-api-common/pull/20
