### ISSUE TITLE
[FEATURE-REQUEST] Longer JWT duration and a bit of leeway

### ISSUE THREAD

**Issue by alextreme** [open-zaak/open-zaak#1500]
## Gegevens aanvrager / information applicant

Organisatie / Organization: Maykin
Naam / Name: Alex de Landgraaf

### Probleem beschrijving / Problem description

I'm frustrated when writing one-off scripts that take longer than an hour to run, as after an hour my JWT token expires and I have to refresh and restart my script.

Now short-lived JWT's are recommended, however this tends to be the case with user-sessions instead of system-to-system integrations. I've also seen combinations of a short-lived session JWT token together with a JWT refresh token. It is possible to auto-renew the JWT token but this is more hassle for the client for little benefit security-wise.

Instead of redoing JWT's for Open Zaak, I'd suggest to simply extend the current duration of a JWT token from 1 hour to 1 day (or even 1 week) to make this more workable for longer-running scripts, migrations and the like.

I'd also recommend adding a few seconds of JWT clock-drift as I've seen this trip up users of Open Zaak that aren't perfectly aligned time-wise when using the API. Also here, this avoids unnecessary steps for API clients.

### Urgentie / Priority
low prio

**Comment by joeribekker** [comment]
Request was set out to the larger group.
