### ISSUE TITLE
Importing ZaakType with related Besluittypen isn't possible

### ISSUE THREAD

**Issue by Coperh** [open-zaak/open-zaak#1505]
Ref DH 463 (screenshots + zip available)

**Description**
Den Haag wanted to copy over the attached exported zaaktype from their test-environment (OpenZaak 1.8.1) to acceptance (OpenZaak 1.8.1) and production (OpenZaak 1.7.5).

Unfortunately this wasn't possible as long as the zaaktype had related besluittypen in the zip-file, this gives the following error:

> “Er deed zich een validatiefout voor bij de deserialisatie van een ZaakType {'besluittypen': [ErrorDetail(string='Ongeldige hyperlink - Object bestaat niet.', code='does_not_exist')]}”

Only after deleting the besluittypen in BesluitType.json and removing them from the ZaakType.json does importing the zaaktype work as expected.

**Comment by Coperh** [comment]
This issue is already solved with previous changes.

**Comment by alextreme** [comment]
Ref DH 550

**Comment by Coperh** [comment]
I still think that this is already solved. The zip provided without issue in v1.12. 

The zip without besluittypen file does cause the error as it still reference besluittypen without the file to provide them.
It is possible to add the Hyperlink to the error message but it would involve  extending `HyperlinkedModelSerializer` and copy/pasting a function and changing one line.

The zip giving an empty JSON file causes an uncaught JSON load error. It needs to discuss how this is handled.

**Comment by joeribekker** [comment]
Refinement: Discussed that this works. Closing until new info arrives.
