### ISSUE TITLE
ZaakInformatieObject allows PUT and PATCH but updates are blocked by signals in Documenten API

### ISSUE THREAD

**Issue by stevenbal** [open-zaak/open-zaak#151]
**Describe the bug**
According to the API spec of [Zaken API](https://test.openzaak.nl/zaken/api/v1/schema/#operation/zaakinformatieobject_update), it should be possible to do PUT and PATCH on `ZaakInformatieObject`, specifically on the fields `titel` and `beschrijving` (as `zaak` and `informatieobject` are immutable). However, when I try to do an update on a `ZaakInformatieObject`, I get the following error:

```python
File "/home/steven/Documents/VNG/open-zaak/src/openzaak/components/documenten/signals.py", line 40, in sync_oio
    raise RuntimeError("Updates to relation information are not allowed.")
RuntimeError: Updates to relation information are not allowed.
```

Should updates be allowed on the fields `titel` and `beschrijving`? Or should updates not be allowed altogether?

**Comment by sergei-maertens** [comment]
They should be allowed on those fields, this is a bug. We should probably check what change(s), check if it's a local FK and then allow the update to happen.

The API validation should have the relation fields immutable, the rest should work.
