### ISSUE TITLE
When removing an Application, I expect the underlying JWTSecrets to also be deleted

### ISSUE THREAD

**Issue by alextreme** [open-zaak/open-zaak#1515]
**General information**
Open Zaak version: 1.8.1

**Describe the bug**
Related to #1351 , I noticed that removing an Application via the admin doesn't remove the underlying client_id and secret instance (a vng_api_common.models.JWTSecret).

Security-wise this isn't an issue as due to removing the application there are no longer autorisations linked to the JWTSecret, however this blocks the ability to add a previously used client_id in a new Application so it can be an annoyance as via the admin you can't clean up the previously used JWTSecrets. And the expected behaviour is that when deleting the Application that also the related credentials/JWTSecret's are deleted.

Manually removing the JWTSecret via a shell ensures that the client_id can be created again:

`JWTSecret.objects.filter(identifier='foo').delete()`

Low-prio in my eyes

**Comment by stevenbal** [comment]
@alextreme are you sure this happens in Open Zaak? I implemented this a long time ago: https://github.com/open-zaak/open-zaak/blob/main/src/openzaak/components/autorisaties/admin.py#L107-L111

Locally this cascade seems to work fine. I didn't test on 1.8.1, but the change was in before that release

**Comment by alextreme** [comment]
@stevenbal I thought I was able to reproduce it on test.openzaak.nl, however on further notice I saw an application with the same client ID. I tried various combinations of applications with autorizations but I can't get the same problem anymore.

Lets close this issue, if it can be reproduced I'll open a new one
