### ISSUE TITLE
[FEATURE-REQUEST] Ability to make a concept-zaaktype without depublishing the published zaaktype

### ISSUE THREAD

**Issue by alextreme** [open-zaak/open-zaak#1532]
## Gegevens aanvrager / information applicant

Organisatie / Organization: DH
Naam / Name: 536

### Probleem beschrijving / Problem description
Currently when creating a concept-version of a published zaaktype you have to specify the enddate for the published zaaktype.

### Oplossingsrichting / Solution direction
It would be more logical to only require the enddate on the existing zaaktypewhen publishing the new version of the zaaktype (to avoid overlapping the old version). 

When publishing a conceptversion check the currently active version, and offer the option to automatically set the enddate / depublish the old version:

PA: "De mogelijkheid om een concept zaaktypen aan te maken zonder de actieve versie eerst te moeten depubliceren. 
Vervolgens bij het publiceren van een conceptversie een controle op actieve versies en de keuzemogelijkheid deze automatisch te depubliceren. Onafhankelijk van catalogus en/of omgeving."

**Comment by joeribekker** [comment]
Refinement: This requires us to make a database constraint more complex: We should include concept flag into the mix.
Let's double check if this is not specified somehow in the API specs from VNG.

**Comment by alextreme** [comment]
Afaik there already is a concept-flag for zaaktype. This is an import action which shouldn't modify the datastructure of zaaktypes.

It would require relaxing the database constraint, in that we limit this constraint to the published zaaktypes (eg. that you can have a concept-zaaktype with a beginGeldigheid/eindeGeldigheid that overlaps with a published zaaktype, however that once you publish the concept-zaaktype that it's mandatory to avoid overlap).

Looking at https://github.com/open-zaak/open-zaak/blob/main/src/openzaak/components/catalogi/models/mixins.py#L11 we have a GeldigheidMixin and a ConceptMixin, however there isn't a check in the GeldigheidsMixin if the object has a concept-status. In my eyes the GeldigheidMixin should only check for overlapping objects for non-concept / published objects.

![image](https://github.com/open-zaak/open-zaak/assets/226839/7574aa40-312f-475a-aaa9-305ab87343bf)

**Comment by alextreme** [comment]
Discussed with @Coperh and I'd want him to proceed with a suggested change, because no API or datamodel changes are necessary (afaik). A getattr to check if 'concept' exists on the instance within the geldigheidsmixin should be a workable approach

**Comment by alextreme** [comment]
Discussed with @joeribekker and he isn't against this change. It does have to be checked with @annashamray to ensure this doesn't cause surprises or block users when publishing zaaktypes via the admin

**Comment by annashamray** [comment]
@alextreme It should be fine, but I think API and admin should have the same checks for overlapping. But I agree that it make sense to exclude concept objects from this check
