### ISSUE TITLE
[FEATURE-REQUEST] auto-publish zaaktype including besluittypes/informatieobjecttypes

### ISSUE THREAD

**Issue by alextreme** [open-zaak/open-zaak#1533]
## Gegevens aanvrager / information applicant

Organisatie / Organization: DH
Taiga 537

### Probleem beschrijving / Problem description
Currently when publishing a zaaktype, all the related entities already need to be published. This requires additional unnecessary work because you have to publish these entities one by one.

### Oplossingsrichting / Solution direction
The idea is to have an option in the importer to auto-publish all relations below the zaaktype when you publish a zaaktype.

This to avoid the need to investigate which informatieobjecttypes still need publishing before it's possible to publish the zaaktype…

PA: "De keuzemogelijkheid om een geïmporteerd zaaktype direct te publiceren, inclusief onderliggende nog niet gepubliceerde relaties"

**Comment by annashamray** [comment]
Let's discuss this issue within the Open Zaak team
