### ISSUE TITLE
As developer, I want to remove check status!='definitief' from update/patch

### ISSUE THREAD

**Issue by annashamray** [open-zaak/open-zaak#1548]
Master US - #1464
Related VNG US - https://github.com/VNG-Realisatie/gemma-zaken/issues/2241
Related VNG PR - https://github.com/VNG-Realisatie/documenten-api/pull/212
Related question to VNG - https://github.com/VNG-Realisatie/gemma-zaken/issues/2390

**Question**
In Documenten API 1.2 a new permission scope `documenten.geforceerd-bijwerken` was introduced to allow changing documents with 
status='definitief'. Removing this check makes this scope useless
Should I remove this scope also?

**Comment by joeribekker** [comment]
Remove the scope and the validation.
