### ISSUE TITLE
Importing zaaktypes: When having overlapping IOTs it doesn't state which one it is overlapping with

### ISSUE THREAD

**Issue by alextreme** [open-zaak/open-zaak#1567]
**General information**
Open Zaak version: 1.10.2

**Describe the bug**
When encountering an overlapping IOT, the following message is shown. However it doesn't state which IOT the overlap is for, making importing the zaaktype when there are many IOTs very tricky

Er deed zich een validatiefout voor bij de deserialisatie van een InformatieObjectType {'begin_geldigheid': [ErrorDetail(string='Dit Informatieobjecttype komt al voor binnen de catalogus en opgegeven geldigheidsperiode.', code='overlap')]}

![image](https://github.com/open-zaak/open-zaak/assets/226839/07f2b4a1-bdad-4d72-8143-522936d275a7)

**Comment by Coperh** [comment]
This should be fixed in #1497 which was released with version 1.11

**Comment by alextreme** [comment]
Okay, this issue can be closed
