### ISSUE TITLE
500 error when accessing admin history

### ISSUE THREAD

**Issue by Coperh** [open-zaak/open-zaak#1571]
Ref: DH547
Sentry error in Open Zaak version: 1.10.2
Replicable in Open Zaak version: 1.11

**Description**
```
ValueError
Missing staticfiles manifest entry for 'vng_api_common/libs/bootstrap/css/bootstrap.min.css
```

500 error when admin accessing history e.g. /admin/catalogi/catalogus/1/history/

Commonground static files seem to no longer exists: 
https://github.com/open-zaak/open-zaak/blob/2188590fc74db79b733c1b1e13456847532cc28c/src/openzaak/templates/admin/object_history.html#L7C1-L16C15

**Comment by Coperh** [comment]
@annashamray @stevenbal 
Admin history imports static files from commonground that are not available any more. Do either of you know why this might be?
```
vng_api_common/libs/jquery/jquery-3.3.1.slim.min.js
vng_api_common/libs/bootstrap/js/bootstrap.min.js
vng_api_common/libs/bootstrap/css/bootstrap.min.css
```

**Comment by annashamray** [comment]
related us - https://github.com/open-zaak/open-zaak/issues/1512
