### ISSUE TITLE
Zaken API listview, slow queries

### ISSUE THREAD

**Issue by Coperh** [open-zaak/open-zaak#1574]
Ref: DH544

**Description**
* High DB CPU utilization (~100%)
* Lowest requests are the zaken listview API calls: GET /zaken/api/v1/zaken?page=1
* Duration of these requests under regular load: 2-9 seconds.
* Number of cases in Open Zaak: 62000

The Plan
- [x] get results for 1.10.3
- [x] get results for 1.12.x
- [x] test with fuzzy pagination
-  ~~test with join-refactor (todo)~~ see results of the performance tests

**Comment by joeribekker** [comment]
Refinement: Can you check if this PR solves the slowdowns? https://github.com/open-zaak/open-zaak/pull/1368

If so, let's just do this using an environment var to enable/disable this bahviour.

**Comment by alextreme** [comment]
Discussed, separate zaakidentificatie table seems to be in my eyes the problem for this however requires buy-in from Joeri to revisit

**Comment by sergei-maertens** [comment]
> Discussed, separate zaakidentificatie table seems to be in my eyes the problem for this however requires buy-in from Joeri to revisit

If you *do* revisit this, you'll need to do some serious load testing for zaak creation since that was the reason this change was made. There was a high failure rate without the separation, and 0% failure rate with the current implementation.

**Comment by joeribekker** [comment]
Refinement: Conor will do performance test on a OZ version that does NOT have the joined table thing, to see how much it actually saves in our tests env. Then we compare these numbers and see if its worth removing it at the cost of reliability or not (or make something new that is fast AND reliable!)

**Comment by annashamray** [comment]
The results of performance tests for Open Zaak 1.10, 1.12 with and without fuzzy pagination, 1.13 can be found on BitBucket
