### ISSUE TITLE
When specifying a Zaken API authorization with permissions linked to an internal zaaktype, deleting the zaaktype causes a 500 error

### ISSUE THREAD

**Issue by alextreme** [open-zaak/open-zaak#1584]
**General information**
Open Zaak version: 1.11
Rotterdam nr 80
Sentry 352159

**Describe the bug**
When specifying a Zaken API authorization with permissions linked to an internal zaaktype (eg. you check the zaaktypes individually using the 'Selecteer handmatig' option), deleting the zaaktype that is linked to the autorization causes a 500 error.

ZaakType.DoesNotExist
ZaakType matching query does not exist.
openzaak/components/autorisaties/utils.py in _get_related_object at line 30

A workaround is to delete the corresponding Autorisatie (but note that there isn't a FK so the zaaktype delete isn't cascaded to the authorizations)

I'd suggest to ignore autorizations to entities which no longer exist, if only to allow managing the autorizations. Normally zaaktypes aren't deleted, however this is something that can be done via the admin and was encountered during testing

**Comment by annashamray** [comment]
We have a signal `catalogi.sync_autorisaties_zaaktype` which should take care of it. 
I don't mind a workaround but I also think it would be good to analyze why this signal hasn't deleted autorizations. 

Could I ask you to reproduce following steps on this environment and provide logs:
* create a local zaaktype
* create an authorization with it
* delete this zaaktype

Also we did have problems with it in the past so we have a management command `sync_autorisaties`, which  
removes authorizations if zaaktypen, iotypen or besluittypen were deleted

**Comment by Coperh** [comment]
> Then Zaaktype is being deleted its url is build based on OPENZAAK_DOMAIN or Sites config.
If the signal doesn't do anything, it could mean that OPENZAAK_DOMAIN or Sites aren't configured properly. I think it should be investigated further.
