### ISSUE TITLE
As developer, I want to add batch authorizations in the configuration

### ISSUE THREAD

**Issue by annashamray** [open-zaak/open-zaak#1589]
**Description**
It's a part of step 2 of https://github.com/maykinmedia/django-setup-configuration/issues/1 

Authorizations have complicated structure, which should be put to yaml file. 
The path to yaml file should be configured with the env var. 
During one of the steps of `setup_confgiruation` data from yaml file should be loaded to the DB in the similar way as django fixture.

**Comment by joeribekker** [comment]
Refinment: duplicate of #1611
