### ISSUE TITLE
Creating an Informatieobjecttype with existing combination of catalogus and omschrijving gives internal server error

### ISSUE THREAD

**Issue by stevenbal** [open-zaak/open-zaak#159]
**Describe the bug**
When I try to create an `InformatieObjectType` in the Catalogi API with a combination of `catalogus` and `omschrijving` that already exists within the database, I get the following internal server error:

```json
IntegrityError at /catalogi/api/v1/informatieobjecttypen
duplicate key value violates unique constraint "catalogi_informatieobjec_catalogus_id_omschrijvin_6774690f_uniq"
DETAIL:  Key (catalogus_id, omschrijving)=(1, informatieobject) already exists.


Request Method: POST
Request URL: http://localhost:8000/catalogi/api/v1/informatieobjecttypen
Django Version: 2.2.4
Python Executable: /usr/local/bin/uwsgi
Python Version: 3.7.4
```

**Expected behavior**
I would expect an HTTP 400 to be returned with error code `unique` (`UniqueTogetherValidator`)

**Comment by annashamray** [comment]
fixed via afa8a21a1aa45e946966a574a3b828eb3b2cab4e
