### ISSUE TITLE
Verify that the Zaken API autorizations read-only permissions gives you /zaken/ and /zaken/{id} 

### ISSUE THREAD

**Issue by alextreme** [open-zaak/open-zaak#1591]
**General information**
Open Zaak version: 1.11

**Describe the bug**

Via Taiga AMS 14, it could be that we have a regression related to the 'zaken.lezen' authorization

> Na upgrade OpenZaak 1.10.0 naar 1.11.0 waren er twee van de zeven al eerder geconfigureerde API autorisatie applicaties die via de API wel een lijst met zaken mochten opvragen, maar geen specifieke zaak meer. Dit waren applicaties waarvan de autorisaties al in de 1.10.0 versie de autorisaties gezet zijn en niet veranderd. Voor de upgrade was het voor beide applicaties wel mogelijk om een lijst met zaken en een specifieke zaak op te vragen via de api

> Het vinkje zetten "heeft alle autorisaties" of een nieuwe applicatie aanmaken verhielp de problemen. Zodra het vinkje "heeft alle autorisaties" weer uitgezet werd, kon er alleen maar een lijst van zaken opgehaald worden, geen specifieke zaak

![image](https://github.com/open-zaak/open-zaak/assets/226839/d8234118-9982-4494-983d-d9eebd1d07ef)

**Comment by joeribekker** [comment]
Refinmenent: Still needs to be reproduced but case is: with scope zaken.lezen you can not read zaken....

**Comment by JanBrek** [comment]
Tested on The Hague T env (1.12). When setting a new authorisation on zaken.lezen this seems to work fine.
So probably only applicable when you already have zaken.lezen set in V1.10- and upgrade to 1.11+. Sadly we cannot really test this without potentially blowing up our A environment...

**Comment by alextreme** [comment]
@bart-maykin just to clarify, note that this issue mentions migrating from OZ 1.10 to 1.11 and that it can be resolved in v1.11 by re-creating the application. So if it occurs it's a datamigration issue

**Comment by bart-maykin** [comment]
I have tried to recreate this bug by creating the authorization in OZ 1.10 installations and upgrading them to OZ 1.11+ but can't seem to replicate the issue as described.

**Comment by alextreme** [comment]
Unable to reproduce and the DH v1.12 OpenZaak production upgrade went without reported issues
