### ISSUE TITLE
OPENZAAK_REWRITE_HOST & OPENZAAK_DOMAIN breaks external services, path isn't taken into account when determining the service

### ISSUE THREAD

**Issue by alextreme** [open-zaak/open-zaak#1592]
**General information**
Open Zaak version: 1.11

**Describe the bug**
Taiga AMS 13

When using OPENZAAK_DOMAIN with an API gateway (for instance api.amsterdam.nl with a subpath /openzaak), Open Zaak acts as if it has this domain.

This however breaks the determining if a URL is external or internal, leading to external Document APIs routed through the same hostname (api.amsterdam.nl/alfresco) being seen as local URLs instead of external URLs. As such, creating a zaakinformatieobject with a external alfresco URL is handled as a local URL and causes an error that the object can't be found.

https://github.com/maykinmedia/django-loose-fk/blob/84facdbae45be468aa7f0d4b2def6e6593e4d72e/django_loose_fk/drf.py#L48

`
>>> import logging
>>> from dataclasses import dataclass
>>> from typing import Tuple, Union
>>> from urllib.parse import ParseResult, urlparse
>>> s = "https://api.amsterdam.nl/ozgv-t/documenten/service/drc/v1/enkelvoudiginformatieobjecten/foo"
>>> urlparse(s)
ParseResult(scheme='https', netloc='api.amsterdam.nl', path='/alfresco/documenten/service/drc/v1/enkelvoudiginformatieobjecten/foo', params='', query='', fragment='')
>>> parsed = urlparse(s)
>>> parsed.netloc
'api.amsterdam.nl'
`

This is then the same hostname as OPENZAAK_DOMAIN, causing is_local to be True

**Comment by annashamray** [comment]
Discussed on slack. We will add extra option to `loose-fk` lib to explicitly set list of supported local paths, in case the Open Zaak and external services uses the same API gateway domain / hosted on the same domain
