### ISSUE TITLE
As an admin configuring a zaaktype I want to know what to do with the field Referentieproces 

### ISSUE THREAD

**Issue by alextreme** [open-zaak/open-zaak#1593]
**Description**
The field 'Referentieproces' is mandatory when creating a zaaktype, with no additional information about what to enter in this field.

Currently I recommend using 'Generiek werkproces' or 'Specifiek werkproces' in this field. However as far as I know no details about this field from Gemma/imZTC is available. 

Either mention these two strings in the Referentieproces field help-text or provide additional information what an admin user needs to do with this field

**Comment by Hugo-ter-Doest** [comment]
Ik denk een verwijzing naar een van de referentieprocessen die hier beschreven zijn: https://www.gemmaonline.nl/index.php/Procesarchitectuur_Referentieprocessen

**Comment by joeribekker** [comment]
Refinement: Add link to help text.
