### ISSUE TITLE
Check outgoing request logs, no longer working after v1.11?

### ISSUE THREAD

**Issue by alextreme** [open-zaak/open-zaak#1595]
**Description**
Open Zaak: 1.11 / latest
Taiga AMS 15

I no longer see outgoing request logs, client showed in a call that this worked until OZ 1.11 was deployed to their environment: 

https://test.openzaak.nl/admin/log_outgoing_requests/outgoingrequestslog/

**Comment by annashamray** [comment]
@alextreme 
I've checked config in `test.openzaak.nl`, and it looks like `LOG_REQUESTS` env var is not set. In Open Zaak `1.10.1` its default was changed to False, so if it's not set explicitly the logging won't happen. 
Related PR - https://github.com/open-zaak/open-zaak/pull/1488/files

Could Amsterdam have the same issue?

**Comment by annashamray** [comment]
@sjoerdie Could you please add env var `LOG_REQUESTS=yes` for Open Zaak deployment?

**Comment by sjoerdie** [comment]
Hello @annashamray ,

Thank you for your request. 

`LOG_REQUESTS` is now set to the value `yes`.

**Comment by annashamray** [comment]
@sjoerdie Thank you! Now it works in test.openzaak.nl

This config also solved the issue for Amsterdam, so I'll close the issue
