### ISSUE TITLE
Make "Label" configurable with setup_configuration command

### ISSUE THREAD

**Issue by sjoerdie** [open-zaak/open-zaak#1606]
Remove default data, see refinement comment

---

Om een feature request in te dienen gebruik dit template. 
To add a new feature request please use this template.

## Gegevens aanvrager / information applicant

Organisatie / Organization: Maykin
Naam / Name: Sjoerd
E-mailadres / e-mail address: sjoerd@maykinmedia.nl

### Omschrijving / Summary
The `setup_configuration` command always creates a notification service named:  `Notificaties API`

### Probleem beschrijving / Problem description
I find it slightly confusing, because the default example NRC services (https://notificaties-api.vng.cloud/api/v1/) is also called `Notificaties API`.

![image](https://github.com/open-zaak/open-zaak/assets/85243022/bc8b759a-64f2-48fc-97b5-34091d86a103)

### Oplossingsrichting / Solution direction
Make the label configurable with an environment variable, e.g. `NOTIF_OPENZAAK_LABEL` and / or have it default to `Notificaties API (auto)`.

### Urgentie / Priority
7

**Comment by joeribekker** [comment]
Refinement: Let's just remove this default value since no one will ever use the VNG service in real life OR for dev purposes.
