### ISSUE TITLE
Bij importeren (op acc/OZ 1.10) komen de besluittypes en informatieobjecttypes niet meer overeen

### ISSUE THREAD

**Issue by alextreme** [open-zaak/open-zaak#1609]
### Product versie / Product version

1.10, unsure about 1.12

### Omschrijf het probleem / Describe the bug

Taiga DH 564

When importing a zaaktype with besluittypen, the besluittypen-relations to informatieobjecttypen after importing on acceptance aren't the same as the ones on the testenvironment.

This was encountered when exporting from Open Zaak v1.12 (test) to Open Zaak v1.10 (acc), so unsure if this is still a case when importing into Open Zaak v1.12. It is at least something that can be investigated. 

See for screenshots and export Taiga. Can be worked around but requires un-publishing besluittypes from the django shell to allow correcting so isn't ideal.

**Comment by stevenbal** [comment]
I looked into this, I could reproduce the issue locally on 1.10.2 and if I tried the same import flow with 1.11.0 it worked correctly

**Comment by alextreme** [comment]
Sufficient for now, thanks for checking!
