### ISSUE TITLE
Allow CICD-configuration for authorisations

### ISSUE THREAD

**Issue by joeribekker** [open-zaak/open-zaak#1611]
### Thema / Theme

Other

### Omschrijving / Description

**Probleem**

1. Technische configuratie-items zijn niet via CI/CD pipeline te besturen:
• Dit zorgt ervoor dat alle configuratie handmatig moet worden uitgevoerd
• Elke gemeente moet separaat en handmatig worden geconfigureerd met veel deplicatie
• Het gevolg is dat Dimpact niet schaalbaar kan zijn als beheerorganisatie

2. Technisch en functioneel beheer zijn onvoldoende gescheiden
• Dit is een probleem aangezien gevolgen van aanpassingen voor technisch beheer groot zijn
(risico voor beschikbaarheid applicaties)
• Niet elke beheerder moet technisch beheer rechten krijgen en voor sommige gemeentes zal
alleen Dimpact het technisch beheer doen

**Acceptance criteria**

1. Technische configuratie kan programmatisch worden ingesteld vanuit de CI/CD pipeline
2. Dit is van toepassing op alle componenten die in gebruik zijn binnen PodiumD
3. Technisch beheer kan nog steeds via een GUI worden aangepast
4. Middels rollen en rechten is technisch beheer gescheiden van functioneel beheer

**Oplossingsrichting**

1. Er wordt van elk component een inventarisatie gemaakt welke environment variabelen wel/niet
ondersteund worden.
2. Er wordt overkoepelend bepaald welke environment variabelen nog moeten worden
toegevoegd.
3. Een aantal environment variabelen zal effect hebben op in de database opgeslagen waarden. De
database waarden worden overschreven met de waarden uit de environment variabelen.
4. Er komt in alle componenten een “setup_configuration” commando, waarmee environment
variabelen worden opgeslagen in de database. Dit commando kan middels een Kubernetes job
worden aangeroepen, met een init-container, of handmatig.
5. Een aantal configuratie instellingen zijn dermate uitgebreid dat deze niet met eenvoudige key-
value (standaard environment variabelen) methodiek kunnen worden opgegeven. Daarom zijn
sommige waarden middels een YAML-bestand in te laden, waarnaar verwezen kan worden met
een environment variabele. Het YAML-bestand zelf kan een gemounte ConfigMap zijn.
6. Environment variabelen die database waarden overschrijven die ook in de beheer UI zijn aan te
passen, blijven aanpasbaar in de beheer UI. Middels rechten kan je deze alleen-lezen maken. We
gebruiken hiervoor het standaard rechten-model in het technische framework, en bouwen geen
laag daar boven op.
7. Het einddoel is om Open Zaak en Open Notificaties volledig werkend en geconfigureerd te
hebben op een Kubernetes cluster, in het bijzonder op PodiumD, zonder dat in de
beheerinterface hoeft te worden ingelogd.

### Toegevoegde waarde / Added value

No more admin UI after deploy/update

**Comment by joeribekker** [comment]
Refinement: Don't dive into k8s but use Docker-compose, focus on loading in a yaml file with the data to configure the applications, from a mounted volume. We should look into a way to not ass secrets as is (the client secret) and not use database IDs - we could look at natural keys.

**Comment by joeribekker** [comment]
Good comment @stevenbal !!

Ad 1. Yes, we should assume the operation is idempotent. Thus, it can run every time, which doesn't lead to duplicates. Changing non-key details will overwrite the existing details.

Ad 2. This one we need to discuss but my idea is to have seperate file/export containing environment specific settings, for each environment.

**Comment by annashamray** [comment]
2. Our dear old issue with saving zaaktype urls for Authorizations. I think we can approach it iteratively. In the first stage we can use unchanged urls, and then if clients are not happy with it we can change it

**Comment by stevenbal** [comment]
We discussed this today: we will export the URLs and when importing we provide a mapping to map domains and we assume that the UUIDs match across different environments

**Comment by stevenbal** [comment]
As mentioned in the PR, this issue is blocked by https://github.com/open-zaak/open-zaak/issues/1661
