### ISSUE TITLE
Lopende zaken aanpassen met nieuwe info uit nieuwe versie zaaktype

### ISSUE THREAD

**Issue by OlavAllema** [open-zaak/open-zaak#1620]
### Thema / Theme

Catalogi API

### Omschrijving / Description

In de praktijk ervaren we dat er behoefte is aan het toepassen van wijzigingen aan een zaaktype en die toe te passen voor lopende zaken. Een nieuwe versie van een zaaktype is nu niet geldig voor lopende zaken.
Hoe staan jullie t.o.v. deze casus? Is dit een aanpassing die in Open Zaak zou moeten komen? Of zou deze behoefte ergens anders geregeld moeten worden?

### Toegevoegde waarde / Added value

Sommige zaken lopen lang. Er is dan kans dat er nieuwe metadata (nodig) is. De mogelijkheid om een lopende zaak bij te werken met nieuwe info uit een nieuwe versie van een zaaktype is er nu niet.

**Comment by joeribekker** [comment]
Very similar to #1621

**Comment by joeribekker** [comment]
Refinement: We decided that this goes against the standard AND the essence of the concept of versioning casetypes. Therefore, we will not make an experimental changes for this. The proper way to go is via VNG.
