### ISSUE TITLE
Document the usage of JWT tokens better, in various programming languages

### ISSUE THREAD

**Issue by alextreme** [open-zaak/open-zaak#1626]
### Thema / Theme

Other

### Omschrijving / Description

Discussed with Jan from Den Haag, lets improve the OpenZaak documentation regarding the usage of JWT's. Having a few examples of generating a JWT in various languages (PHP, Javascript etc) would help in API usage

**Comment by joeribekker** [comment]
Seriously, just Google it.

**Comment by joeribekker** [comment]
Alright, let's add an example to our documentation on how it looks, then how to generate the encoded version and how to sent it as header.

**Comment by alextreme** [comment]
Discussied:
- Point to https://open-zaak.readthedocs.io/en/stable/client-development/authentication.html from the API documentation (to avoid duplicate explanations)
- Expand the authentication documentation with examples for JS, Python (jwt library), PHP, Java (based on the recipe that Anna showed)
- Add reference from this page to https://vng-realisatie.github.io/gemma-zaken/themas/achtergronddocumentatie/authenticatie-autorisatie for the VNG-details


![image](https://github.com/open-zaak/open-zaak/assets/226839/b8babaeb-3b15-477b-accf-20b836298756)
