### ISSUE TITLE
Authorizations aren't being stored as expected

### ISSUE THREAD

**Issue by alextreme** [open-zaak/open-zaak#1636]
### Product versie / Product version

1.12

### Omschrijf het probleem / Describe the bug

Taiga DH 554

Als ik Autorisaties op een zaaktype probeer toe te voegen wordt dit niet doorgezet in een aantal gevallen.

Reproductie:   

1. Switch op de bestaande autorisatie van de zaken api de selectie van ‘Alle huidige en toekomstige…’ naar ‘Selecteer handmatig’
2. Vul bij zaken autorisaties een zaaktype uit de (onderste) catalogus en druk op opslaan.
3. Kijk daarna weer in het autorisatie overzicht. Het is niet doorgevoerd

----

Confirmed on https://test.openzaak.nl/admin/authorizations/applicatie/10654/autorisaties/

For the existing application toggle ‘Selecteer handmatig’ and select one or more zaaktypes. After saving the autorisaties are created, however I suspect that the existing autorisatie that gives permissions to all current and future zaaktypes isn't cleared as expected.

Workaround is to re-create the application with the correct authorizations, which is a bit of a pain

![image](https://github.com/open-zaak/open-zaak/assets/226839/381aa342-b31e-4110-b717-4e6592b73830)

**Comment by alextreme** [comment]
@joeribekker added to the team-bron board, this issue from DH has priority as it is seen as blocking on their end

**Comment by Coperh** [comment]
Backport needed. I do not know if it was done yet

**Comment by annashamray** [comment]
No, thanks for reminding

**Comment by annashamray** [comment]
Open Zaak 1.12.2 is released
