### ISSUE TITLE
Automatically generate documentation from environment variables

### ISSUE THREAD

**Issue by stevenbal** [open-zaak/open-zaak#1649]
Split off from https://github.com/open-zaak/open-zaak/issues/1629

In Open Inwoner there is functionality to generate documentation for `django-setup-configuration` steps. It would be good to make use of this functionality in our components as well.

Additionally we want something to generate the `env_config.rst` documentation based on envvars (that aren't used in `ConfigurationSteps`), to avoid having to manually write documentation for those as well.

Possible solution: in https://github.com/open-zaak/open-zaak/issues/1629 the utils for retrieving envvars is being moved to Open API Framework, we could modify `config` to also accept a `help_text` (and maybe `category` and `required` as well) and have `config` store this information in some object. Then we can add a management command that imports this object and generates docs from it. We could leave the `setup_configuration` envvars separate from these by not specifying a `help_text` for them

Components to update:
- [ ] Open Zaak https://github.com/open-zaak/open-zaak/pull/1725
- [x] Open Notificaties https://github.com/open-zaak/open-notificaties/pull/174
- [x] Objects/Objecttypes https://github.com/maykinmedia/objects-api/pull/425
- [x] Open Klant https://github.com/maykinmedia/open-klant/pull/206
- [x] Referentielijsten https://github.com/maykinmedia/referentielijsten/pull/19

**Comment by joeribekker** [comment]
Refinement: Implement this in the projects once they use OAf env settings.
