### ISSUE TITLE
Creating ZIOT with existing combination of Zaaktype and volgnummer gives internal server error

### ISSUE THREAD

**Issue by stevenbal** [open-zaak/open-zaak#165]
**Describe the bug**
When trying to create a `Zaaktype-Informatieobjecttype` in Catalogi API with a combination of `Zaaktype` and `volgnummer` gives the following internal server error:

```json
IntegrityError at /catalogi/api/v1/zaaktype-informatieobjecttypen
duplicate key value violates unique constraint "catalogi_zaakinformatieo_zaaktype_id_volgnummer_656b2060_uniq"
DETAIL:  Key (zaaktype_id, volgnummer)=(49, 1) already exists.


Request Method: POST
Request URL: http://localhost:8000/catalogi/api/v1/zaaktype-informatieobjecttypen
Django Version: 2.2.4
Python Executable: /usr/local/bin/uwsgi
Python Version: 3.7.4
```

**Expected behavior**
It would be expected that a 400 error is returned with the correct error code (using `UniqueTogetherValidator`)

**Comment by sergei-maertens** [comment]
Fixed via 552816000fa88852f4f3d9224c557ea51a4ba1d9
