### ISSUE TITLE
API uitbreidingen Zaken & Objecten

### ISSUE THREAD

**Issue by JanBrek** [open-zaak/open-zaak#1660]
### Thema / Theme

Zaken API

### Omschrijving / Description

Om efficienter queries te doen op de ZGW registraties wil ik het volgende voorstellen:
1. Query doen op meerdere zaaktypes
   - Momenteel is het mogelijk om een query te doen waarbij gefilterd word op zaaktype
   - Het zou fijn zijn om te kunnen filteren op meerdere zaaktypes (OR) zodat bij een bevraging over meerdere specifieke zaaktypes de paginering, ordering, etc geregeld is
    - Momenteel moeten nu meerdere queries gedaan moeten worden en dan client-side samengevoegd moeten worden tot een gepagineerd resultaat wat natuurijk erg inefficient en onhandig is
2. Page size op alle plekken waar 'page' opgegeven kan worden (bijv. ook bij rollen)
   - Het is mij een mysterie waarom de een er wel in zit en de andere niet
   - Bij bijv. Klantportaal Den Haag halen we vaak alleen de eerste +-5 zaken op voor het eerste overzicht. Nu halen we er 100 op en gooien er feitelijk 95 weer van weg (Default page size = 100)
   - Bij bijv. Klantportaal willen we een zoekbare, gepagineerde lijst weergeven voor zakelijke gebruikers (die veel zaken kunnen hebben). Hierbij zou het fijn zijn om geen paginas van 100 zaken hoeven laten te zien
3. Zoeken op zaak identificatie
   - Handig voor portalen enz.
4. Objecten data_attrs zoeken met 'OR'
   - Voorbeeld query; geef de taken (objecten) die bij een van deze zaaknummers (data attribuut) horen

### Toegevoegde waarde / Added value

- Grote reducering in aantal queries
  - In sommige gevallen exponentieel omdat je 2 lagen aan queries moet uitvoeren (voor ieder resultaat...)
- Werkende paginering en ordering (Omdat dit niet meer op de client samengevoegd hoeft te worden)

### Aanvullende opmerkingen / Additional context

Ik kan nog meer use-cases opleveren indien nodig

**Comment by flinden68** [comment]
Today we encountered a DataBufferLimitException in our service who is using OPenZaak. Could be caused by the amount of (related) data who are collected on a Zaak, like Documents etc. 
But the result of the default pageSize 100 in getZaken in OpenZaak could also cause this issue. 
PageSize as query parameter on getZaken will prevent (to) big responses from OpenZaak

**Comment by joeribekker** [comment]
@flinden68 that's not an exception Open Zaak can throw. Sounds like something else

**Comment by flinden68** [comment]
No it is not a OpenZaak exception, it is an exception from the Spring Framework which is caused by the amount of data returned from another API.

**Comment by joeribekker** [comment]
Ok, but you are talking about "this could cause that" but Open Zaak is not returning an error so if the error on your end is indeed caused by large responses (for you to check) then we can have a case to add a pageSize query parameter if that is your indirect question :)

**Comment by flinden68** [comment]
Of course we it as an error on 'our' side, probably caused by a (too) large response. So a pageSize query parameter will help us controle the reponse size a bit.

**Comment by joeribekker** [comment]
> Query doen op meerdere zaaktypes
This can already be done with `api/v1/zaken/_zoek` and pass `zaaktype__in`. See spec.

> Page size op alle plekken waar 'page' opgegeven kan worden (bijv. ook bij rollen)
Created a ticket for this: https://github.com/open-zaak/open-zaak/issues/1668

> Zoeken op zaak identificatie
This can already be done in both the `list` and `_zoek` endpoints.

![image](https://github.com/open-zaak/open-zaak/assets/96970/3b7664ae-8dc0-482f-86dc-8c9e310dbd05)

> Objecten data_attrs zoeken met 'OR'
Moved to Objects API repo: https://github.com/maykinmedia/objects-api/issues/411

And with that, I can close this issue :) See above for all related issues.

**Comment by flinden68** [comment]
@joeribekker goed om te weten dat we op meerdere zaaktypes kunnen zoeken. Als ik de API bekijk dan zie ik dat dat _zoek endpoint queryparameters en een request body heeft. En sommige kan je als Query parameter EN als request body meegeven. Kan je die gewoon door elkaar heen gebruiken??

**Comment by joeribekker** [comment]
> @joeribekker goed om te weten dat we op meerdere zaaktypes kunnen zoeken. Als ik de API bekijk dan zie ik dat dat _zoek endpoint queryparameters en een request body heeft. En sommige kan je als Query parameter EN als request body meegeven. Kan je die gewoon door elkaar heen gebruiken??

I think so. The reason they are both there is because the URL length is limited. I would always use the body (probably makes your code easier as well)
