### ISSUE TITLE
As an admin of Open Zaak I'd like to assign authorizations on a per-catalogus basis

### ISSUE THREAD

**Issue by alextreme** [open-zaak/open-zaak#1661]
### Thema / Theme

Admin

### Omschrijving / Description

Taiga DH 513

Currently you can only assign Zaken API (and Documenten+Besluiten API) authorizations on a global basis and a per-zaaktype basis. This becomes quite cumbersome when you have a lot of zaaktypes, especially because new versions of zaaktypes need to be added explicitly to every application.

It would be more manageable to manage application authorizations for the Zaken API on a per-catalogus level, where an application automatically gets access to all zaaktypes that are created in a specific catalogus. Currently the only alternative is selecting 'Alle huidige and toekomstige zaaktypen' which is too broad.

This request most likely has impact on the Authorizations API, however in my eyes can also be done solely via the admin.

**Comment by joeribekker** [comment]
Refinement: Preferably, we don't change the API specification. We can add a model that links Application to Catalogs, and resolve this to relevant zaaktypes, documenttypes and besluittypes when the API is consulted.

**Comment by JanBrek** [comment]
Additional feature request (Maybe needs to be moved into another ticket?)
Also allow notification API to be set per catalogus. So set your abbonement to a catalogus instead of using zaaktype as filtering.
...Id imagine this to be a much bigger change, if at all implemented, due to it being cross-application. But still asking the question to see if this is at all something to integrate into the solution or not.
One possible solution would be that the zaak kanaal also will include catalogi name/number/whatever in the notification so that it can be used as a filter.

**Comment by joeribekker** [comment]
@JanBrek Sounds like a new ticket :)

**Comment by JanBrek** [comment]
Created https://github.com/open-zaak/open-notificaties/issues/156 :)

**Comment by PeterVanBragt** [comment]
Wait for alignment with Peter Arkesteijn regarding costs (Peter A is returning from leave at the end of June)

**Comment by PeterVanBragt** [comment]
Peter A will discuss prio with Geert Jan Pes

**Comment by PeterVanBragt** [comment]
GJP doesn't recognize this issue. Jan Brekelmans will contact him to explain so the right prio can be set.

**Comment by joeribekker** [comment]
@PeterVanBragt from a technical perspective this is really needed AND it's currently blocking authorization exports that helps with the OTAP-issues (copying config from environment A to B).

**Comment by PeterVanBragt** [comment]
Peter Arkesteijn doubts if this should have the highest prio now. There might be other issues that will be more valuable to fix. He will take this up with Geert Jan and come back on this.
