### ISSUE TITLE
Handling notifications for Bulk-import Documents

### ISSUE THREAD

**Issue by joeribekker** [open-zaak/open-zaak#1687]
Not sure why this ticket appeared but if we currently sent out notifications on bulk import... this should not happen :)

**Comment by SonnyBA** [comment]
@annashamray Unless we want to discuss this any further, I think we can close this ticket (as no notifications are being sent currently).

**Comment by annashamray** [comment]
I think we need to discuss it. We don't sent any notifications now, but should we do it? What if someone is subscribed to notifications of these informatieobjecttypen and now they will have inconsistent data

**Comment by joeribekker** [comment]
Refinement: Anna made a point that this might be desired and people rely on this. It was decided that this endpoint is experimental and the migration use case where this endpoint was created for, can lead to alot of notifications and this was not specified in the feature request.

However, we need to add this warning in the API specification documentation.
