### ISSUE TITLE
The ZGW OpenAPI specifications contain 'min_length' and 'max_length' properties which are prohibited according to the schema

### ISSUE THREAD

**Issue by edgarvonk** [open-zaak/open-zaak#1699]
### Product versie / Product version

1.13.0

### Omschrijf het probleem / Describe the bug

The ZGW OpenAPI specifications contain `min_length` and `max_length` properties which are prohibited according to the schema. E.g. https://github.com/open-zaak/open-zaak/blob/main/src/openzaak/components/zaken/openapi.yaml but this also goes for the other `openapi.yaml` specs.

When we try to generate Java stub client code from such a spec using https://github.com/OpenAPITools/openapi-generator we get schema validation errors such as:

`Schema validation: Property 'min_length' is not allowed`

I think these properties should be renamed to `minLength` and `maxLength` instead.

### Stappen om te reproduceren / Steps to reproduce

1. Download an openapi.yaml file. E.g. https://github.com/open-zaak/open-zaak/blob/main/src/openzaak/components/zaken/openapi.yaml
2. Use https://github.com/OpenAPITools/openapi-generator to generate Java client code from this spec.
3. Schema validation errors occur such as: `Schema validation: Property 'min_length' is not allowed`

### Verwacht gedrag / Expected behavior

No schema validation errors. Older versions of OpenZaak did not have this issue. We are upgrading from 1.10.3 to 1.13.0. Not sure in which version this issue was introduced.

**Comment by joeribekker** [comment]
@annashamray Quick check and I noticed we arent running spec validation (anymore). I see no postman checks, no oas-lint and no sdk generation in Github actions, like done here: https://github.com/maykinmedia/referentielijsten/tree/master/.github/workflows

This should be added specifically to prevent these issues (to all registrations).

**Comment by annashamray** [comment]
@joeribekker  we removed postman checks since they were not updated. We kept updating them ourselves for a while but then dropped. We 've never has schema validation checks for Open Zaak (unlike Objects API), I agree that it's a good think to add them!

**Comment by joeribekker** [comment]
@annashamray please cover all components

**Comment by annashamray** [comment]
@joeribekker I've created an issue for it with tasks for all APIs: https://github.com/open-zaak/open-zaak/issues/1708
