### ISSUE TITLE
AttributeError /zaken/api/v{version}/zaken/{uuid} 'NoneType' object has no attribute 'uuid'

### ISSUE THREAD

**Issue by SilviaAmAm** [open-zaak/open-zaak#1707]
### Product versie / Product version

1.11.0

### Omschrijf het probleem / Describe the bug

Sentry maykin-media/issues/363194

```
AttributeError: 'NoneType' object has no attribute 'uuid'
  File "rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "rest_framework/mixins.py", line 82, in partial_update
    return self.update(request, *args, **kwargs)
  File "notifications_api_common/viewsets.py", line 195, in update
    with conditional_atomic(self.notifications_wrap_in_atomic_block)():
  File "django/db/transaction.py", line 290, in __exit__
    connection.set_autocommit(True)
  File "django/db/backends/base/base.py", line 420, in set_autocommit
    self.run_and_clear_commit_hooks()
  File "django/db/backends/base/base.py", line 653, in run_and_clear_commit_hooks
    func()
  File "vng_api_common/caching/etags.py", line 135, in __call__
    return self.callback()
  File "vng_api_common/caching/etags.py", line 180, in calculate_new_value
    self.instance.calculate_etag_value()
  File "vng_api_common/caching/models.py", line 35, in calculate_etag_value
    self._etag = calculate_etag(self)
  File "vng_api_common/caching/etags.py", line 92, in calculate_etag
    rendered = renderer.render(serializer.data, "application/json")
  File "rest_framework/serializers.py", line 548, in data
    ret = super().data
  File "rest_framework/serializers.py", line 246, in data
    self._data = self.to_representation(self.instance)
  File "rest_framework/serializers.py", line 515, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "openzaak/components/documenten/api/fields.py", line 32, in to_representation
    kwargs={"uuid": value.uuid},
```

### Stappen om te reproduceren / Steps to reproduce

from the shell of a project talking to our test env open-zaak:

```python
from zgw_consumers.models import Service
from zgw_consumers.constants import APITypes
from zgw_consumers.client import build_client

service = Service.objects.get(api_type=APITypes.zrc)
zrc_client = build_client(service)
with zrc_client:
     response = zrc_client.patch("zaken/d5aca3e4-14f9-4345-8c17-f03668b32a37", headers={"Accept-Crs": "EPSG:4326","Content-Crs": "EPSG:4326",}, json={"archiefactiedatum": "2026-01-01"})
```

### Verwacht gedrag / Expected behavior

Either a 400 or success

**Comment by SilviaAmAm** [comment]
For some reason here `latest_version` is None: https://github.com/open-zaak/open-zaak/blob/c436252c0bda324c95600e5988f2181dac1f0e76/src/openzaak/components/documenten/api/fields.py#L32

**Comment by Coperh** [comment]
The cause of this is that you can create en empty `enkelvoudiginformatieobjectcanonical` in the admin by leaving all fields blank and then linking this empty to a `BesluitInformatieObject` or `ZaakInformatieObject`

**Comment by Coperh** [comment]
Quick fix is to go to `/admin/documenten/enkelvoudiginformatieobjectcanonical/` and delete everything that says `None`

**Comment by Coperh** [comment]
@annashamray thinking about this a bit more, how do you create these via the admin? 
`ZaakInformatieObject` needs a `EnkelvoudigInformatieObjectCanonical` which needs a `EnkelvoudigInformatieObject`

Do we remove `EnkelvoudigInformatieObject` admin and make it so you must create through the canonical admin?

Do we do it like the API which does not have a `EnkelvoudigInformatieObjectCanonical` endpoint? In this situation, how do you link a `ZaakInformatieObject` to it?

There is also the question of where else it could be created.

I honestly have no idea what to do.

**Comment by annashamray** [comment]
@Coperh Let's keep it simple
We don't expose `EnkelvoudigInformatieObjectCanonical` resource in the API. So let's focus on the admin.
I think the easiest way would be just to require to fill at lease one document version in the `EnkelvoudigInformatieObjectCanonical` admin page
It will help to remove this possibility to have a document without uuid

**Comment by joeribekker** [comment]
Please use Dimpact - Open Archiefbeheer for hours.
