### ISSUE TITLE
AutorisatieForm in admin does not show selected informatieobjecttypen

### ISSUE THREAD

**Issue by stevenbal** [open-zaak/open-zaak#1718]
### Product versie / Product version

latest / 6bc94b31168af217c3e9b4024c9ac3790e04738d

### Omschrijf het probleem / Describe the bug

In the `AutorisatieForm`, selected informatieobjecttypes do not show after saving them

### Stappen om te reproduceren / Steps to reproduce

If I save an Autorisatie via the admin with the following settings (I'm not sure if the actual component/scopes matter, but this is how I ran into it locally):

component: Documenten API
scopes: notificaties.consumeren
extra params, select an Informatieobjecttype manually
choose any confidentiality

And then navigate back to the AutorisatiesForm, I see that the option to manually select a type is select, but no type is checked in the selectboxes below it, nor is it part of external types.

### Verwacht gedrag / Expected behavior

The selected type should show in the form

I tested this locally and on the testenv with version 1.11.0 and I could not reproduce it there, so it has to be introduced somewhere between 1.11.0 and `6bc94b31168af217c3e9b4024c9ac3790e04738d`

**Comment by annashamray** [comment]
Good news: after the Autorisatie form was refactored and Catalogus autorisatie was introduces this problem is no longer present. 
Bad news: when I tested it another bug showed up: if you add an autorisatie with several iotypen and without catalogus autorisatie the form would crush. So I'll fix this issue here
