### ISSUE TITLE
Host the Traefik dashboard on its own service/subdomain

### ISSUE THREAD

**Issue by sergei-maertens** [open-zaak/open-zaak#172]
From https://github.com/open-zaak/open-zaak/pull/138#discussion_r340158333

We need to configure this differently using Traefik services (internal) and Kubernetes middlewares to apply an IP-whitelist + HTTP basic auth, before we can remove the `--insecure` option.

**Comment by Hugo-ter-Doest** [comment]
@joeribekker kan dit niet prioriteren? Geef jij prio aan?

**Comment by joeribekker** [comment]
Standaard  kunnen we Traefik dashboard simpelweg uitzetten in onze templates zodat er in ieder geval geen security risico out of the box in zit. Dit is vooral handig voor debugging, wat je eventueel als sysadmin wel kan aanzetten.

**Comment by sergei-maertens** [comment]
Not going to happen - this is too much cluster operations rather than deployment of Open Zaak itself.

It's up to the infrastructure provider to provide an ingress and configure it in a secure way. Open Zaak taps into this via the ingress resources.
