### ISSUE TITLE
Celery healthcheck

### ISSUE THREAD

**Issue by annashamray** [open-zaak/open-zaak#1727]
### Thema / Theme

Other

### Omschrijving / Description

There can be issues with celery workers coming up before redis and DB when k8s cluster has been restarted. 
So let's add healthchecks to celery to prevent it

Add celery healthcheck:
* [x] Open Zaak https://github.com/open-zaak/open-zaak/pull/1735
* [x] Open Notificaties https://github.com/open-zaak/open-notificaties/pull/177
* [x] Objects API - https://github.com/maykinmedia/objects-api/pull/427
* [ ] ~~Objecttypes API~~ does not have celery
* [ ] ~~Open Klant~~ does have celery, but seems to be unused?

Release it
* [ ] Open Zaak
* [ ] Open Notificaties
* [x] Objects API
* [ ] ~~Objecttypes API~~
* [ ] ~~Open Klant~~

**Comment by stevenbal** [comment]
@annashamray I checked, Objecttypes does not have celery (only as part of OAF dependencies, but it's not configured) and Open Klant does have Celery configured, but I don't think it actually needs Celery, since notifications aren't supported.

@bart-maykin do you know if Celery is still used in Open Klant?

**Comment by annashamray** [comment]
@stevenbal 
I can confirm that Objecttypes doesn't use celery and it doesn't sent notifications. 
I'm pretty sure that Referentielijst API also doesn't use celery. Should we make it an optional dependency? Or is it too much work?

**Comment by stevenbal** [comment]
@annashamray I'm not sure, it's explicitly installed, but it's also installed by `notifications-api-common`, which is not explicitly specified but installed by `commonground-api-common`, so it would probably be a fair bit of work + releasing just to remove celery from some projects :grimacing:
