### ISSUE TITLE
500 when deleting ZIO

### ISSUE THREAD

**Issue by SilviaAmAm** [open-zaak/open-zaak#1729]
### Product versie / Product version

1.11.0

### Omschrijf het probleem / Describe the bug

When making a DELETE request to `/zaken/api/v1/zaakinformatieobjecten/08315412-77eb-4c86-a835-47873c55cb76` on our test environment, we get a 500 error. 

In our sentry: maykin-media/issues/365861

### Stappen om te reproduceren / Steps to reproduce

DELETE request to `/zaken/api/v1/zaakinformatieobjecten/08315412-77eb-4c86-a835-47873c55cb76` (on our test env, see sentry for full url).

### Verwacht gedrag / Expected behavior

Either a 204 or a 400 response

**Comment by SonnyBA** [comment]
Relevant issue hiervoor vanuit de test omgeving vanuit open-zaak: maykin-media/issues/365860/?project=149&query=is%3Aunresolved&statsPeriod=14d

Het blijkt dat de test omgeving van open-zaak een request probeert te doen naar een omgeving toe die gebruikt maakt van een self-signed certifcate en hierdoor faalt. Zie de breadcrumbs in eerder genoemd sentry issue voor nadere info.

**Comment by joeribekker** [comment]
Even met Sven over gehad. Dit komt omdat sommige zaken op test.oz.nl zijn gekoppeld aan documenten bij Utrecht, waar we niet (meer) bij kunnen. Vandaar fouten. Mijn advies: Zet een eigen oz neer met eigen test data.

Deze error ligt buiten scope van Open Archiefbeheer, en wellicht kan oz een betere foutmelding hiervoor geven maar eehhhh, stakeholder nodig
