### ISSUE TITLE
Add selectielijstklasse and archief datum to test data generation.

### ISSUE THREAD

**Issue by svenvandescheur** [open-zaak/open-zaak#1732]
### Thema / Theme

Zaken API

### Omschrijving / Description

The (generate_data?) management command creates test data but seems to result in a set of zaken that lacks a (valid) selectielijstklasse and an archiefdatum. 

### Toegevoegde waarde / Added value

This allows more realistic test data to be generated benefitting the development of OAB.

**Comment by alextreme** [comment]
Is about https://github.com/open-zaak/open-zaak/blob/main/src/openzaak/management/commands/generate_data.py 

@annashamray can be picked up to help out @svenvandescheur and the OAB team
