### ISSUE TITLE
Deleting an Application via the admin via a bulk-delete doesn't delete the underlying Autorisatie

### ISSUE THREAD

**Issue by alextreme** [open-zaak/open-zaak#1741]
### Product versie / Product version

1.12.3 and 1.11 (test.openzaak.nl)

### Omschrijf het probleem / Describe the bug

Taiga Utrecht 264

Having trailing entities when deleting an Application was an issue earlier in #1515 , this issue is new but related.

When deleting an indivudal Application things go well, however when you do a bulk-delete with the Application the Autorisatie (or JWTSecret?) object remains. Even though the Application credentials can no longer be used, the client-id's of the Application's Autorisatie can't be reused.

This issue can be easily reproduced by doing a bulk-delete of an Application and then attempting to use the deleted client-id again in a new Application:

![image](https://github.com/user-attachments/assets/f5b14cf4-9124-4451-a188-9d8cfb939a25)

![image](https://github.com/user-attachments/assets/35f5d4a0-3d2b-4257-8a24-3c1095ae5f1a)

**Comment by joeribekker** [comment]
Refinement: SInce @stevenbal refactored this, I want to doublecheck with him once he's back.

**Comment by joeribekker** [comment]
@annashamray can you doublecheck if this works correctly in the latest version?
