### ISSUE TITLE
Replace "nld" in helptext for "taal" with the proper value

### ISSUE THREAD

**Issue by joeribekker** [open-zaak/open-zaak#1755]
### Thema / Theme

Zaken API

### Omschrijving / Description

"nld" is the wrong value according to the ISO spec.

### Toegevoegde waarde / Added value

Small change, big impact

**Comment by SonnyBA** [comment]
Although the ticket mentions the Zaken API, I can't find any resource with the field named `taal`. A very similar fix was made though through https://github.com/open-zaak/open-zaak/commit/3fe3dea1432fddb19b0e7e541a8f4060d6401d70. Is the problem in this issue already fixed?
