### ISSUE TITLE
Updating an application's authorizations via the admin leads to duplicate authorizations

### ISSUE THREAD

**Issue by alextreme** [open-zaak/open-zaak#1767]
### Product versie / Product version

1.13

### Omschrijf het probleem / Describe the bug

Taiga DH 588 
Unsure if this situation is solved in 1.14 or not, I wasn't able to reproduce the issue but I remember having a similar non-reproducable issue with authorizations earlier. Screenshots showing the steps taken have been added to Taiga

**Comment by annashamray** [comment]
I've checked it locally with Open Zaak 1.14 both when selecting catalogus and manual zaaktypen and this error hasn't been reproduced
