### ISSUE TITLE
zaaktype__not_in filter on zaak search

### ISSUE THREAD

**Issue by JanBrek** [open-zaak/open-zaak#1783]
### Thema / Theme

Zaken API

### Omschrijving / Description

In some cases we want to get all zaken, but not of a few specific types.
DH Usecase:
- A party started registering zaken in OpenZaak, great, but they did not expect them to be visible in our customer portal
- Now we want to exclude zaken from those zaaktypes from our searches so we can still query properly instead of filtering them out client side

### Toegevoegde waarde / Added value

Exceptions in queries can be made on prod, without weird client side magic

### Aanvullende opmerkingen / Additional context

Maybe zaken__out, or maybe a negative mark on the search like  `zaaktype__in ["!my.zaak.nl/UUID1", "!my.zaak.nl/UUID2"]` though this might be overkill as a (positive) zaaktype__in already excludes the rest.

**Comment by joeribekker** [comment]
Refinement: We're calling it `__not_in` and it should be in both the `zoek` and the `list` endpoint. We throw a validation error if you specify the same zaaktype in both `zaaktype__in` and in `zaaktype__not_in`

Estimate: 2 days

@PeterVanBragt ready for approval.

**Comment by PeterVanBragt** [comment]
Approved!
