### ISSUE TITLE
As a maintainer I want to choose procestypes of the Selectielijst from a combobox

### ISSUE THREAD

**Issue by Hugo-ter-Doest** [open-zaak/open-zaak#185]
... so I don't have to type free text. This prevents errors.

This is the `Zaaktype > Selectielijst procestype` URL.

**Tasks**

- [ ] ~Add configuration for the Selectielijst API in OpenZaak possible via the admin~
- [x] Change the URL field to a dropdown or similar to choose one of the processtypes from this API.

**Comment by sergei-maertens** [comment]
> Add configuration for the Selectielijst API in OpenZaak possible via the admin

@joeribekker it's currently a Django setting, I'm not sure this is part of the MVP? There is currently only one environment that provides this API.

**Comment by joeribekker** [comment]
Ok I agree. Let's move it to a different user story.
