### ISSUE TITLE
As a maintainer I want to choose resultaattypes that belong to a procestype (Selectielijst) from a combobox

### ISSUE THREAD

**Issue by Hugo-ter-Doest** [open-zaak/open-zaak#186]
... so I don't enter a resultaattype that does not belong to the chosen procestype and don't make typing errors.

**Comment by sergei-maertens** [comment]
See also #176

**Comment by sergei-maertens** [comment]
Fixed in #209 

If it cannot be pre-filtered, validation will catch the lack of `Zaaktype.proces_type` so it's not possible to make mistakes anymore.
