### ISSUE TITLE
As a municipality I want to give a relevant name to a catalogue

### ISSUE THREAD

**Issue by Hugo-ter-Doest** [open-zaak/open-zaak#187]
... so I can easily see what a catalogue is meant for, i.e. the kind of zaaktypes it contains.

Domein and Identificatie are not enough.

Maybe this should be solved in the standard.

**Description**
Describe the user story in more detail.

**Comment by Hugo-ter-Doest** [comment]
First name of catalogue has to be added to the standard. See https://github.com/VNG-Realisatie/gemma-zaken/issues/1449

**Comment by joeribekker** [comment]
> First name of catalogue has to be added to the standard. See https://github.com/VNG-Realisatie/gemma-zaken/issues/1449

Yes, but not implemented yet and we need it at the very least from a UI perspective.

**Comment by joeribekker** [comment]
Done in #289
