### ISSUE TITLE
The Identificatie field for zaaktype has wrong format

### ISSUE THREAD

**Issue by Hugo-ter-Doest** [open-zaak/open-zaak#188]
In the admin, the "identificatie" field shows up/down arrows.

2 questions/fixes needed:

- Should it be an integer?
- Can we remove all these up/down arrows everywhere? It's more confusing than helpfull.

**Comment by sergei-maertens** [comment]
We established that we'd change the identification in the API spec as well - this must become a `CharField` and the matching patch needs to be applied to gemma-zaaktypecatalogus.
