### ISSUE TITLE
As a maintainer I want to enter durations with number of days only

### ISSUE THREAD

**Issue by Hugo-ter-Doest** [open-zaak/open-zaak#191]
... so I don't have to enter hours as well.

**Implementation hints**
We can override the admin field to use an integer field and convert it on save/load.

**Comment by sergei-maertens** [comment]
It should be clear that this number-of-days includes non-working days (Saturday/Sunday).

**Comment by sergei-maertens** [comment]
@joeribekker not sure if this is entirely the way to go. Probably you want to combine it in a bunch of inputs:

```
years: 0     months: 6    days: 0
```

If you convert it to days again, you lose the precision of specifying years.

**Comment by joeribekker** [comment]
The format is currently `DD 00:00` so where's the precision?

**Comment by sergei-maertens** [comment]
hrm, I'm aware of some places that still use Django's durationfield instead of the 3rd party lib, so that might be it? or the widget is not adapted for it.

But I'll make it pretty :-)
