### ISSUE TITLE
Button "Add another" does not work anymore after removing the last entry

### ISSUE THREAD

**Issue by Hugo-ter-Doest** [open-zaak/open-zaak#193]
When editing a zaaktype: in places where you can add multiple entries (for instance "trefwoorden"): when you remove the last entry button "Add another" does not add a new entry.

**Comment by sergei-maertens** [comment]
Fix in https://github.com/gradam/django-better-admin-arrayfield/commit/dbd57cb22f5fef16828626bbf9fe38cdbdfffc06

-> update django-better-admin-arrayfield to 1.0.4

**Comment by sergei-maertens** [comment]
Fixed in #233
