### ISSUE TITLE
Adding a statustype to a zaaktype results opens a general details page for editing statustype

### ISSUE THREAD

**Issue by Hugo-ter-Doest** [open-zaak/open-zaak#198]
**Describe the bug**
When clicking "Add statustype" on a Zaaktype detail page, the Zaaktype information is not saved and the user is redirect to add a statustype.

**To Reproduce**
1. Create new Zaaktype
2. Add some infor
3. Click "Add statustype"
4. the Zaaktype information is lost

**Expected behavior**
Information should not be lost when adding related information.

**Implementation hints**
We can do either of 4 things:

1. Only show "Add/Change" links when all information on the current page is saved ie. not dirty.
2. Make full blown inlines from these things (and perhaps prettify with expanded/collapsed "rows" per related object)
3. Clicking a link that leaves the page wil auto save the page (or cancel redirect when validation errors).
4. Clicking a link that laves the page will show a popup: "are you sure?", when the page is dirty.

Let's discuss briefly and choose one!

**Comment by sergei-maertens** [comment]
Implemented by:

* removing the link if the main object (zaaktype) isn't saved to database yet. you get a message stating this
* modified the link so that it opens in a new tab, prevents you from loading a new page and discarding unsaved data
