### ISSUE TITLE
As maintainer I want the see the Selectielijst data

### ISSUE THREAD

**Issue by Hugo-ter-Doest** [open-zaak/open-zaak#203]
...so I can determine what should be filled in.

This screen should roughly be split in 2:

![image](https://user-images.githubusercontent.com/96970/68580386-8f985a80-0476-11ea-856f-77b3fd8d4c90.png)

1. The right side showing what is there now (just admin fields)
2. The left side should show the values based on the selectielijst.

If it doesn't line up really nice, just show the information from the selectielijst in the left side (so not directly matched in field rows).

**Comment by sergei-maertens** [comment]
See also #176

**Comment by joeribekker** [comment]
We made changes so it should be more clear in #239.
