### ISSUE TITLE
As a maintainer I want to view logging files in the BeheerPortaal of GemeenteZaak

### ISSUE THREAD

**Issue by Hugo-ter-Doest** [open-zaak/open-zaak#207]
... so I can view these loggings without asking the hosting.

**Description**
Describe the user story in more detail.

**Comment by joeribekker** [comment]
Wat willen mensen precies zien en waarom?

**Comment by sergei-maertens** [comment]
Also a complex matter - if running on Kubernetes, logging is centralized in the cluster itself and this is not easily available per se.

**Comment by sergei-maertens** [comment]
Closing because of lack of input
