### ISSUE TITLE
As maintainer I want to be able to add an 'EigenschapSpecificatieObject' in Date-format

### ISSUE THREAD

**Issue by MichelleDautzenberg** [open-zaak/open-zaak#211]
When adding an 'Eigenschap' I have to add an 'EigenschapSpecificatieObject' (though this seems optional). When I choose the format 'Datum', it doesn't work. 

![image](https://user-images.githubusercontent.com/48316239/68474392-8b293300-0225-11ea-91ef-e19c012ff082.png)

**Comment by sergei-maertens** [comment]
Fixed in #209
