### ISSUE TITLE
As developer, I want a generic solution prototype for using local and external API URLs

### ISSUE THREAD

**Issue by joeribekker** [open-zaak/open-zaak#22]
... so other developers can use this strategy for all URL-fields.

**Description**
Before starting with #5 and #6 we need a basic strategy to store these URLs/FKs, also taking the URL fragmentation into account: https://zaakgerichtwerken.vng.cloud/themas/achtergronddocumentatie/versies-en-migraties

**Comment by sergei-maertens** [comment]
https://pypi.org/project/django-loose-fk/ is the first product of this

**Comment by joeribekker** [comment]
@sergei-maertens Do you consider this task as Implemented then?

**Comment by sergei-maertens** [comment]
Yeah, prototyping/spike is definitely done. We'll run into more issues for sure, but this can be closed.
