### ISSUE TITLE
Creating ZaakType in the admin without trefwoorden and/or verantwoordingsrelatie gives internal server error

### ISSUE THREAD

**Issue by stevenbal** [open-zaak/open-zaak#237]
**Describe the bug**
In the `ZaakType` admin, the fields `trefwoorden` and `verantwoordingsrelatie` are not marked as required, but when trying to create a `ZaakType` without either of these two fields, the page crashes, because the fields have not null constraints:

```html
IntegrityError at /admin/catalogi/zaaktype/add/

null value in column "trefwoorden" violates not-null constraint
DETAIL:  Failing row contains (180, 2019-11-18, null, t, 612c8cd0-bdaf-43c1-92c3-95845443ea93, 1, dasd, , openbaar, sadasd, sadasd, , extern, sadasd, sdadas, asda, 10 days, null, f, f, null, null, f, , null, 2019-11-18, {https://ref.tst.vng.cloud/standaard/}, https://referentielijsten-api.vng.cloud/api/v1/procestypen/e1b73..., s, , 2).
```

**Expected behavior**
If these fields are indeed required, they should also be marked as required in the admin, raising a ValidationError when they are not filled in

**Comment by sergei-maertens** [comment]
Was fixed via https://github.com/open-zaak/open-zaak/commit/5e26ca6c614431ffcb4dd26456ac1a92edda7c18 already
