### ISSUE TITLE
Plural forms for typen in Catalogi should end with `n`

### ISSUE THREAD

**Issue by stevenbal** [open-zaak/open-zaak#238]
**Describe the bug**
Currently the field on the `Besluittype` which registers the m2m relation with `Zaaktype` is called `zaaktypes`, but the plural form for all typen from the Catalogi API should end with `n` rather than `s` (e.g. `zaaktypes` -> `zaaktypen`, `besluittypes` -> `besluittypen` etc.)

**Comment by joeribekker** [comment]
@stevenbal Klopt, mag doorgevoerd worden conform 1.0.0 spec:

https://github.com/VNG-Realisatie/gemma-zaken/blob/master/api-specificatie/ztc/1.0.x/openapi.yaml#L7827
