### ISSUE TITLE
Add an architecture image to the application architecture documentation.

### ISSUE THREAD

**Issue by sergei-maertens** [open-zaak/open-zaak#244]
From https://github.com/open-zaak/open-zaak/pull/223/files#r344769043

**Comment by Hugo-ter-Doest** [comment]
@sergei-maertens zoiets?
![image](https://user-images.githubusercontent.com/7829083/71898817-8536cc00-315a-11ea-8ccb-5d8dceb79f1c.png)

**Comment by joeribekker** [comment]
Done here: https://github.com/open-zaak/open-zaak/pull/458
