### ISSUE TITLE
As developer, I want to create an audit entry in the API if a change was made in the admin inlines...

### ISSUE THREAD

**Issue by sergei-maertens** [open-zaak/open-zaak#245]
so changes cannot be made without leaving an audit trail.

**Description**

This is the sequel to #169 - during [code review](https://github.com/open-zaak/open-zaak/pull/236#pullrequestreview-319768617) it became apparent that `Zaak.status` inlines etc. aren't caught by the audit trail integration.

The implementation looks solid and it should be fairly straight-forward to add it for inlines.

**Comment by annashamray** [comment]
Implemented in bea5f97b24eb5b493f83bfb94cb8c1f0cd605b93
