### ISSUE TITLE
As municipality I want to keep the existing UUIDs when exporting/importing catalogs

### ISSUE THREAD

**Issue by joeribekker** [open-zaak/open-zaak#249]
... so I can migrate to a different supplier and/or only need to change hosts in client configurations.

**Description**
The export/import done in #189 has excluded the case to keep UUIDs. This US extends on that.

**Comment by joeribekker** [comment]
@stevenbal What do we currently support? With or without existing UUIDs?

**Comment by stevenbal** [comment]
@joeribekker without existing UUIDs
