### ISSUE TITLE
Als functioneel beheerder wil ik per status binnen een zaak aan kunnen geven of deze getoond moet/mag worden richting burger en/of medewerker 

### ISSUE THREAD

**Issue by FrankHarbers** [open-zaak/open-zaak#25]
zodat ik bijvoorbeeld voor interne afhandeling meer statussen kan gebruiken dan de statussen die ik wil tonen aan een burger.
Voor burgers is misschien iets anders een mijlpaal dan voor een buurtteam in dezelfde keten. Misschien in Statustype configureren?

**Comment by Hugo-ter-Doest** [comment]
Ik denk dat dit in de standaard moet worden opgelost met een attribuut dat dit uitdrukt, en niet zozeer thuishoort in de bouw van de OpenZaak registraties.

**Comment by joeribekker** [comment]
@FrankHarbers Wellicht voorziet `STATUSTYPE.informeren` in je behoefte?

Zie: https://catalogi-api.vng.cloud/api/v1/schema/#operation/statustype_read

Zo niet, dan moet dit inderdaad toegevoegd worden aan de standaard of op applicatie niveau worden vastgelegd.
