### ISSUE TITLE
As municipality I want to use NLX logging feature

### ISSUE THREAD

**Issue by joeribekker** [open-zaak/open-zaak#279]
... so I can log requests.

**Description**
Currently disabled but probably needed for AVG.

See: https://github.com/open-zaak/open-zaak/pull/273#discussion_r351215623

**Comment by Hugo-ter-Doest** [comment]
Gaat om configuratie van NLX inway, en is buiten scope van OpenZaak

**Comment by sergei-maertens** [comment]
FYI - as part of the [Utrecht Proeftuin](https://github.com/GemeenteUtrecht/ZGW/issues/347) there is existing infrastructure code to configure NLX completely, including logging database
