### ISSUE TITLE
Als functioneel beheerder wil ik per objectsoort (waarop een gebruiker zoekt) willen kunnen instellen wat de authentieke bron is van die gegevens

### ISSUE THREAD

**Issue by FrankHarbers** [open-zaak/open-zaak#29]
zodat [vul aan].
Uitgangspunt is dat er één bron is. Behalve bij BRP waarbij allereerst in de lokale BRP wordt gezocht en daarna in de landelijke GBA-V.

**Description**
Describe the user story in more detail.

**Comment by joeribekker** [comment]
@FrankHarbers Kan je deze verder toelichten eventueel met een concreet voorbeeld?

1. Heb je het over de API of de beheer interface?
2. En wat bedoel je met "objectsoort"?
3. Hoe zou je de authentieke bron willen "instellen"?

**Comment by Hugo-ter-Doest** [comment]
De authentieke bron van een object aangewezen door de URI waarmee je ernaar verwijst.
