### ISSUE TITLE
Deleting Zaak with existing Zaakbesluit gives internal server error

### ISSUE THREAD

**Issue by stevenbal** [open-zaak/open-zaak#290]
**Describe the bug**
If I try to delete a `Zaak` that has one or more  `Besluiten` linked to it, I get an internal server error, because the foreign key is protected: 
```json
ProtectedError at /zaken/api/v1/zaken/d364d85f-ce14-4d4b-9609-ef55db4e39a8
("Cannot delete some instances of model 'Zaak' because they are referenced through a protected foreign key: 'Besluit._zaak'", <QuerySet [<Besluit: 000000000 - BESLUIT-2019-0000000002>, <Besluit: 000000000 - BESLUIT-2019-0000000001>]>)

Request Method: DELETE
Request URL: http://localhost:8000/zaken/api/v1/zaken/d364d85f-ce14-4d4b-9609-ef55db4e39a8
Django Version: 2.2.4
```

**To Reproduce**
1. Create a `Zaak`
2. Add a `Besluit` to the `Zaak`
3. Try to delete the `Zaak`

**Expected behavior**
I would expect one of the following two:
1) The API returns a 400 stating that there are related `Besluiten` that must be deleted first
2) The deletion cascades to `Besluiten`

@joeribekker @sergei-maertens what do you think should happen here?

**Comment by joeribekker** [comment]
@stevenbal the first option

> The API returns a 400 stating that there are related Besluiten that must be deleted first

**Comment by stevenbal** [comment]
Okay, I'm not sure if this is currently the case in the reference implementation, so I will check that and create an issue in gemma-zaken if needed.

**Comment by annashamray** [comment]
while fixing this error I've realized that `ZaakBesluit` resource doesn't support external urls. The issue for this - https://github.com/open-zaak/open-zaak/issues/296
