### ISSUE TITLE
As stakeholder I want to rename OpenZaak to GemeenteZaak

### ISSUE THREAD

**Issue by joeribekker** [open-zaak/open-zaak#294]
... so I there is no reference anymore to the "old" name.

**Description**
The original project name was OpenZaak but was later renamed to GemeenteZaak. References should be updated everywhere.

- [ ] Admin UI
- [ ] Documentation
- [ ] Code
- [ ] Configuration files

**Comment by Hugo-ter-Doest** [comment]
OpenZaak will be used.

**Comment by joeribekker** [comment]
Discussed that we're going to use Open Zaak.
