### ISSUE TITLE
De referentieimplementatie laat op dit moment toe dat nieuwe documenten aan een gearchiveerde zaak gekoppeld worden

### ISSUE THREAD

**Issue by sergei-maertens** [open-zaak/open-zaak#298]
# Bug

Na het archiveren van een zaak is deze in principe immutable, het zou dus door (reguliere) users niet mogelijk mogen zijn om nieuwe documenten te relateren aan deze zaken.

Check:
- [x] Documenten koppelen
- [x] Nieuwe statussen zetten (mag mits scope heropenen)
- [x] Zaakobjecten
- [x] Zaakeigenschappen
- [x] ZaakInformatieObjecten
- [x] Klantcontacten
- [x] Rollen
- [x] Resultaten
- [x] ZaakBesluiten

---

Collection of what the standard describes:

From [zrc-007](https://github.com/VNG-Realisatie/gemma-zaken/blob/master/docs/_content/standaard/zaken/index.md#afsluiten-zaak-zrc-007):

> Als een Zaak een eindstatus heeft dan is de zaak afgesloten en mogen gegevens van de zaak niet meer aangepast worden (behalve om redenen van correctie). Dit MOET beveiligd worden met de scope zds.scopes.zaken.geforceerd-bijwerken.

From [zrc-021](https://github.com/VNG-Realisatie/gemma-zaken/blob/master/docs/_content/standaard/zaken/index.md#zrc-021):

> Het resultaat van een zaak is bepalend voor het archiefregime. Bij het afsluiten van een zaak MOETEN de attributen Zaak.archiefnominatie en Zaak.archiefactiedatum bepaald worden...

-> "Archivering" vindt plaats bij het afsluiten van de zaak

**Comment by joeribekker** [comment]
Graag ook porten naar VNG ref impl.
