### ISSUE TITLE
Als functioneel beheerder wil ik per status binnen een zaak aan kunnen geven of deze getoond moet/mag worden richting burger en/of medewerker 

### ISSUE THREAD

**Issue by FrankHarbers** [open-zaak/open-zaak#31]
zodat ik bijvoorbeeld voor interne afhandeling meer statussen kan gebruiken dan de statussen die ik wil tonen aan een burger.
Voor burgers is misschien iets anders een mijlpaal dan voor een buurtteam in dezelfde keten. Misschien in Statustype configureren?

**Description**
Describe the user story in more detail.

**Comment by joeribekker** [comment]
Zelfde als #25
