### ISSUE TITLE
As a developer, I want to verify that permission checks are performed on external 'type' resources

### ISSUE THREAD

**Issue by sergei-maertens** [open-zaak/open-zaak#314]
... so I can rest assured that there are no security leaks.

**Description**

When operating on local objects with type information from an external catalogue (local Zaak, external zaaktype), I want to be sure that the scopes configured for that zaaktype for that consumer application are honored.

This is a sanity check and task to write some tests for these situations and fix them where needed.

Checklist:

- [x] `Zaak.zaaktype` external
- [x] `EIO.informatieobjecttype` external
- [x] `Besluit.besluittype` external
- [x] `Status.zaak.zaaktype` external
- [x] `Resultaat.zaak.zaaktype` external
- [x] `ZaakInformatieobject.zaak.zaaktype` external
-    `ZaakBesluit.besluit` external - _doesn't affect permission checks_
-    `ZaakInformatieobject.informatieobject` external - _doesn't affect permission checks_
-    `ZaakInformatieobject.zaak` external - _impossible case_
-    `BesluitInformatieobject.besluit` external - - _impossible case_
-    `BesluitInformatieobject.informatieobject` external - _doesn't affect permission checks_

**Comment by annashamray** [comment]
updated checklist in requirements with comments in _italic_
