### ISSUE TITLE
Als functioneel beheerder wil ik dat er afspraken zijn over het moment tijdens het invullen van een formulier dat er een zaak wordt aangemaakt. 

### ISSUE THREAD

**Issue by FrankHarbers** [open-zaak/open-zaak#32]
... so I can [...]

**Description**
Describe the user story in more detail.

**Comment by joeribekker** [comment]
Dit is geen functionaliteit binnen Open Zaak maar typisch geef je dit aan bij vak/domein/afhandel applicaties in de bovenste lagen van het 5-lagen moden.

@FrankHarbers Als je denkt dat dit niet juist is, graag het ticket heropenen met extra uitleg.
