### ISSUE TITLE
Als functioneel beheerder wil ik dat er afpraken gemaakt worden over de relatietypes waarmee we zaken aan elkaar kunnen relateren 

### ISSUE THREAD

**Issue by FrankHarbers** [open-zaak/open-zaak#33]
... so I can [...]

**Description**
Describe the user story in more detail.

**Comment by joeribekker** [comment]
@FrankHarbers Kan je dit verder toelichten?

**Comment by Hugo-ter-Doest** [comment]
De wijze waarop relaties tussen zaken gelegd kunnen worden (bijv. hoofdzaak, deelzaak of andere relevante zaak) is vastgelegd in de standaard. Zie https://zaakgerichtwerken.vng.cloud/standaard/zaken/index. Bij OpenZaak volgen we die mogelijkheden.
