### ISSUE TITLE
Als functioneel beheerder wil ik een KetenInzageComponent (KIC) kunnen configureren

### ISSUE THREAD

**Issue by FrankHarbers** [open-zaak/open-zaak#34]
...waardoor ik alle zaken van een burger (gebundeld) aan de burger kan tonen.
Dashboard/portaal waarop de burger kan inloggen om al zijn lopende en gesloten zaken in te zien.
Waarbij ik als FB kan configureren welke zaaktypen gezamenlijk als een dossier getoond moeten worden.
eventueel integreren van taakapplicaties, zoals de huwelijksplanner?

**Description**
Describe the user story in more detail.

**Comment by joeribekker** [comment]
@FrankHarbers Een KIC is geen onderdeel van Open Zaak. Het klinkt tevens als een applicatie in de bovenste lagen van het Common Ground 5-lagen model.

Het lijkt me verder wel een goed idee :)
