### ISSUE TITLE
Authorizations should check for overlap to prevent fuzzy authorizations

### ISSUE THREAD

**Issue by joeribekker** [open-zaak/open-zaak#356]
**Describe the bug**
Authorizations should check for overlap to prevent fuzzy authorizations

See: https://github.com/open-zaak/open-zaak/pull/307/files#diff-f40996d24e342971921c649c3de886a1R377

**Comment by joeribekker** [comment]
This should actually be enforced on API-level (so in the VNG standard) but it's not (new ticket incoming) but for Open Zaak we can enforce this on UI-level.

**Comment by annashamray** [comment]
Implemented in https://github.com/open-zaak/open-zaak/pull/450
