### ISSUE TITLE
As devops, I want to deploy an Open Notificaties appliance to VMWare or similar

### ISSUE THREAD

**Issue by sergei-maertens** [open-zaak/open-zaak#358]
This is the Open Notificaties variant of #136

**Comment by joeribekker** [comment]
Let's discuss briefly where to put this: Open Zaak or Open Notificaties repo? How to keep this a bit in sync? Or should we make it more generic to apply to both projects?

**Comment by joeribekker** [comment]
See: https://github.com/open-zaak/open-notificaties/pull/13

**Comment by sergei-maertens** [comment]
Merged
