### ISSUE TITLE
Als functioneel beheerder wil ik bij het vastleggen van eigenschappen binnen een zaaktype, kunnen kiezen uit /toe kunnen voegen aan een lijst met eigenschappen die ik kan gebruiken voor mijn organisatie 

### ISSUE THREAD

**Issue by FrankHarbers** [open-zaak/open-zaak#36]
zodat namen van eigenschappen consequent worden gebruikt.
Na het inrichten van twee zaaktypes hebben we nu al de eigenschap Datum vergadering en Vergaderdatum.

**Description**
Describe the user story in more detail.

**Comment by joeribekker** [comment]
@FrankHarbers Waar leg je deze eigenschappen voor je organisatie dan vast?

**Comment by Hugo-ter-Doest** [comment]
Heeft nu 2 maand open gestaan voor aanvulling. Ik sluit het hem af.
