### ISSUE TITLE
The documentation build on RTD is broken

### ISSUE THREAD

**Issue by sergei-maertens** [open-zaak/open-zaak#368]
Currently the build fails because of the Sphinx integration with autodoc loading the project code, which breaks on the GeoDjango integration. lib-gdal is missing in the RTD build environment.

I've commented on https://github.com/readthedocs/readthedocs-docker-images/issues/114#issuecomment-570566599 which also mentions you could script the installtion via `conf.py`

**Comment by SilviaAmAm** [comment]
It is now possible to add gdal to the RTD build:
https://github.com/maykinmedia/open-archiefbeheer/blob/40bfc340cd14e1925a771ca77f35c513576c6336/.readthedocs.yaml#L12
