### ISSUE TITLE
Als functioneel beheerder wil ik bij het vastleggen van rollen binnen een zaaktype, kunnen kiezen uit /toe kunnen voegen aan een lijst met rollen die ik kan gebruiken voor mijn organisatie 

### ISSUE THREAD

**Issue by FrankHarbers** [open-zaak/open-zaak#37]
...zodat namen van rollen consequent worden gebruikt..
Na het inrichten van twee zaaktypes hebben we nu al de de rol coordinator en zaakcoordinator.

**Description**
Describe the user story in more detail.

**Comment by joeribekker** [comment]
@FrankHarbers Waar leg je deze rollen voor je organisatie dan vast?

**Comment by Hugo-ter-Doest** [comment]
Gesloten vanwege geen input.
