### ISSUE TITLE
Als functioneel beheerder wil ik dat er gebruik gemaakt wordt van de sjablonen van de KING referentielijst

### ISSUE THREAD

**Issue by FrankHarbers** [open-zaak/open-zaak#38]
Zodat ik een voorbeeldlijst krijg van resultaten/documenttypes. enz.

**Comment by joeribekker** [comment]
@FrankHarbers Wat is de KING referentielijst? Kan je een concreet voorbeeld tonen **en** de link naar deze referentielijst geven?

Als je het hebt over de Gemeentelijke Selectielijst, dan geeft deze wel wat standaard waarden voor archivering maar het zijn niet echt sjablonen te noemen toch?

**Comment by Hugo-ter-Doest** [comment]
Staat 4 maand op input te wachten. Ik sluit deze.
