### ISSUE TITLE
As a maintainer, I want to isolate environment configuration secrets from the tooling

### ISSUE THREAD

**Issue by sergei-maertens** [open-zaak/open-zaak#384]
... so I can handle different secrets and environments properly and securely.

**Description**
For the different target environments (kubernetes, single-server, vmware appliance), we keep a number of secrets in the Ansible Vault that are instance specific (database credentials, secret keys...). With every installation, these variables change, but the deployment code/configuration does not.

Currently all these secrets are encrypted using the same ansible vault password - which means that the kubernetes/single server deployment use the same vault password.

We should document the structure of these variable files (include examples), and remove the actual secrets from this repository. Actual secrets can then live in separate repositories (per environment) and be added as submodules for the actual deployment.

Perhaps it would also be beneficial to completely separate the deployment tooling in its own repository.

**Comment by joeribekker** [comment]
Please discuss first before commencing.

**Comment by sergei-maertens** [comment]
In #432, the vault-encrypted secrets were removed already (which is good).

The plan is to:

**for both Open Zaak and Open Notificaties**

* create a github repository for the Kubernetes Ansible role
* move `deployment/kubernetes/roles/openzaak` to the github repo
* clean up the role, properly document it
* publish the role on Ansible Galaxy
* adapt `deployment/kubernetes/apps.yml` to use the Ansible Galaxy role

* create a github repository for the Docker Ansible role
* move `deployment/single-server/roles/openzaak` to the github repo
* clean up the role, properly document it
* publish the role on Ansible Galaxy
* adapt `deployment/single-server/open-zaak.yml` to use the Ansible Galaxy role

* create a github repository for the app-database Ansible role
* move `deployment/kubernetes/roles/app-database` and `deployment/single-server/database` roles into that role (so merge them)
* publish the role on Ansible galaxy
* adapt `deployment/kubernetes/apps.yml` to use the Ansible Galaxy role
* adapt `deployment/single-server/open-zaak.yml` to use the Ansible Galaxy role

* create a github repo for the nlx Ansible role
* move `deployment/kubernetes/roles/nlx` to the github repo
* take the log database setup into account (done for Utrecht)
* document & clean up the role
* publish the role on Ansible Galaxy
* adapt `deployment/kubernetes/apps.yml` to use the Ansible Galaxy role

Secrets could be stored as Ansible-vault encrypted variable files in a different repo on Bitbucket which is private, and that *could* be added as a git submodule or we document that you need to check this out separately and use symlinks instead.
