### ISSUE TITLE
Publiceren werkt niet

### ISSUE THREAD

**Issue by joeribekker** [open-zaak/open-zaak#385]
*From: Eduard Witteveen*

**Describe the bug**
Bij het "definitief maken" (publiceren) van `informatieobjecttype` en `zaaktype` gaat er iets fout. Zie bijlagen:

[zaaktypen-definitief.txt](https://github.com/open-zaak/open-zaak/files/4040159/zaaktypen-definitief.txt)
[informatieobjecttypen-definitief.txt](https://github.com/open-zaak/open-zaak/files/4040160/informatieobjecttypen-definitief.txt)

**Comment by stevenbal** [comment]
Het bleek niet zo zeer een probleem te zijn met publiceren, want in de twee tekstbestanden werd er een GET gedaan op `/publish/` i.p.v. een POST, wat een 403 teruggaf (dit bleek een probleem op alle endpoints, ik kreeg ook een 403 als ik PUT probeerde op `/zaken/` bijv.). Ik heb een PR gemaakt die ervoor zorgt dat de API een 405 Method Not Allowed teruggeeft in dit soort gevallen.

**Comment by EduardWitteveen** [comment]
Op welk endpoint (dus rul met of zonder /publish ) in combinatie met welke method moet er gebruikt worden? (na zetten van concept=False)
Ik heb de verschilldende urls (met/zonder publish) in combinatie met PUT/POST gebruikt

(had ik dit ergens in de docu terug kunnen vinden?)

**Comment by stevenbal** [comment]
@EduardWitteveen in de [API spec](https://test.openzaak.nl/catalogi/api/v1/schema/#operation/zaaktype_publish) staat de publish operatie beschreven. Het `concept` attribuut kan alleen op `False` gezet worden door te publiceren, en dat kan voor bijv. zaaktypen door een POST te doen `{{zaaktype_url}}/publish` (bijv. https://test.openzaak.nl/catalogi/api/v1/zaaktypen/1234/publish)

**Comment by EduardWitteveen** [comment]
werkt op de beschreven manier 
(niet duidelijk door een fout de protocol prefix op mijn omgeving)
