### ISSUE TITLE
ResultaatType aanmaken lukt niet

### ISSUE THREAD

**Issue by joeribekker** [open-zaak/open-zaak#389]
*From: Eduard Witteveen*

Voor het toevoegen van een resultaat type zou ik graag voorbeeld waarden voor het attribuut: brondatumArchiefprocedure willen hebben. Ik loop namelijk in het probleem:
  a - bij 'afgehandeld' mag geen waarde voorkomen bij een aantal attributen
  b - bij een aantal attributen attributen moeten attributen (dezelfde :-) ) een waarde hebben

@stevenbal Kan jij een voorbeeld van een POST als antwoord geven?

**Comment by stevenbal** [comment]
@joeribekker 
Een voorbeeld:
```json
{
	"zaaktype": "http://localhost:8000/catalogi/api/v1/zaaktypen/e7061e2c-a430-49df-b8d6-4003bd81b482",
	"omschrijving": "TEST",
	"resultaattypeomschrijving": "https://referentielijsten-api.vng.cloud/api/v1/resultaattypeomschrijvingen/e6a0c939-3404-45b0-88e3-76c94fb80ea7",
	"selectielijstklasse": "https://referentielijsten-api.vng.cloud/api/v1/resultaten/cc5ae4e3-a9e6-4386-bcee-46be4986a829",
	"brondatumArchiefprocedure": {
		"afleidingswijze": "afgehandeld",
		"procestermijn": null,
		"datumkenmerk": "",
		"einddatumBekend": false,
		"objecttype": "",
		"registratie": ""
	}
}
```

In de standaard wordt het uitgebreider uitgelegd welke attributen leeg moeten zijn, afhankelijk van afleidingswijze: https://github.com/VNG-Realisatie/gemma-zaken/blob/master/docs/_content/standaard/catalogi/index.md#ztc-003

**Comment by EduardWitteveen** [comment]
top!

**Comment by sergei-maertens** [comment]
Ik neem aan dat de vraag hiermee beantwoord is en sluit daarom het issue :-)
