### ISSUE TITLE
Ansible deploy needs to take CSRF into account when not deploying for HTTPS

### ISSUE THREAD

**Issue by joeribekker** [open-zaak/open-zaak#393]
**Describe the bug**
When installing at gemeente Buren, we noticed CSRF validation failed when logging into the admin because it was deployed on http instead of https.

**Comment by sergei-maertens** [comment]
Depends on #436 refactor

**Comment by sergei-maertens** [comment]
Handled by setting `IS_HTTPS` in the [`.env` template](https://github.com/open-zaak/ansible-collection/blob/master/roles/open_zaak_docker/templates/env.j2#L13)
