### ISSUE TITLE
Changing .env file does not trigger a Docker restart/reload

### ISSUE THREAD

**Issue by joeribekker** [open-zaak/open-zaak#396]
**Describe the bug**
From our findings at gemeente Buren:

Changes made to the .env file are not picked up by the Docker containers. Either we make them pick up or document you need to restart the containers.

**Comment by sergei-maertens** [comment]
-> detect in Ansible playbook that changes were done
AND
document that manual changes require a container restart

**Comment by sergei-maertens** [comment]
Depends on #436 refactor

**Comment by sergei-maertens** [comment]
Handled during deployment by [restarting the container conditionally](https://github.com/open-zaak/ansible-collection/blob/master/roles/open_zaak_docker/tasks/containers.yml#L23)

**Comment by joeribekker** [comment]
See #452
