### ISSUE TITLE
Export catalog/zaaktype has invalid roltype generic description value

### ISSUE THREAD

**Issue by joeribekker** [open-zaak/open-zaak#397]
**Describe the bug**
When exporting Zaaktype or Catalog with a Roltype, the field "omschrijvingGeneriek" has an incorrect value: `Behandelaar` instead of `behandelaar` (all lowercase)

**Comment by stevenbal** [comment]
@joeribekker het lukt me niet om deze bug te reproduceren, zowel via de API als via de admin lukt het me niet om een Roltype te maken met `omschrijvingGeneriek` `Behandelaar` (met een hoofdletter). Was het Roltype dat jullie probeerden te exporteren misschien ooit een keer aangemaakt toen de enum van RolOmschrijving niet klopte o.i.d.?

**Comment by joeribekker** [comment]
Ok prima, dan sluiten we deze.
