### ISSUE TITLE
As installer, I want to know how to configure Open Notifications on the same machine as Open Zaak

### ISSUE THREAD

**Issue by joeribekker** [open-zaak/open-zaak#405]
... so I can deploy both on the same machine

**Description**
For example you need 2 domains pointing to the same server.

**Comment by sergei-maertens** [comment]
Done in:

* Open Notificaties: https://github.com/open-zaak/open-notificaties/pull/12
* Open Zaak: https://github.com/open-zaak/open-zaak/pull/453
