### ISSUE TITLE
urls starting with http:// instead of https://  when allowed hosts = * in .env

### ISSUE THREAD

**Issue by EduardWitteveen** [open-zaak/open-zaak#413]
**Describe the bug**
All objects that are created on my endpoint: https://openzaak.local/ have an url that starts with: http:// (missing the http**S**:// ) when the allowed hosts = * 

An url that is generated is: 'http://openzaak.local/catalogi/api/v1/catalogussen/b9c6bb08-66ae-4ed4-b125-c3192df6c89a' . I would have expected the url: 'https://openzaak.local/catalogi/api/v1/catalogussen/b9c6bb08-66ae-4ed4-b125-c3192df6c89a'.

This because the hostname is configured in the application

**Comment by sergei-maertens** [comment]
Is the envvar `IS_HTTPS` set to `False` perhaps?

**Comment by sergei-maertens** [comment]
As a side-note - `ALLOWED_HOSTS=*` breaks support for external catalogi APIs, so most likely you'll want to provide this explicitly and set it to `openzaak.local`

**Comment by joeribekker** [comment]
If no input is supplied within 30 days, the issue will be closed.

**Comment by joeribekker** [comment]
You can reopen the issue if the problem still occurs.
