### ISSUE TITLE
Relevante andere zaken URL is ID

### ISSUE THREAD

**Issue by rderooij** [open-zaak/open-zaak#414]
**Describe the bug**
Bij het aanmaken van en zaakrelatie (RelevanteZaak) op een zaak, dan moet je twee waarden meegeven. aardRelatie en URL naar andere zaak. Het aanmaken van de eerste RelevanteZaak gaat goed, maar de daarop volgende niet. Dit komt omdat de URL wordt aangepast naar ID. En bij het toevoegen van een tweede RelevanteZaak wordt de URL gecontroleerd en is inderdaad geen URL.

[{'url': [ErrorDetail(string='Voer een geldige URL in.', code='bad-url')]}, {}]}

**To Reproduce**
1. Aanmaken relevante zaak op zaak
2. Haal zaak informatie op en zie dat er een ID staat ipv een URL

**Expected behavior**
Ik verwacht URL ipv ID.

**Comment by joeribekker** [comment]
@stevenbal Graag verifieren en indien inderdaad een bug, graag ook een issue aanmaken bij VNG.

**Comment by stevenbal** [comment]
Ik krijg inderdaad ook een ID terug waar een URL zou moeten staan. Ik heb het ook op de referentiecomponenten, maar daar loop ik niet tegen dit probleem aan
