### ISSUE TITLE
As a developer, I want to be sure that all admin pages work without errors with read-only permissions

### ISSUE THREAD

**Issue by sergei-maertens** [open-zaak/open-zaak#419]
... so I can look at my date instead of seeing 500 error pages

**Description**

There are a bunch of custom admin forms used, where some fields are accessed with the pattern `self.fields[fieldname]`. This works if you can edit the form, but for read-only permissions, those fields are absent from the form because of how the Django admin works.

When that happens, the end-user will see an error page.

We need to go through the admin pages with a read-only account and :

- check if/where this happens
- write an integration test
- fix the custom form

**Comment by joeribekker** [comment]
I find looking at data to be optional... but added it to sprint anyway ;-)
