### ISSUE TITLE
As developer, I don't want any Ansible secrets included in the repo

### ISSUE THREAD

**Issue by joeribekker** [open-zaak/open-zaak#420]
... so I don't have to worry about exposing them accidentally. 

**Description**
The current secrets are for our test environment only. No one else is going to use this environment, except the maintainer/owner of this environment. So, let's remove the secrets entirely and keep them local.

Discussed earlier but also a gitsubmodule for this seems unneeded.

**Comment by annashamray** [comment]
Implemented in https://github.com/open-zaak/open-zaak/pull/432
