### ISSUE TITLE
creating resultaattype in the admin pages fails with internal error

### ISSUE THREAD

**Issue by annashamray** [open-zaak/open-zaak#473]
Probably some issues with `selectielijst` availability 

The log:

> 2020-02-11 14:56:09,492 ERROR django.request  Internal Server Error: /admin/catalogi/resultaattype/add/
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
>     response = get_response(request)
>   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
>     response = self.process_exception_by_middleware(e, request)
>   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
>     response = wrapped_callback(request, *callback_args, **callback_kwargs)
>   File "/usr/local/lib/python3.7/site-packages/django/contrib/admin/options.py", line 606, in wrapper
>     return self.admin_site.admin_view(view)(*args, **kwargs)
>   File "/usr/local/lib/python3.7/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
>     response = view_func(request, *args, **kwargs)
>   File "/usr/local/lib/python3.7/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
>     response = view_func(request, *args, **kwargs)
>   File "/usr/local/lib/python3.7/site-packages/django/contrib/admin/sites.py", line 223, in inner
>     return view(request, *args, **kwargs)
>   File "./openzaak/utils/admin.py", line 346, in add_view
>     extra_context=self._get_extra_context(request, extra_context),
>   File "/usr/local/lib/python3.7/site-packages/django/contrib/admin/options.py", line 1645, in add_view
>     return self.changeform_view(request, None, form_url, extra_context)
> 3:58
>   return self.changeform_view(request, None, form_url, extra_context)
>   File "/usr/local/lib/python3.7/site-packages/django/utils/decorators.py", line 45, in _wrapper
>     return bound_method(*args, **kwargs)
>   File "/usr/local/lib/python3.7/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
>     response = view_func(request, *args, **kwargs)
>   File "/usr/local/lib/python3.7/site-packages/django/contrib/admin/options.py", line 1529, in changeform_view
>     return self._changeform_view(request, object_id, form_url, extra_context)
>   File "/usr/local/lib/python3.7/site-packages/django/contrib/admin/options.py", line 1562, in _changeform_view
>     ModelForm = self.get_form(request, obj, change=not add)
>   File "/usr/local/lib/python3.7/site-packages/django/contrib/admin/options.py", line 705, in get_form
>     return modelform_factory(self.model, **defaults)
>   File "/usr/local/lib/python3.7/site-packages/django/forms/models.py", line 551, in modelform_factory
>     return type(form)(class_name, (form,), form_class_attrs)
>   File "/usr/local/lib/python3.7/site-packages/django/forms/models.py", line 256, in __new__
>     apply_limit_choices_to=False,
>   File "/usr/local/lib/python3.7/site-packages/django/forms/models.py", line 176, in fields_for_model
>     formfield = formfield_callback(f, **kwargs)
>   File "./openzaak/components/catalogi/admin/resultaattype.py", line 98, in formfield_for_dbfield
>     return get_resultaattype_omschrijving_field(db_field, request, **kwargs)
>   File "./openzaak/selectielijst/admin_fields.py", line 72, in get_resultaattype_omschrijving_field
>     help_text=db_field.help_text,
>   File "/usr/local/lib/python3.7/site-packages/django/forms/fields.py", line 767, in __init__
>     self.choices = choices
>   File "/usr/local/lib/python3.7/site-packages/django/forms/fields.py", line 784, in _set_choices
>     value = list(value)
>   File "./openzaak/selectielijst/admin_fields.py", line 66, in 
>     for omschrijving in get_resultaattype_omschrijvingen()

**Comment by joeribekker** [comment]
Source: Utrecht proeftuin
Related sentry issue: https://sentry.maykinmedia.nl/maykin-media/open-zaak/issues/266982/
