### ISSUE TITLE
Resultaattype-omschrijvingen resource is missing in Selectielijst.

### ISSUE THREAD

**Issue by joeribekker** [open-zaak/open-zaak#479]
**Describe the bug**
The resultaattype-omschrijvingen is missing from the Selectielijst API and is needed by Open Zaak. I think it got removed by accident?

See: https://github.com/open-zaak/vng-selectielijst

Compare: https://referentielijsten-api.vng.cloud/api/v1/schema/
To: https://selectielijst.openzaak.nl/api/v1/schema/

**To Reproduce**
1. Configure Open Zaak to use selectielijst.openzaak.nl
2. Create a new Zaaktype, and add a new resultaattype
3. You will get a HTTP 500

**Expected behavior**
Selectielijst API should have this resource.

**Comment by annashamray** [comment]
@joeribekker selectielijst.openzaak.nl has never had a `resultaattype-omschrijvingen` resource. As far as I know the future of this resource is not determined yet and so it wasn't included into selectielijst.openzaak.nl

@sergei-maertens can provide necessary information about it

**Comment by sergei-maertens** [comment]
yeah, this is problematic since the content is not standardized by VNG (yet). We should also provide the resultaattypeomschrijvingen resource and fill in some data. I think we should be able to get actual used content from I-navigator
