### ISSUE TITLE
Resultaattype from Selectielijst doesn't seem to respect or see the Zaaktype processtype.

### ISSUE THREAD

**Issue by joeribekker** [open-zaak/open-zaak#480]
**Describe the bug**
Selectielijst Zaaktype doesn't seem to show. And the possible resultaattypes dont seem to be filtered correctly (tried with referentielijsten-api.vng.cloud and selectielijst.openzaak.nl)

![image](https://user-images.githubusercontent.com/96970/74415670-15e08600-4e44-11ea-9425-bf2fcc959c35.png)

**To Reproduce**
1. Create Zaaktype
2. Add Resultaattype
3. Check selectielijstklasse

**Expected behavior**
Zaaktype processtype should be shown and ist should be filtered

**Comment by annashamray** [comment]
This case only happens when a new `resultaattype` is being created and it's `zaaktype` field is not save to DB yet. Once you choose the `zaaktype` and submit the form the `Zaaktype processtype` field and filtering of `selectielijstklasse` will appear

**Comment by joeribekker** [comment]
Can we add a message in that case where the "-" (dash) is now as value for Zaaktype:

"Please save this Resultaattype first to get proper filtering of selectielijstklasses" (Kies "Opslaan en opnieuw bewerken" om de bijpassende selectielijstklassen te filteren.")

**Comment by joeribekker** [comment]
Or better, grab the Zaaktype from the query parameters of not on the object (`?zaaktype=X`)
