### ISSUE TITLE
403 Forbidden on lins to uploaded files

### ISSUE THREAD

**Issue by haarlem-dvh** [open-zaak/open-zaak#481]
I am using a local installation of OpenZaak in a Ubuntu VM. I used this installation guide: https://open-zaak.readthedocs.io/en/latest/installation/deployment/single_server.html
Everything works. I can use the Admin dashboard and add zaken, objects and documents with the API.

When I GET an 'enkelvoudiginformatieobject' with:

``` 
https://openzaak.local/documenten/api/v1/enkelvoudiginformatieobjecten/d472e687-b338-482f-96cd-2d9482560c55
```
this returns the correct document.

When i GET the 'inhoud'-link 
```
https://openzaak.local/documenten/api/v1/enkelvoudiginformatieobjecten/d472e687-b338-482f-96cd-2d9482560c55/download?versie=1) 
```
this results in: 

```
<html>

<head>
	<title>403 Forbidden</title>
</head>

<body>
	<center>
		<h1>403 Forbidden</h1>
	</center>
	<hr>
	<center>nginx</center>
</body>

</html>
```

When I look the document op in the Admin dashboard, the link to the inhoud also fails with an 403.

I have not altered the provided NginX configuratien (except for cert configuration).

```
upstream openzaak {
            server 127.0.0.1:8000;
            server 127.0.0.1:8001;
            server 127.0.0.1:8002;
    }


server {
    server_tokens off;
    listen 443 ssl;
    server_name openzaak.local;
    client_max_body_size 4G;

    include snippets/self-signed.conf;
    include snippets/ssl-params.conf;

    # Enable Gzip, from html5-boilerplate-server-configs
    gzip  on;
    gzip_http_version 1.0;
    gzip_comp_level 2;
    gzip_min_length 1100;
    gzip_buffers     4 8k;
    gzip_proxied any;
    gzip_types

      # text/html is always compressed by HttpGzipModule
      text/css
      text/javascript
      text/xml
      text/plain
      text/x-component
      application/javascript
      application/json
      application/xml
      application/rss+xml
      font/truetype
      font/opentype
      application/vnd.ms-fontobject
      image/svg+xml;

    gzip_static on;

    gzip_proxied        expired no-cache no-store private auth;
    gzip_disable        "MSIE [1-6]\.";
    gzip_vary           on;

    
    location / {
        proxy_pass_header Server;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $server_name;
        proxy_set_header X-Scheme $scheme;
        proxy_connect_timeout 300s;
        proxy_read_timeout 300s;

        proxy_set_header Host $http_host;
        proxy_redirect off;
        proxy_pass_request_headers on;
        proxy_pass http://openzaak;
    }

    location /private-media {
        internal;
        alias /var/lib/docker/volumes/openzaak-private-media/_data;
    }

    error_page  404              /404.html;
    error_page  413              /413.json;
    error_page  500 502 503 504  /500.json;
}
```

The uploaded document is present in the folder shown in the Admin Dashboard:
```
/var/lib/docker/volumes/openzaak-private-media/_data/uploads/2020/02/f02ba7a4-200e-476a-b889-56ef90ca1ddd.bin
```

I have tried setting the folder rights to 777 but that did not fix this.

Is this a known bug or something that is wrong in my configuration?

**Comment by sergei-maertens** [comment]
Going to try to reproduce this :+1:

**Comment by sergei-maertens** [comment]
@haarlem-dvh thanks for the report, we had overlooked a part in the configuration, which is now (read: soon :tm: ) fixed!

#487 contains the fixed infrastructre update, which will be provided in the Open Zaak 1.0.2 release. This will be available this week. Applying the fix will boil down to following the [update procedure](https://open-zaak.readthedocs.io/en/latest/installation/deployment/single_server.html#updating-an-open-zaak-installation).

For reference, the relevant infrastructure changes can be found [here](https://github.com/open-zaak/ansible-collection/commit/7f964315b583adeb6d31f8e4790020dc37d53a72).

No manual intervention will be required, the update to 1.0.2 is automatic.
