### ISSUE TITLE
The wrong browser page title is shown on the redoc page for the catalogi API

### ISSUE THREAD

**Issue by CMasselink** [open-zaak/open-zaak#495]
**Describe the bug**
Instead of Catalogi API the Zaken API is shown on the redoc page of the catalogi api:
![afbeelding](https://user-images.githubusercontent.com/39768984/75543687-ad3c0080-5a22-11ea-961d-e0795b62b73f.png)

**To Reproduce**
1. Open the catalogi API on  https://openzaak.utrechtproeftuin.nl/catalogi/api/v1/schema/
2. check browser title

**Expected behavior**
Catalogi API in browser title

**Comment by joeribekker** [comment]
@stevenbal I'm not sure what's causing this but could be caching perhaps?

What happens if you set the cache_timeout to 0 in the urls?

```
                    SchemaView.with_ui(
                        "redoc", cache_timeout=0
                    ),
```

If it's caching i think you can pass a key_prefix to fix it as well.

**Comment by stevenbal** [comment]
@joeribekker it has to do with the `info` parameter used in `get_schema_view` in drf_yasg, it now defaults to `SWAGGER_SETTINGS.DEFAULT_INFO` which is set to the info of zaken api
