### ISSUE TITLE
As developer, I want to have FK-relations between core resources

### ISSUE THREAD

**Issue by joeribekker** [open-zaak/open-zaak#5]
... so I can rely on a consistent data structure.

**Description**
Currently, relations are on API-level using URLs to relate one object to another. For local API URLs (ie. those that point to an API that is part of OpenZaak), we should store the relationship on database level.

**Comment by Hugo-ter-Doest** [comment]
I think " we should store the relationship on database level" should be "we should store the relationship both as a URL and as a database relation (FK)".

**Comment by sergei-maertens** [comment]
URLs are generated from database values, there's no reason to store the URL as well if it's a local resource.

**Comment by sergei-maertens** [comment]
@annashamray I think we've got everything as FK now, right?

**Comment by annashamray** [comment]
Yes, I think all components have DB-relations now.

**Comment by sergei-maertens** [comment]
Cool, closing this one, it'll be finalized when #60 is merged.
