### ISSUE TITLE
As maintainer I want to be able to see which Zaaktypen are inactive

### ISSUE THREAD

**Issue by MichelleDautzenberg** [open-zaak/open-zaak#510]
so I can see which Zaaktypen are in use and which are not.

I added an enddate to the Zaaktype, but the status remains Gepubliceerd:

![afbeelding](https://user-images.githubusercontent.com/48316239/76628272-c2458300-653c-11ea-967c-3270e8fe710c.png)

![afbeelding](https://user-images.githubusercontent.com/48316239/76628369-e43f0580-653c-11ea-9a3a-61ca2eefdfd4.png)

**Description**
Describe the user story in more detail.

**Comment by joeribekker** [comment]
So, we could add a filter to the right side "active: yes/no" where active means it's both published AND the end date is n/a or in the future.

**Comment by MichelleDautzenberg** [comment]
Yes please!
