### ISSUE TITLE
Afleidingswijze brondatum niet altijd correct

### ISSUE THREAD

**Issue by joeribekker** [open-zaak/open-zaak#520]
Email from Jurjen and Michelle (Utrecht):

**Describe the bug**
Wanneer ik een resultaattype aan een zaak toevoeg, moet de datum afhandeling worden afgeleid uit de selectielijst.

Twee opmerkingen:

1) Blijkbaar wordt de waarde op de achtergrond afgeleid. Wanneer ik er 1 kies uit de dropdown “Afleidingswijze brondatum” wordt deze in veel gevallen afgekeurd. Bijvoorbeeld  bij 14.1.1  kan ik niet kiezen voor datum Afgehandeld als afleidingswijze: dat levert een foutmelding op.

2) de afleiding klopt vaak niet. Dit komt deels omdat de selectielijst niet 1 op 1 te vertalen is naar een vaste variabele.  En in sommige gevallen klopt de afleiding gewoon niet: in bovengenoemd voorbeeld, 14.1.1. moet de afleidingswijze brondatum, de datum afgehandeld zijn, maar die kan ik niet kiezen.

Kunnen jullie aangeven of dit zo zou moeten werken?

![image](https://user-images.githubusercontent.com/96970/77432992-16732180-6ddf-11ea-80a1-fcd11b078eba.png)

**To Reproduce**
Steps to reproduce the behavior (inferred from above email by Jurjen):
1. Create Zaaktype with Procestype = 14
2. Create Resultaattype with Resultaattype = 14.1.1
3. In Resultaattype, select "Afgehandeld" as "Afleidingswijze brondatum"
4. Can't save with error.

**Expected behavior**
Save should be possible?

**Comment by joeribekker** [comment]
Het lijkt er op dat 14.1.1 waardering "bewaren" heeft en hierdoor ook geen afleidingswijze voor de brondatum nodig heeft.

Ik kan het niet goed zien, maar overrulen jullie dit naar "vernietigen"?

Volgens mij klopt de afleiding wel redelijk 1 op 1. Ik zeg wel redelijk, omdat ik het niet zeker weet. Heb je meer voorbeelden?

**Comment by MichelleDautzenberg** [comment]
We overrulen dit niet naar vernietigen.
We moeten toch kunnen aangeven vanaf welk moment (=Afgehandeld) de bewaartermijn moet starten?

**Comment by joeribekker** [comment]
> We moeten toch kunnen aangeven vanaf welk moment (=Afgehandeld) de bewaartermijn moet 
starten? Of dit nu bewaren of vernietigen is, dat zou toch niet uit moeten maken?

Maar, bewaren betekent eeuwig bewaren toch? Anders is het vernietigen, na zoveel tijd.

> EN Afleidingswijze Brondatum is een verplicht veld, dus leeg laten is ook geen optie :)

Dat zou dan inderdaad een bug zijn :)

**Comment by JurjenBert** [comment]
Bewaren betekent inderaad eeuwig bewaren, maar niet in de ZRC en/of DRC. Op enig moment vindt overbrenging plaats naar een archief. 
De archiefactietermijn slaat in het geval van bewaren op het moment van het overbrengen. Die wordt standaard berekend tov de datum afgehandeld. 
Nominatie Bewaren icm met achiefactietermijn 10 jaar betekent dus: over 10 jaar moeten de zaken worden overgebracht naar een definitief archief. 

Je hebt dus altijd een afleidingswijze brondatum nodig om de archiefactiedatum te berekenen, of het nou om bewaren of vernietigen gaat.

**Comment by JurjenBert** [comment]
een aantal constateringen nav bovenstaande
1) in geval van bewaren is de afleidingswijze brondatum altijd afgehandeld
2) de afleidingswijze brondatum mag nooit leeg zijn
3) de afleidingswijze brondatum valt voor zover ik weet niet 1 op 1 te vertalen naar het lijstje wat in de drop down getoond wordt. Het moet minimaal mogelijk zijn om de waarde in de selectielijst te interpreteren en deze zelf te kunnen koppelen aan een van de waarden in de drop down. 

Wat utrechtse context: wij gaan uit van de volgende 3 afleidingswijzes voor het berekenen van de archieftactietermijn
1) tov de datum afgehandeld. Dit is meestal het geval, en altijd in geval van nominatie bewaren.  
2) tov van een datum die wordt ingevuld bij het afsluiten van een zaak (liefst een eigenschap uit de zaak). Hierbij kun je denken aan een vervaldatum van een vergunning of de datum dat een leerling niet meer leerplichtig is, of 
3) tov een datum die je nog niet weet bij het afsluiten van een zaak. Denk hierbij aan een zaak voor het in dienst nemen van een personeelslid. Was wanneer het personeelslid uit dienst treedt, kan de datum ingevuld worden.

**Comment by joeribekker** [comment]
Okay, ik ga de volgende stappen nemen:

1. Overbrengen hebben we nooit als actie gezien die afhangt van een bewaartermijn. Je mag gegevens volgens mij altijd overbrengen naar een archiefdepot. Ik ga dit met VNG opnemen.
2. Ik ga intern overleggen of dit een bug of gedrag volgens de standaard betreft, en of die standaard evt moet worden aangepast.
3. Ik betwijfel toch nog of het niet 1-op-1 te vertalen is. Je geeft aan dat er ruimte voor interpretatie is maar volgens mij moet de Selectielijst precies dit voorkomen. Ook deze ga ik opnemen met VNG.

**Comment by JurjenBert** [comment]
👍
________________________________

**Comment by stevenbal** [comment]
@joeribekker ik heb gekeken wat de mogelijkheden zijn voor `BrondatumArchiefprocedure.afleidingswijze` als `selectielijstklasse.waardering` `blijvend_bewaren` is, deze zijn voor de API en de admin hetzelfde:

Niet mogelijke afleidingswijzen:
- afgehandeld
- termijn

Wel mogelijk:
- eigenschap
- gerelateerde_zaak
- hoofdzaak
- ingangsdatum_besluit
- vervaldatum_besluit
- zaakobject

**Comment by joeribekker** [comment]
Even correctie op mezelf:

> Overbrengen hebben we nooit als actie gezien die afhangt van een bewaartermijn. Je mag gegevens volgens mij altijd overbrengen naar een archiefdepot. Ik ga dit met VNG opnemen.

Mijn geheugen liet me in de steek. Dit is wel de bedoeling.

**Comment by joeribekker** [comment]
@JurjenBert en @MichelleDautzenberg is jullie probleem opgelost als jullie simpelweg **wel** afgehandeld en termijn kunnen kiezen indien archiefnominatie bewaren betreft?

**Comment by JurjenBert** [comment]
@joeribekker en @MichelleDautzenberg 
Ja, dan is het opgelost voor archiefnominatie bewaren (want  in geval van bewaren, is de interpretatie van de afleidingswijze altijd afgehandeld). 

Het probleem voor  archiefnominatie vernietigen bestaat dan echter nog steeds. Afleidingswijzen zoals hoofdzaak, eigenschap, zaakobject komen niet als zodanig voor in de selectielijst (zoja, hoor ik graag welke kolom dat is). Omdat die relatie niet 1 op 1 is, is er een interpretatie voor nodig voor het vertalen van de selectielijst naar een afleidingswijze zoals in het pulldown menu. 

Ik begrijp daarom ook niet hoe er gecontroleerd kan worden op de geselecteerde afleidingswijze.
Minimaal moet kunnen worden afgeweken van de verwachte waarden. Als dat kan conform bij bewaren, is dit probleem helemaal opgelost.

**Comment by joeribekker** [comment]
> Het probleem voor archiefnominatie vernietigen bestaat dan echter nog steeds. Afleidingswijzen zoals hoofdzaak, eigenschap, zaakobject komen niet als zodanig voor in de selectielijst (zoja, hoor ik graag welke kolom dat is). Omdat die relatie niet 1 op 1 is, is er een interpretatie voor nodig voor het vertalen van de selectielijst naar een afleidingswijze zoals in het pulldown menu.
> 
> Ik begrijp daarom ook niet hoe er gecontroleerd kan worden op de geselecteerde afleidingswijze.
> Minimaal moet kunnen worden afgeweken van de verwachte waarden. Als dat kan conform bij bewaren, is dit probleem helemaal opgelost.

Het klopt dat er geen kolom voor de afleidingswijze in de selectielijst. Het klopt ook dat er interpretatie nodig is. We hebben daarom maar 2 basale regels in Open Zaak (gelijk aan de [standaard](https://github.com/VNG-Realisatie/gemma-zaken/blob/master/docs/_content/standaard/catalogi/index.md#ztc-003)):

* afleidingswijze MOET `afgehandeld` zijn indien de selectielijstklasse kolom `procestermijn` de waarde `nihil` heeft
* afleidingswijze MOET `termijn` zijn indien de selectielijstklasse kolom `procestermijn` de waarde `ingeschatte_bestaansduur_procesobject` heeft

We dwingen dus maar in 2 gevallen iets af (en daar kan niet vanaf geweken worden, maar we laten dit dus los bij bewaren). Klopt dit niet volgens jou?

PS. Heel fijn dat jullie meedenken en ik wil echt graag het probleem oplossen maar...

> Minimaal moet kunnen worden afgeweken van de verwachte waarden.

dit zou direct tegen de standaard ingaan, iets wat me Open Zaak juist niet willen. Het proces om de standaard te wijzigen duurt helaas langer dan een technische oplossing doorvoeren.

**Comment by JurjenBert** [comment]
Hallo @joeribekker 
De constraints lijken logisch, en daar zouden we prima mee uit de voeten kunnen. Maar ik heb de indruk dat de controles niet op die manier werken, namelijk dat er in veel meer situaties iets wordt afgedwongen. 

Twee voorbeelden: op basis van de 2 basale regels zou ik voor een zaaktype van procestype 14 (Openbare ruimte inrichten) het volgende verwachten:
1)	Wanneer ik een resultaattype 14.1 toevoeg (nominatie vernietigen, procestermijn “De bestaans- of geldigheidsduur van het procesobject”) zou ik zelf de afleidingswijze mogen bepalen (procestermijn is niet nihil, en ook niet De ingeschatte maximale bestaansduur van het procesobject). 
2)	Wanneer ik resultaattype 14.1.1 wil toevoegen (nominatie bewaren, procestermijn leeg) zou ik ook zelf de afleidingswijze mogen bepalen.
Echter: ik ben ik beide situaties niet vrij om de waarde voor afleidingswijze zelf in te vullen (afgehandeld bijvoorbeeld wordt voor beide resultaattypen afgekeurd).  Dat zou dan toch niet moeten?   

Nog een opmerking: Wat mij opvalt is dat jij het hebt over de waarde ingeschatte_bestaansduur_procesobject. Als ik kijk in de selectielijst van de vng, bevat de kolom procestermijn niet die waarde, maar omschrijvingen als "De ingeschatte maximale bestaansduur van het procesobject". Kan het zijn dat de vertaling overal goed is gegaan?

**Comment by joeribekker** [comment]
Hoi @JurjenBert 

> 2. Wanneer ik resultaattype 14.1.1 wil toevoegen (nominatie bewaren, procestermijn leeg) zou ik ook zelf de afleidingswijze mogen bepalen.
> Echter: ik ben ik beide situaties niet vrij om de waarde voor afleidingswijze zelf in te vullen (afgehandeld bijvoorbeeld wordt voor beide resultaattypen afgekeurd). Dat zou dan toch niet moeten?

Volgens mij wordt punt 2 opgelost als we bij de validatie van afleidingswijze weghalen als de procestermijn leeg is in de selectielijst (typisch bij archiefnominatie bewaren). Ik ga dit ook aanpassen in de standaard bij VNG.

> 1. Wanneer ik een resultaattype 14.1 toevoeg (nominatie vernietigen, procestermijn “De bestaans- of geldigheidsduur van het procesobject”) zou ik zelf de afleidingswijze mogen bepalen (procestermijn is niet nihil, en ook niet De ingeschatte maximale bestaansduur van het procesobject).

Bij punt 1 heb je gelijk dat je geen "afgehandeld" kan selecteren. Ik was niet helemaal volledig in mijn regel weergave. Je MAG ALLEEN afgehandeld selecteren als de procestermijn nihil is.

Ik vind het echter vreemd dat je hier afgehandeld wil selecteren. In de selectielijst staat duidelijk dat het afhangt van de einde geldigheid van het procesobject. Waarom dan toch afgehandeld willen selecteren?

> Nog een opmerking: Wat mij opvalt is dat jij het hebt over de waarde ingeschatte_bestaansduur_procesobject. Als ik kijk in de selectielijst van de vng, bevat de kolom procestermijn niet die waarde, maar omschrijvingen als "De ingeschatte maximale bestaansduur van het procesobject". Kan het zijn dat de vertaling overal goed is gegaan?

Sorry, dit is mijn technische waarde vs de tekstuele waarde:

- `nihil` - Nihil
- `bestaansduur_procesobject` - De bestaans- of geldigheidsduur van het procesobject.
- `ingeschatte_bestaansduur_procesobject` - De ingeschatte maximale bestaans- of geldigheidsduur van het procesobject.
- `vast_te_leggen_datum` - De tijdens het proces vast te leggen datum waarop de geldigheid van het procesobject komt te vervallen.
- `samengevoegd_met_bewaartermijn` - De procestermijn is samengevoegd met de bewaartermijn.

Zie ook: https://selectielijst.openzaak.nl/api/v1/schema/#operation/resultaat_read

**Comment by JurjenBert** [comment]
"Volgens mij wordt punt 2 opgelost als we bij de validatie van afleidingswijze weghalen als de procestermijn leeg is in de selectielijst (typisch bij archiefnominatie bewaren). Ik ga dit ook aanpassen in de standaard bij VNG."
> dat is mooi. 

"Bij punt 1 heb je gelijk dat je geen "afgehandeld" kan selecteren. Ik was niet helemaal volledig in mijn regel weergave. Je MAG ALLEEN afgehandeld selecteren als de procestermijn nihil is.
Ik vind het echter vreemd dat je hier afgehandeld wil selecteren. In de selectielijst staat duidelijk dat het afhangt van de einde geldigheid van het procesobject. Waarom dan toch afgehandeld willen selecteren?"

> Ik ga daarbij af op de verzoeken die we hebben gekregen bij de inrichting van onze huidige zaaktypen (waarbij het merendeel is ingericht tov de datum afgehandeld). Ik vind het prima om het voor nu zo te laten, en verder te kijken of we de inrichting voor elkaar krijgen zonder af te wijken. Dan kan dit issue gesloten worden.
