### ISSUE TITLE
I cannot change the field 'Omschrijving generiek' in a Resultaattype

### ISSUE THREAD

**Issue by MichelleDautzenberg** [open-zaak/open-zaak#532]
**Describe the bug**
If I want to change a Resultaattype, I cannot change the field 'Omschrijving generiek'.
If I made a mistake in this field and already saved the Resultaattype, I have to delete the entire Resultaattype and start from scratch. 

![afbeelding](https://user-images.githubusercontent.com/48316239/78024051-023ba100-7358-11ea-81b2-b3d6e6cc668a.png)

**To Reproduce**
1. Make and save a new Resultaattype. Make sure the field 'Omschrijving generiek' is filled.
2. Try to edit the Resultaattype. 

**Expected behavior**
Just like the field 'Omschrijving', I can change the field 'Omschrijving generiek'

**Comment by stevenbal** [comment]
Het klopt inderdaad dat het veld `Omschrijving generiek` readonly is in de admin, dit veld wordt afgeleid uit het veld `Resultaattypeomschrijving` onder `Gemeentelijke selectielijst`:
![Screenshot from 2020-04-03 12-25-24](https://user-images.githubusercontent.com/29249171/78350905-3f956e00-75a6-11ea-9adc-e55d9e6d3281.png)

Ik heb wel gezien dat er in die afleiding een bug zit, omdat de generieke omschrijving niet geupdate wordt als de `Resultaattypeomschrijving` aangepast wordt, dus dat zal ik fixen
