### ISSUE TITLE
Saving a new Document in the admin gives a 500 error

### ISSUE THREAD

**Issue by stevenbal** [open-zaak/open-zaak#548]
**Describe the bug**
When trying to create a new EnkelvoudigInformatieObject in the admin, saving it gives the following error:
```html
Request Method: | POST
-- | --
http://localhost:8000/admin/documenten/enkelvoudiginformatieobject/add/
2.2.10
AttributeError
'InMemoryUploadedFile' object has no attribute 'instance'


```

**To Reproduce**
1. Go to the admin page to add an Informatieobject
2. Fill in the details and try to save

**Expected behavior**
Saving shouldn't crash the page and should properly save the object

**Comment by stevenbal** [comment]
should be fixed by https://github.com/sergei-maertens/django-privates/pull/2

**Comment by sergei-maertens** [comment]
Should be fixed indeed.
