### ISSUE TITLE
Dependencies aren't pinned exactly

### ISSUE THREAD

**Issue by sergei-maertens** [open-zaak/open-zaak#55]
**Describe the bug**

Only the `requirements/base.in` is used as input to pip-compile. The production/dev requirements should also be frozen, as we've run into strange issues between minor versions of isort for example.

**Comment by joeribekker** [comment]
`dev.in` is ok, but I don't really want deviations for production anyway?

**Comment by sergei-maertens** [comment]
nope, that also won't happen. I want to reduce that as much as possible, so might just do away with `production.txt` alltogether, or keep it as an alias for `base.txt`. In the docker-context, you want uwsgi etc. in the base deps anyway.
