### ISSUE TITLE
Can not recreate client id in application because of remaining data in table after delete

### ISSUE THREAD

**Issue by plaarakkers-trifork** [open-zaak/open-zaak#551]
**Describe the bug**
When a client id for an application is deleted not all data is removed. This results in a message that the client id exists when you try to reuse this.

**To Reproduce**
1. Create an application with a client id.
2. Delete the client id.
3. Try to reuse this client id in an application.
4. A message is shown that the client id already exists.
5. It looks like the reason for this is that the client id is still present in the table 'vng_api_common_jwtsecret'. After removing the row with the specific client id it is possible to reuse the client id.

**Expected behavior**
It should be possible to reuse a client id that was deleted previously.

**Comment by joeribekker** [comment]
Good find!

@stevenbal can you confirm with a unit test and fix the sync between those two tables (if I remember correctly)?
