### ISSUE TITLE
Cannot open zaak page when EIO files are not available by external system

### ISSUE THREAD

**Issue by rderooij** [open-zaak/open-zaak#554]
**Is your feature request related to a problem? Please describe.**
You get an internal server error when related documents (EIO) are not available when clicking on some case (zaak). (1.0.4)

**Describe the solution you'd like**
It would be nice to be able to still edit the zaak metadata.  Even if related documents are not available. Maybe an indicator icon that indicate resource is not available. Which means the ZAAKINFORMATIEOBJECTEN component have to be disabled.  

**Describe alternatives you've considered**
If this is not possible, maybe provide more information about why the zaak page cannot be loaded.

**Comment by joeribekker** [comment]
Thanks for reporting this @rderooij . I consider this a bug so we will pick it up asap.

@stevenbal please discuss with @sergei-maertens what we can do to make this work. I think we should indeed disable or show empty parts if they are unused/in use by an external component but that's just a quick assesment.
