### ISSUE TITLE
Template rendering error when create resulttype in user interface because of a key error

### ISSUE THREAD

**Issue by plaarakkers-trifork** [open-zaak/open-zaak#556]
**Describe the bug**
When I go to the resulttypes for a case type within the ui I get an error page because of the following error:

Request Method: | GET
-- | --
http://open-zaak.utrecht.local:8001/admin/catalogi/resultaattype/add/?_changelist_filters=zaaktype__id__exact%3D4&catalogus=1&zaaktype=4
2.2.10
KeyError
'nummer'
./openzaak/components/catalogi/admin/resultaattype.py in get_zaaktype_procestype, line 139
/usr/local/bin/uwsgi
3.7.7
['.',  '',  '/usr/local/lib/python37.zip',  '/usr/local/lib/python3.7',  '/usr/local/lib/python3.7/lib-dynload',  '/usr/local/lib/python3.7/site-packages']
wo, 15 Apr 2020 08:28:38 +0000

7 | <div class="form-row{% if line.fields\|length_is:'1' and line.errors %} errors{% endif %}{% if not line.has_visible_field %} hidden{% endif %}{% for field in line %}{% if field.field.name %} field-{{ field.field.name }}{% endif %}{% endfor %}">
-- | --
{% if line.fields\|length_is:'1' %}{{ line.errors }}{% endif %}
{% for field in line %}
<div{% if not line.fields\|length_is:'1' %} class="fieldBox{% if field.field.name %} field-{{ field.field.name }}{% endif %}{% if not field.is_readonly and field.errors %} errors{% endif %}{% if field.field.is_hidden %} hidden{% endif %}"{% elif field.is_checkbox %} class="checkbox-row"{% endif %}>
{% if not line.fields\|length_is:'1' and not field.is_readonly %}{{ field.errors }}{% endif %}
{% if field.is_checkbox %}
{{ field.field }}{{ field.label_tag }}
{% else %}
{{ field.label_tag }}
{% if field.is_readonly %}
<div class="readonly">{{ field.contents }}</div>
{% else %}
{{ field.field }}
{% endif %}
{% endif %}
{% if field.field.help_text %}
<div class="help">{{ field.field.help_text\|safe }}</div>
{% endif %}
</div>
{% endfor %}
</div>

**To Reproduce**
1. Navigate to the resultypes overview for a case type
2. Click on the 'resultaattype toevoegen' button

**Expected behavior**
I expect to be able to add a result type.

**Comment by sergei-maertens** [comment]
Can you specify which selectielijst procestype was picked for the zaaktype?

**Comment by plaarakkers-trifork** [comment]
I did not specify a selectielijstProcestype for the zaaktype during creation. According to the specification this was not required. When retrieving the zaaktype the field is also empty:

{
            "url": "http://open-zaak.utrecht.local:8001/catalogi/api/v1/zaaktypen/556bd754-e48c-4fe9-bbb8-180655f3b736",
            "identificatie": "EVE3",
            "omschrijving": "Evenementen vergunning 3",
            "omschrijvingGeneriek": "",
            "vertrouwelijkheidaanduiding": "openbaar",
            "doel": "doel",
            "aanleiding": "aanleiding",
            "toelichting": "",
            "indicatieInternOfExtern": "extern",
            "handelingInitiator": "aanvragen",
            "onderwerp": "Evenementenvergunning",
            "handelingBehandelaar": "behandelen",
            "doorlooptijd": "P31D",
            "servicenorm": null,
            "opschortingEnAanhoudingMogelijk": false,
            "verlengingMogelijk": false,
            "verlengingstermijn": null,
            "trefwoorden": [],
            "publicatieIndicatie": true,
            "publicatietekst": "",
            "verantwoordingsrelatie": [],
            "productenOfDiensten": [
                "http://example.com"
            ],
            "selectielijstProcestype": "",
            "referentieproces": {
                "naam": "test",
                "link": ""
            },
            "catalogus": "http://open-zaak.utrecht.local:8001/catalogi/api/v1/catalogussen/bdb59a0b-3ac3-4d8c-9a25-d5e4c3800d82",
            "statustypen": [],
            "resultaattypen": [],
            "eigenschappen": [],
            "informatieobjecttypen": [],
            "roltypen": [],
            "besluittypen": [],
            "deelzaaktypen": [],
            "gerelateerdeZaaktypen": [],
            "beginGeldigheid": "2020-04-14",
            "eindeGeldigheid": null,
            "versiedatum": "2020-04-14",
            "concept": true
        }

**Comment by sergei-maertens** [comment]
Yes, that's an odd thing in the specification and the older spec that the standard was based on. Resultaat resource requires a reference to the selectielijst, which depends on the procestype in the zaaktype, but somehow procestype is optional.

Either way, I think the issue is rooted in that, thanks for reporting it!
