### ISSUE TITLE
Deleting a decision from a case results in a 500 response 

### ISSUE THREAD

**Issue by plaarakkers-trifork** [open-zaak/open-zaak#558]
**Describe the bug**
When I try to remove a decision from a case using the API I receive a 500 response:

> FieldError at /zaken/api/v1/zaken/bb78146b-f4f3-49de-9769-76124c4333af/besluiten/11bf54bb-51b5-4f0e-8bd2-c3b0ed7fdd30
Cannot resolve keyword 'besluit' into field. Choices are: _besluittype, _besluittype_id, _besluittype_url, _zaak, _zaak_id, _zaak_url, _zaakbesluit_url, besluitinformatieobject, besluittype, bestuursorgaan, datum, id, identificatie, ingangsdatum, objectinformatieobject, publicatiedatum, toelichting, uiterlijke_reactiedatum, uuid, verantwoordelijke_organisatie, vervaldatum, vervalreden, verzenddatum, zaak, zaakbesluit

Request Method: DELETE

**To Reproduce**
1. Attach a decision to a case with a POST to '/zaken/{zaak_uuid}/besluiten'
2. Try to Delete a decision from a case with a DELETE to ' /zaken/{zaak_uuid}/besluiten/{uuid}'

**Expected behavior**
The decision should be removed from the case.

**Comment by sergei-maertens** [comment]
First, let me say that this indeed looks like a bug to be solved!

Second, I suspect you're building a consumer application (and not a besluiten API), which shouldn't be creating or deleting these resources, per https://zaken-api.vng.cloud/api/v1/schema/#operation/zaakbesluit_create and https://zaken-api.vng.cloud/api/v1/schema/#operation/zaakbesluit_destroy

To relate a besluit to a zaak, you should make a POST call to the Besluiten API with the zaak reference, and to unrelate it, you should make a PATCH or PUT request to the besluit resource in the Besluiten API.

Hope this helps!

**Comment by plaarakkers-trifork** [comment]
For the second part. I did indeed miss the note during the testing if notifications for this were sent.

This makes the case attribute in the besluiten API clearer. I didn't see the relation directly in the case so I thought that this call would also be needed.
