### ISSUE TITLE
Delete zaaktype does not accept documented accept headers and returns incorrect response type

### ISSUE THREAD

**Issue by plaarakkers-trifork** [open-zaak/open-zaak#577]
**Describe the bug**
According to the documentation when deleting a zaaktype the ok response is a 204 no content without a response schema. For all the error responses the response schema is aplication/problem+json. When creating a java client based on the swagger documentation this is the only acceptheader that is added for this call.

When a delete call for a zaaktype and possibly other resources is sent to open zaak an error response with unacceptable is returned because of the accept header. The response type also is aplication/json which does not corresponds to the documented schema.

When adding aplication/json to the accept headers the call is accepted.

**To Reproduce**
1. Perform a delete call for a zaaktype with only aplication/problem+json as an accept header:
` curl --location --request DELETE 'http://open-zaak.test.local:8001/catalogi/api/v1/zaaktypen/5d40c63b-d816-4ffb-bd46-5d731ef86d7faa' -v \
> > --header 'Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiIsImNsaWVudF9pZGVudGlmaWVyIjoiZGVtbyJ9.eyJpc3MiOiJkZW1vIiwiaWF0IjoxNTg4MDU3ODM5LCJjbGllbnRfaWQiOiJkZW1vIiwidXNlcl9pZCI6IiIsInVzZXJfcmVwcmVzZW50YXRpb24iOiIifQ.m6BLwJIkIVOHtDcWUc0OEZyT1CWW_yZR9_-hJfgRpIw' \
> > --header 'Accept: application/problem+json'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to open-zaak.test.local (127.0.0.1) port 8001 (#0)
> DELETE /catalogi/api/v1/zaaktypen/5d40c63b-d816-4ffb-bd46-5d731ef86d7faa HTTP/1.1
> Host: open-zaak.test.local:8001
> User-Agent: curl/7.58.0
> Accept: */*
> 
< HTTP/1.1 403 Forbidden
< Content-Type: application/json
< Allow: GET, PUT, PATCH, DELETE, HEAD, OPTIONS
< API-version: 1.0.0
< X-Frame-Options: DENY
< Content-Length: 303
< X-Content-Type-Options: nosniff
< X-XSS-Protection: 1; mode=block`

**Expected behavior**
Open zaak should not give an error based on the supplied accept headers that corresponds to the documentation and return the correct content type.

**Comment by sergei-maertens** [comment]
should be nothing more than subclassing the DRF-camelcase JSONRenderer/JSONParser and specifying the content type `application/problem+json`, and add the subclasses to the `REST_FRAMEWORK` settings.
