### ISSUE TITLE
publish zaaktype returns not documented error responses with unexpected type

### ISSUE THREAD

**Issue by plaarakkers-trifork** [open-zaak/open-zaak#578]
**Describe the bug**
According to the documentation when performing a publish action the only response is 201 created. This is also the case for publishing other resources.

However when I, for example, publish an unknown zaaktype the response is a 404 not found as I would expect. This is on of the responses that is not documented where I also  expect that the other default error responses are possible.

When receiving the error response the content type is also application/json and not application/problem+json as expected.

**To Reproduce**
1. Perform a publish for a not existing zaaktype.
`curl --location --request POST 'http://open-zaak.test.local:8001/catalogi/api/v1/zaaktypen/58ebb6f6-31ff-4625-b794-52bec5b946cs/publish' -v \
> --header 'Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiIsImNsaWVudF9pZGVudGlmaWVyIjoiZGVtbyJ9.eyJpc3MiOiJkZW1vIiwiaWF0IjoxNTg4MDYyNjgyLCJjbGllbnRfaWQiOiJkZW1vIiwidXNlcl9pZCI6IiIsInVzZXJfcmVwcmVzZW50YXRpb24iOiIifQ.19JLY8vAZ63m9ihnDCbKomgvHmf6tOVykBpucUMn00k' \
> --header 'Accept: application/json'
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to open-zaak.test.local (127.0.0.1) port 8001 (#0)
> POST /catalogi/api/v1/zaaktypen/58ebb6f6-31ff-4625-b794-52bec5b946cs/publish HTTP/1.1
> Host: open-zaak.test.local:8001
> User-Agent: curl/7.58.0
> Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiIsImNsaWVudF9pZGVudGlmaWVyIjoiZGVtbyJ9.eyJpc3MiOiJkZW1vIiwiaWF0IjoxNTg4MDYyNjgyLCJjbGllbnRfaWQiOiJkZW1vIiwidXNlcl9pZCI6IiIsInVzZXJfcmVwcmVzZW50YXRpb24iOiIifQ.19JLY8vAZ63m9ihnDCbKomgvHmf6tOVykBpucUMn00k
> Accept: application/json
> 
< HTTP/1.1 404 Not Found
< Content-Type: application/json
< Allow: POST, OPTIONS
< API-version: 1.0.0
< X-Frame-Options: DENY
< Content-Length: 209
< X-Content-Type-Options: nosniff
< X-XSS-Protection: 1; mode=block`

**Expected behavior**
The error responses for the publish method should be documented like the rest of the calls and the content type should be the expected application/problem+json.

**Comment by Hugo-ter-Doest** [comment]
Checken of dit een bug is van de standaard.

**Comment by plaarakkers-trifork** [comment]
Extra informatie over de teruggegeven responses. Met verdere testen blijkt dat de gedocumenteerde 201 response ook niet teruggegeven wordt. In werkelijkheid wordt er een 200 response teruggegeven waarbij de beschreven location header ook niet terugkomt.

Dit blijkt ook uit de test welke terug te vinden is bij het vng reference component:
`def test_publish_zaaktype(self):
        zaaktype = ZaakTypeFactory.create()
        besluittype = BesluitTypeFactory.create(concept=False)
        zaaktype.besluittypen.add(besluittype)
        ZaakInformatieobjectTypeFactory.create(
            zaaktype=zaaktype, informatieobjecttype__concept=False
        )
        zaaktype_url = get_operation_url("zaaktype_publish", uuid=zaaktype.uuid)
        response = self.client.post(zaaktype_url)
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        zaaktype.refresh_from_db()
        self.assertEqual(zaaktype.concept, False)`

Het lijkt er op dat dit geddelte van de documentatie een kopie is van de create.

**Comment by sergei-maertens** [comment]
Yep, there's some issues here because of the schema generation tooling. The same problem is also present in the upstream standard documentation, and it's correctly identified as a bug.

To fix:

* explicitly override the `@auto_schema(...)` stuff on the API detail action
* re-generate the API schema
* make a PR to upstream to fix this

The error content-type is tracked in #577 already.

**Comment by stevenbal** [comment]
related upstream issue: https://github.com/VNG-Realisatie/gemma-zaken/issues/1475

**Comment by sergei-maertens** [comment]
Fix is not okay yet, looks like I was too eager to accept and merge that.
