### ISSUE TITLE
As an Open Zaak maintainer, I want application-developers to find the standards documentation easily

### ISSUE THREAD

**Issue by sergei-maertens** [open-zaak/open-zaak#603]
... so I don't have to repeat myself and share the links to the documentation more often than I'd like :-)

**Description**

The API specs describe the API itself, but a textual description of run-time behaviour is also part of the standard. This documentation is not easily found, so it should be made much more prominent than it currently is.

Example target docs: https://vng-realisatie.github.io/gemma-zaken/standaard/zaken/index

**Comment by Hugo-ter-Doest** [comment]
Are the URL's to the standards documentation too long or obscure?

**Comment by joeribekker** [comment]
I think we currently point to the AOS, while we should point to the API-page in the documentation because the runtime behaviour documentation is there as well. If we point to the OAS, you easily miss the runtime behaviour.

**Comment by sergei-maertens** [comment]
Fixed via #753
