### ISSUE TITLE
As functioneel beheerder, I want to use Selectielijst 2020 when configuring Open Zaak zaaktypes 

### ISSUE THREAD

**Issue by JurjenBert** [open-zaak/open-zaak#606]
... so I can configure them correcty. 

On the website https://vng.nl/nieuws/selectielijst-2020-vastgesteld you can find the files containing the selectielijst. 
The link on that page to the excel file "selectielijst opsomming" seems the most useful.

**Description**
Describe the user story in more detail.

**Comment by sergei-maertens** [comment]
#691 added support for this :-)
