### ISSUE TITLE
Wie heeft welke rechten om merges door te voeren?

### ISSUE THREAD

**Issue by DeBAAT** [open-zaak/open-zaak#615]
Issue komt uit workshop 11-6-2020

**Comment by DeBAAT** [comment]
Issue komt uit workshop 11-6-2020

**Comment by Vivette** [comment]
Aanvullend daarop heb je ook de vraag: wie bepaalt/hoe wordt besloten welke oplossing/fix je accepteert met een merge conflict

**Comment by Hugo-ter-Doest** [comment]
At the moment product owner and developers can merge pull requests. When we install the committees we have to reconsider this.

**Comment by Hugo-ter-Doest** [comment]
> Aanvullend daarop heb je ook de vraag: wie bepaalt/hoe wordt besloten welke oplossing/fix je accepteert met een merge conflict

In the long term this has to be decided by the technical steering committee.
