### ISSUE TITLE
Definitie simple en super majority

### ISSUE THREAD

**Issue by Vivette** [open-zaak/open-zaak#616]
In de code of governance wordt gesproken over simple en super majority. Wat zijn hier de % die hier bij horen?

Issue komt uit workshop 11-6-2020

**Comment by Hugo-ter-Doest** [comment]
Has been defined.

**Comment by joeribekker** [comment]
Here: https://github.com/open-zaak/open-zaak-market-consultation/blob/develop/GOVERNANCE.md

Super majority = 2/3
Simple majority = 1/2
