### ISSUE TITLE
Wanneer ik openzaak draai heb ik een verbinding met internet nodig

### ISSUE THREAD

**Issue by EduardWitteveen** [open-zaak/open-zaak#621]
Wanneer ik openzaak lokaal installeer heb ik een internet verbinding nodig om het te laten werken.

Een internet verbinding naar:  https://selectielijst.openzaak.nl/ is nodig bij het aanmaken van een zaaktype
Een internet verbinding naar:  https://notificaties-api.vng.cloud/api/v1/ is nodig bij het aanmaken van een zaaktype

Tevens is er geen manier om dit uit te zetten

Dit maakt dat voor het lokaal draaien van openzaak, in een beveiligde omgeving, er firewall instellingen moeten worden gedaan.

**Comment by petercuret** [comment]
@EduardWitteveen Klopt, de logs worden momenteel overspoeld met tracebacks omdat de notification endpoint niet te bereiken. Je kunt de verbinding naar notificaties (https://notificaties-api.vng.cloud/api/v1/) instellen vanuit de admin omgeving, en die wijzen naar een endpoint op je localhost. 

Daarvoor moet je lokaal wel eerst een applicatie draaien, een consumer voor de notificaties die verstuurd worden. 
Vanuit de developer experience lijkt me dat niet bepaald laagdrempelig, omdat je dan ook gelijk die consumer moet draaien (b.v open-notificaties).

Het lijkt me handiger om de notificaties (vooraal voor lokale development) uit te kunnen zetten vanuit. Door bijvoorbeeld NOTIFICATIONS_DISABLED als environment variable vanuit je Docker compose mee te geven aan de open-zaak image.

**Comment by sergei-maertens** [comment]
> Het lijkt me handiger om de notificaties (vooraal voor lokale development) uit te kunnen zetten. Door bijvoorbeeld NOTIFICATIONS_DISABLED als environment variable vanuit je Docker compose mee te geven aan de open-zaak image.

De setting bestaat in ieder geval: https://github.com/open-zaak/open-zaak/blob/master/src/openzaak/conf/dev.py#L101 - we moeten hiervoor nog envvar support toevoegen.

**Comment by EduardWitteveen** [comment]
Was deze al geïmplementeerd?
Ik zie door de bomen(foutmeldingen) het bos niet meer,

**Comment by sergei-maertens** [comment]
Nee, dat is nog niet gebeurd.

**Comment by sergei-maertens** [comment]
When #1293 is merged, there will no longer be a network connection required to `raw.githubusercontent.com`. This concludes the implementation aspect for this ticket.

To summarize:

* Notifications: either disable notifications alltogether (not standard-compliant!) via `NOTIFICATIONS_DISABLED` envvar) or configure your Open Zaak instance to use a notifications API instance on your local network
* Selectielijst: it's recommended to use the public instance as it's managed by Maykin Media, however you can:
    * Deploy your own instance and consume it over your local network
    * Consider using NLX to limit your public internet exposure. Your service provider can look into exposing the selectielijst API on the NLX network :wink: 
* Open Zaak 1.8.0 will include the (VNG) API specs/assets from github in the docker image, so you don't need network calls for this.
