### ISSUE TITLE
Performance regression: /zaken/api/v1/zaakinformatieobjecten

### ISSUE THREAD

**Issue by sergei-maertens** [open-zaak/open-zaak#622]
**Describe the bug**

The endpoint to list ZaakInformatieobjecten for a given zaak is too slow. A Zaak URL with only a single related document takes about 1400ms to complete according to profiling done as part of Gemeente Utrecht. Hardware is definitely not the issue

**To Reproduce**
1. Create a zaak
2. Relate a number of documents
3. `GET /zaken/api/v1/zaakinformatieobjecten?zaak=<url of zaak>`
4. Observe the slow response times

**Expected behavior**

Fast response times. As it is, this endpoint currently performs worse than the `/zaken/api/v1/zaken` endpoint, which does far more exciting stuff.

**Comment by stevenbal** [comment]
When filtering on `Zaak` for the ZIO endpoint, `get_resource_for_path` is called for this `Zaak`, which causes all the prefetches on the `ZaakViewSet` queryset to be called as well, resulting in extra queries:
![Screenshot from 2020-07-10 14-18-14](https://user-images.githubusercontent.com/29249171/87153750-3f4cf300-c2b8-11ea-958c-6bf59064a0dd.png)

This, combined with a lot of Zaken with related objects like Statussen or Resultaten might be the cause of this performance issue

**Comment by sergei-maertens** [comment]
Closing this because the API-call monitoring implied Open Zaak was the culprit, but that's wrong - the same API call in Postman takes 50-200ms, while the application takes 1600-2000ms.

Long story short - we've dug up Wireshark and don't know the cause of the problem yet, but it doesn't look like it's Open Zaak application layer. So closing this.

**Comment by sergei-maertens** [comment]
FYI - the extra prefetch-queries there should be avoided, but it's not cripling right now.
