### ISSUE TITLE
Updating the one-line description in the repository

### ISSUE THREAD

**Issue by Ainali** [open-zaak/open-zaak#623]
**Is your feature request related to a problem? Please describe.**
The oneliner in GitHub right  now is "API's voor Zaakgericht werken" which is in Dutch and also not very descriptive.

**Describe the solution you'd like**
How about basing it on the opening in the [documentation](https://open-zaak.readthedocs.io/en/latest/introduction/index.html)?
"Open Zaak is a modern, open-source data- and services-layer to enable zaakgericht werken, a Dutch approach to case management."

**Describe alternatives you've considered**
The documentation uses "alternative" instead of "approach", but I believe approach is better because it actually is case management, not an alternative to it.

**Comment by Hugo-ter-Doest** [comment]
Which oneliner do you mean?

**Comment by Ainali** [comment]
The one that is in the top on this page: https://github.com/open-zaak/open-zaak

**Comment by Hugo-ter-Doest** [comment]
@joeribekker ik kan de tekst onder "About" niet zelf aanpassen. Zou jij deze kunnen wijzigen in "Open Zaak is a modern, open-source data- and services-layer to enable zaakgericht werken, a Dutch approach to case management." 

Thanks!

**Comment by joeribekker** [comment]
@Hugo-ter-Doest done. Close maar indien tevreden :)

**Comment by Hugo-ter-Doest** [comment]
Thanks!
