### ISSUE TITLE
As functioneel beheerder zaaksysteem SWF, I want aanpassingen in de look van het zaaksysteem

### ISSUE THREAD

**Issue by SWFTessavdLaan** [open-zaak/open-zaak#627]
Op dit moment staat er heel veel informatie bij een zaak, in open zaak. En is het veel doorklikken. 

Mijn wens is om hier meer overzicht in de creëren, zodat het in één blik/in één scherm zichtbaar is: 
- wat het zaakid is
- wat voor zaaktype het is (incl. zaaktypecode)
- de omschrijving
- de status en het resultaat van de zaak
- de aanvrager van de zaak
- de huidige behandelaar van de zaak (daaronder evt de geschiedenis van eerdere behandelaren). 
- de startdatum
- de einddatum
- welke documenten er gekoppeld zijn, documentid's (en deze documenten daarbij direct kunnen openen)
- de informatie van de documenten, zoals het documentid, het documenttype en de titel.

**Comment by joeribekker** [comment]
Heel begrijpelijke punten. Dit deel van de beheerinterface stond niet hoog op de prio lijst voor versie 1 van Open Zaak. Naarmate er meer mensen gebruik van gaan maken zal deze functionaliteit steeds belangrijker worden.

Wel is dit echt een beheerinterface, vooral voor handmatig ingrijpen/controleren, dat meer uitzondering dan standaard moet zijn. Ik begrijp dat - bij gebrek aan een zaakafhandelcomponent dat met de ZGW API's werkt - de Open Zaak beheerinterface de enige/makkelijkste manier is om data "snel" te bekijken. En dus de wens om deze interface beter te maken.

Aan @Hugo-ter-Doest om deze feature te beoordelen.

**Comment by sergei-maertens** [comment]
Relates to #855, #810, 805. Closing this as it would be the domain of a dedicated application.
