### ISSUE TITLE
As a fucntioneel beheerder, I want to be able to set 'Doorlooptijd behandeling' to 'not defined' when creating a zaaktype

### ISSUE THREAD

**Issue by MichelleDautzenberg** [open-zaak/open-zaak#660]
Not all zaaktypen have a 'Doorlooptijd' set by legislation. 

Such as 'Bestuurlijke besluitvorming', 'Beleid opstellen'..

**Comment by sergei-maertens** [comment]
Not that I don't believe you, but can you give a reference to said legislation?

The information model that the standard was based on (see https://www.gemmaonline.nl/index.php/Imztc_2.1/doc/attribuutsoort/zaaktype.doorlooptijd_behandeling) also does not accomodate empty/undefined values.

Either way, this is an upstream issue for the Catalogi API standard in https://github.comVNG-Realisatie/gemma-zaken

**Comment by MichelleDautzenberg** [comment]
GEMMA says: Doorlooptijd = De periode waarbinnen volgens wet- en regelgeving een ZAAK van het ZAAKTYPE afgerond dient te zijn.

My point is there is no 'wet- en regelgeving' to determine the duration of some processes (in advance). 
Normally we would fill in 999 days in these situations, but that doesn't look very nice in a front-end application. 

But you are right, wrong site for this discussion :)
