### ISSUE TITLE
Command register_channel needs to create all channels

### ISSUE THREAD

**Issue by joeribekker** [open-zaak/open-zaak#668]
**Is your feature request related to a problem? Please describe.**
This command is inherited from vng_api_common but not suited for Open Zaak really, since multiple components are combined.

**Describe the solution you'd like**
register_channels should just register all needed channels.

**Describe alternatives you've considered**
calling the command register_channel for all needed channels.

**Comment by stevenbal** [comment]
This was implemented as part of the changes to notifications (functionality is being moved from `vng-api-common` to `notifications-api-common` (https://github.com/maykinmedia/notifications-api-common/commit/15ffb07d447bd31784b37b4903c8affcb87a06c5)

**Comment by sergei-maertens** [comment]
Fixed via #1208
