### ISSUE TITLE
Email address for security issues

### ISSUE THREAD

**Issue by Ainali** [open-zaak/open-zaak#670]
**Is your feature request related to a problem? Please describe.**
One requirement in [Welcome contributions](https://github.com/open-zaak/open-zaak/blob/master/docs/introduction/open-source/public_code.md#welcome-contributions) is 

> The codebase MUST include an email address for security issues and responsible disclosure.

**Describe the solution you'd like**
I suggest that we at the Foundation for Public Code set up a **private** mailing list for this using [Mailman](https://lists.publiccode.net/mailman/postorius/lists/), possibly at openzaak-security@lists.publiccode.net (and create a better alias for it later). I could add @joeribekker, @sergei-maertens and @ericherman on it for now, and put the question of possible update to the Technical steering team after they been elected at the first community call in September.

Any thoughts on this, or should I set this up?

**Comment by joeribekker** [comment]
We now have this: https://open-zaak.readthedocs.io/en/stable/support/index.html (see bottom).

**Comment by ericherman** [comment]
Okay good! Then perhaps we should reference this in the README, and then adjust the public_code.md as well.

**Comment by Ainali** [comment]
Yeah, README or perhaps CONTRIBUTING in the Reporting bugs section would be helpful. And I agree that this is enough to meet the requirement.

**Comment by Ainali** [comment]
> Yeah, README or perhaps CONTRIBUTING in the Reporting bugs section would be helpful. And I agree that this is enough to meet the requirement.

It will also check one of the boxes in #673
