### ISSUE TITLE
stacktrace en 500 error bij aanmaken bestaande eigenschap

### ISSUE THREAD

**Issue by plaarakkers-trifork** [open-zaak/open-zaak#687]
**Describe the bug**
Het aanmaken van een eigenschap met dezelfde naam en zaaktype als een bestaande eigenschap resulteert in een stacktrace en 500 error.

**To Reproduce**
1. Maak een geldige eigenschap aan.
2. Probeer hierna een eigenschap aan te maken dezelfde naam en zaaktype.
3. Dit resulteerd in een stacktrace (vanwege debugging) en een 500 melding vanwege een db key constraint:
`IntegrityError at /catalogi/api/v1/eigenschappen
duplicate key value violates unique constraint "catalogi_eigenschap_zaaktype_id_eigenschapnaam_2c2773fe_uniq"
DETAIL:  Key (zaaktype_id, eigenschapnaam)=(1, test1) already exists.`

**Expected behavior**
Ik verwacht een duidelijke error melding en geen stacktrace of 500 error.

**Comment by annashamray** [comment]
I can't reproduce it with Open Zaak 1.8.2 
@plaarakkers-trifork does the bug still appear?

**Comment by joeribekker** [comment]
PM decision: Since this reported over 3 years ago and Anna retested this, I assume this is fixed and will close the issue. If it's still relevant, feel free to re-open.
