### ISSUE TITLE
As developer, I want the new Selectielijst year-enhancement from VNG

### ISSUE THREAD

**Issue by joeribekker** [open-zaak/open-zaak#690]
... so I can import 2020 and use it for new zaaktypes.

**Description**

* [x] Update https://github.com/open-zaak/vng-selectielijst to include changes described here: https://github.com/VNG-Realisatie/gemma-zaken/issues/1667
* [x] Release new version of vng-selectielijst to Docker Hub
* [x] Deploy new version
* [x] Import 2020 selectielijst on deployed instance

**Comment by stevenbal** [comment]
PR: https://github.com/open-zaak/vng-selectielijst/pull/6
