### ISSUE TITLE
The Selectielijst "jaar" selection does not trigger a reload of the Processtypen

### ISSUE THREAD

**Issue by joeribekker** [open-zaak/open-zaak#695]
**Describe the bug**
As mentioned in #691, it's a bit annoying that the processtypen do not reload on the fly depending on the selectielijst year selection when creating/updating a zaaktype.

**Expected behavior**
Indicate clearly that zaaktype must be saved with selectielijst_procestype_jaar to reload the procestypen for that year

**Comment by felixfaassen** [comment]
Looks resolved merged in #691

**Comment by joeribekker** [comment]
But, it's not :)

The procestypen only refresh upon save&continue. It should be a JS thingy that does it as soon as the selectielijst is changed.

**Comment by sergei-maertens** [comment]
#1164 implements this
