### ISSUE TITLE
As functioneel beheerder zaaksysteem, I want to open documenten bij de zaak

### ISSUE THREAD

**Issue by SWFTessavdLaan** [open-zaak/open-zaak#699]
Het openen van documenten is niet mogelijk via de zaak (Gegevens - Zaken). 
Dus wanneer ik naar de zaak ga, naar zaakinformatieobjecten/documenten en dan 'wijzigen' dan kom ik bij de documentgegevens. 
Klikken op nummer/ID informatieobject en bij 'inhoud' kan ik het bestaande/huidige document openen via de url. 
Via deze route krijg ik een 'not found'. 

Wanneer ik het document rechtstreeks benader via Gegevens - Documenten, ik klik op hetzelfde ID, dan zie ik bij inhoud een andere url en kan ik het document netjes openen. 

Toch wil ik een document graag openen via de ingang van de zaak (gegevens - zaken).

**Comment by sergei-maertens** [comment]
See also #855, #810 and #805.
