### ISSUE TITLE
As developer, I want OpenZaak to be a Docker container (or multiple)

### ISSUE THREAD

**Issue by joeribekker** [open-zaak/open-zaak#7]
... so I can run OpenZaak easily in a server and/or Kubernetes cluster.

**Description**
OpenZaak needs to be able to run as a Docker instance. So, at the minimum we need to have a `Dockerfile` and `docker-compose.yaml`.

**Comment by sergei-maertens** [comment]
See also #57 for automatic building/publishing of these image(s)

**Comment by joeribekker** [comment]
See: https://hub.docker.com/r/openzaak/open-zaak/tags
