### ISSUE TITLE
Creating Zaaktype-Informatieobjecttype relation does not add Informatieobjecttype to Zaaktype.informatieobjecttypen

### ISSUE THREAD

**Issue by stevenbal** [open-zaak/open-zaak#70]
**Describe the bug**
When I create a Zaaktype-Informatieobjecttype relation, the Informatieobjecttype is not added  to the Zaaktype.informatieobjecttypen, which means that I am not able to create a ZaakInformatieObject with this Zaaktype and Informatieobjecttype.

**Comment by annashamray** [comment]
@stevenbal I think it could be the problem with non-published resources
Have you published `zaaktype` and `informatieobjecttype` before creating `zaakinformatieobjecttype`? 
What it the value of their `concept` fields?

**Comment by annashamray** [comment]
@stevenbal Can you please provide input data? I can't reproduce the error

**Comment by stevenbal** [comment]
In my tests I hadn't yet published the `Zaaktype` and `Informatieobjecttype`, so that's why it failed. When I do publish them, I can create a ZIO without problems. This does mean however that in the reference implementation it is possible to create resources in for instance ZRC with types that are still a concept.
