### ISSUE TITLE
Optie om "zwevende" documenten op te vragen

### ISSUE THREAD

**Issue by nloncaric** [open-zaak/open-zaak#706]
op dit moment kun je losse documenten in het systeem plaatsen zonder een zaak en zonder daar een melding van te krijgen. Het zou mogelijk moeten zijn om deze zwevende documenten te kunnen opvragen zodat we ze dan kunnen koppelen aan een zaak.

**Comment by hanspluimers** [comment]
Is het niet veel verstandiger om te voorkomen dat er 'losse' documenten kunnen worden toegevoegd?  Er zijn namelijk meerdere usecases denkbaar waarbij documenten geen relatie (meer) hebben bij een zaak en eigenlijk moet je dat niet willen. Dus het aanscherpen van de voorwaarden voor het toevoegen van een document lijkt mij een betere oplossing dan het toevoegen van een functie om naar 'losse' documenten te gaan zoeken of die te signaleren.

**Comment by joeribekker** [comment]
De Documenten API is een zelfstandig component. Je kan dus documenten aanmaken, klaar.

@nloncaric noemt dit dan zwevende documenten. Je kan de documenten ook hangen aan een zaak of besluit waardoor ze niet "zweven". Ik begrijp dat, met oog op het verleden met Zaak- en Documentservices, het vooral ging om "Zaakdocumenten". Dat is echter hier niet het geval.

> Het zou mogelijk moeten zijn om deze zwevende documenten te kunnen opvragen zodat we ze dan kunnen koppelen aan een zaak.

Volgens mij is dit al mogelijk. Gewoon `GET /enkelvoudiginformatieobjecten` geeft alle documenten terug, of deze nu aan een zaak zitten of niet. Wellicht is de vraag om beter te kunnen filteren op documenten zonder relatie. Deze vraag zou echter bij bij VNG moete liggen die over de Documenten API specificatie gaat.

**Comment by hanspluimers** [comment]
> De Documenten API is een zelfstandig component. Je kan dus documenten aanmaken, klaar.

Dat is niet helemaal waar want je mag ook geen zaak aanmaken zonder zaaktype dus het is een kwestie van afspraken maken en vastleggen.

Ik ben van mening dat het zeer ongewenst is om een document aan te kunnen maken dat geen relatie heeft met een zaak. We hebben het hier over ZGW-api's dus de uitgangspunten van zaakgericht werken gelden ook voor de documenten-api.

Ik zie geen enkele functionele noodzaak om het aanmaken van een document (zonder relatie met een zaak) te ondersteunen. Als we dat wel doen dan krijg je allerlei problemen rondom het archiveren en vernietigen van documenten. 

Ik begrijp dat er vanuit het verleden behoefte bestaat aan het 'zevend' (= zonder relatie) kunnen opslaan van documenten maar dat lijkt me geen toekomstgerichte oplossing.

Ik weet alleen niet wie de principes van het zaakgericht werken nu gaat bewaken want dit is een bekend discussiepunt tussen de 'puristen' van het documentgericht werken en het zaakgericht werken.

**Comment by joeribekker** [comment]
> Dat is niet helemaal waar want je mag ook geen zaak aanmaken zonder zaaktype dus het is een kwestie van afspraken maken en vastleggen.

Ik vermoed dat je de relatie legt van zaak-zaaktype naar document-documenttype. Het klopt dat een document een documenttype nodig heeft, die onderdeel is van de Catalogi API. De Documenten API heeft op dit moment dus een Catalogi API nodig. Dit is een relatie waarvan ik hoop dat die in een volgende versie van de API verdwijnt.

> Ik ben van mening dat het zeer ongewenst is om een document aan te kunnen maken dat geen relatie heeft met een zaak. We hebben het hier over ZGW-api's dus de uitgangspunten van zaakgericht werken gelden ook voor de documenten-api.

ZGW-api's bestaan eigenlijk niet. Dit is een werk/project naam bij VNG waaronder ze zijn ontworpen. Net zoiets als de HaalCentraal APIs, terwijl de BRP niet zo veel met de BRK te maken heeft.

In mijn ogen is het niet ongewenst maar we houden ons gewoon aan de standaard. Wellicht spreken we niet over hetzelfde. Ik vind echt zwevende documenten ook niet handig maar je referereert expliciet naar een zaak relatie. Documenten in de Documenten API kunnen (en zouden moeten) een relatie hebben met iets anders dan een Zaak, zoals een raadsbesluit, een melding, verzoek, etc. Volgens mij licht dit ook in de visie van de Documenten API.

> Ik weet alleen niet wie de principes van het zaakgericht werken nu gaat bewaken want dit is een bekend discussiepunt tussen de 'puristen' van het documentgericht werken en het zaakgericht werken.

Het Open Zaak team in ieder geval niet. De juiste plek lijkt mij https://github.com/VNG-Realisatie/

Zonder inhoudelijk de discussie verder aan te gaan, denk ik dat dit ticket bij VNG hoort te liggen. Ik zal er naar verwijzen.

**Comment by sergei-maertens** [comment]
Closing this since it's an upstream issue which Joeri was so kind to create :-) We do want the functionality, but the standard should facilitate that.
