### ISSUE TITLE
Koppeling/import mogelijkheid met Sdu i-Navigator

### ISSUE THREAD

**Issue by nloncaric** [open-zaak/open-zaak#707]
Het moet mogelijk zijn om de export van I navigator in te lezen in het systeem Open zaken. 

Op dit moment wordt hier aan gewerkt.

**Comment by EduardWitteveen** [comment]
Ik heb een python-script dat de xml-export-bestanden vanuit inavigator inleest en op basis daarvan de zgw-apis aanroept.
Script zou ook reentrant moeten zijn.
Dit gebruiken wij voor open zaakbrug om zo bestaande zaaktypes te kunnen migreren

**Comment by joeribekker** [comment]
Yes, wij hebben hier nu ook een script voor.
Inlezen van XML bestand en Zaaktypes aanmaken via de API.

Wist niet dat jij dit had Eduard, waar staat dat? :)

**Comment by EduardWitteveen** [comment]
Contact gehad met @joeribekker misschien zou dit meer een tool moeten zijn die wordt gebruikt in combi met https://github.com/VNG-Realisatie/gemma-zaken ?

**Comment by joeribekker** [comment]
Voor dit ticket verwijs ik graag naar: https://github.com/maykinmedia/catalogi-importer
