### ISSUE TITLE
Redoc seems to fail to render due in some cases

### ISSUE THREAD

**Issue by joeribekker** [open-zaak/open-zaak#708]
**Describe the bug**
This prevents the schema from showing up. The JSON view just works, but the Redoc view fails on JS level.

An error similar to this one pops up:

https://github.com/Redocly/redoc/issues/764#issuecomment-455129004

**Comment by sergei-maertens** [comment]
@joeribekker does this problem still persist? Do you have instructions on how to reproduce this, otherwise we'll close this.

**Comment by sergei-maertens** [comment]
Per the above comment
