### ISSUE TITLE
Deleting a catalogue (with concept zaaktypes) when permissions have been defined for "all current and future zaaktypes" breaks the zaken list endpoint

### ISSUE THREAD

**Issue by sergei-maertens** [open-zaak/open-zaak#713]
**Describe the bug**

The application/authorization machinery allows applications to receive permissions for all current and future zaaktypen (or IOT/BT). This installs an `AutorisatieSpec`.

If you then create zaaktypen in a catalogus without publishing them, an Autorisatie is created. Deleting the zaaktype again does not delete the attached Autorisatie, which subsequently is used for permission checks/server-side filtering of Zaken from that zaaktype.

Zaaktypes that are deleted, should also delete related Autorisatie objects.

**To Reproduce**
1. Create an application with authorizations `zaken:lezen` on all current and future zaaktypes
2. Create a catalogus with a zaaktype - unpublished
3. Delete the zaaktype
4. Make an API call with the credentials of the created application to `/zaken/api/v1/zaken`
5. Observe a server error related to django-loose-fk

**Expected behavior**

The API should not return a server error, but appropriately filtered data.

**Comment by sergei-maertens** [comment]
Temporary workaround code to clean up (untested in this exact form, applied in a similar form):

```py
from urllib.parse import urlparse

from django.apps import apps
from django.core.exceptions import ObjectDoesNotExist

from django_loose_fk.loaders import BaseLoader
from vng_api_common.utils import get_resource_for_path


Autorisatie = apps.get_model("authorizations", "Autorisatie")
is_local_url = BaseLoader().is_local_url


def delete_invalid_autorisaties(attr: str):
    qs = Autorisatie.objects.exclude(**{attr: ""})
    for obj in qs:
        url_ref = getattr(obj, attr)
        if not is_local_url(url_ref):
            continue

        parsed = urlparse(url_ref)

        try:
            get_resource_for_path(parsed.path)
        except ObjectDoesNotExist:
            obj.delete()


delete_invalid_autorisaties("zaaktype")
delete_invalid_autorisaties("informatieobjecttype")
delete_invalid_autorisaties("besluittype")

```

**Comment by SilviaAmAm** [comment]
I also noticed that in the Autorisatie.sync() function there is this line (https://github.com/open-zaak/open-zaak/blob/master/src/openzaak/components/autorisaties/models.py#L129) which I think is missing a `.delete()` at the end? Not sure if it should be fixed as part of this issue or a new one?

**Comment by sergei-maertens** [comment]
Good catch! You can fix it as part of this issue, and please write a regression test
