### ISSUE TITLE
Support of Postgresql 11

### ISSUE THREAD

**Issue by alextreme** [open-zaak/open-zaak#716]
**Is your feature request related to a problem? Please describe.**

Currently OpenZaak is tested against Postgresql 10. Although still supported, our default version of Postgres at Maykin is linked to the current version in Debian stable, which is Postgresql 11 ( https://packages.debian.org/buster/postgresql ). This ensures that we don't have to make use of the Postgres-supplied Debian packages.

**Describe the solution you'd like**

I'd like to see OpenZaak automatically tested versus Postgresql 11 and ensure that current/future installations are at PG 11.

**Describe alternatives you've considered**

The alternative is to conceed that OpenZaak only runs on a PG database older than Debian stable. Which means you will have to suffer my endless taunting.

No in practice running on PG 10 is not a problem, it will be supported for the forseeable future and the difference between 10 and 11 is minimal. So this is mostly a matter of consistency and a way of ensuring OpenZaak doesn't fall behind wrt dependancies.

**Comment by sergei-maertens** [comment]
Should indeed be added to the build matrix, I'll make a mental note of it for the technical roadmap.

Note that the default [`docker-compose.yml`](https://github.com/open-zaak/open-zaak/blob/master/docker-compose.yml#L6) makes use of the latest PG version. On my dev machine I also run latest PG (12), so it's 100% intended to work on PG 10, 11 and 12.

I'm not sure, but the Travis pin on PG 10 might be related to the fact that 11 wasn't available yet on Travis for testing.

**Comment by alextreme** [comment]
Thanks @sergei-maertens !
