### ISSUE TITLE
Update documentation to remove mentions of vars/secrets.yml

### ISSUE THREAD

**Issue by Bartvaderkin** [open-zaak/open-zaak#717]
The single-server installation readme mentions a `vars/secrets.yml.example` but it is not present in the repos.

https://github.com/open-zaak/open-zaak/blob/master/deployment/single-server/README.md

**Comment by sergei-maertens** [comment]
I think the readme should be replaced with links to the official documentation: https://open-zaak.readthedocs.io/en/stable/installation/deployment/single_server.html#initial-steps

**Comment by Bartvaderkin** [comment]
After some discussion about missing variables Sergei noted the secret.yml approach isn't actually used anymore and the documentation should be updated.

(note: right now secrets.yml is ignored and so you could deploy with default values)
