### ISSUE TITLE
As functioneel beheerder I would like to get a warning when publishing a new Zaaktype, when I didn't create more than one Statustype

### ISSUE THREAD

**Issue by MichelleDautzenberg** [open-zaak/open-zaak#729]
I'm always frustrated when I get an error when creating a Zaak. But some situations can be prevented.

For instance, I can publish a Zaaktype with only one Statustype. But that leads to an error like the one below.

![afbeelding](https://user-images.githubusercontent.com/48316239/94795168-4712c400-03dd-11eb-8e92-297de7b2adcc.png)

It would help me to get a warning when publishing the Zaaktype that it needs more than one Statustype.

**Comment by sergei-maertens** [comment]
Open Zaak gained a feature flag a while ago to allow creating cases (and documents/besluiten) from unpublished case types (and document/besluittypes). So you can keep editing things and test it out. You can find this here: https://openzaak.utrechtproeftuin.nl/admin/config/featureflags/

**Comment by MichelleDautzenberg** [comment]
I can't open the link (403 error), I am logged in...

**Comment by sergei-maertens** [comment]
Fixed via #1179
