### ISSUE TITLE
RolType.omschrijvingGeneriek is not lowercased

### ISSUE THREAD

**Issue by sergei-maertens** [open-zaak/open-zaak#735]
**Describe the bug**

I'm seeing records in Utrecht where `RolType.omschrijving_generiek` is not a lowercased value, but the codebase does correctly set the choices. I suspect that creating a new version of a zaaktype is the cause, because both the admin and API validate the correct choices value.

It looks like something is picking the label instead of the value from the choices.

**To Reproduce**
Steps to reproduce the behavior: haven't had the time to reproduce yet.

**Expected behavior**

The values in this field should _never_ not be lowercased.

**Comment by SilviaAmAm** [comment]
I have been trying to reproduce this issue in the following ways:

1. Create a `RolType` through the admin.
2. Create a `RolType` through a POST request to `http://127.0.0.1:8123/catalogi/api/v1/roltypen`
3. Creating a `RolType` when creating a new zaaktype in the Admin
4. Creating a new version of a zaaktype with a related `RolType`
5. Importing a `RolType` using the `import` management command on a zip file containing a `roltype.json` file with the following data:
 `[{"url": "http://example.com/catalogi/api/v1/roltypen/bbbc7d7f-7958-4107-ba19-3624d4f1ef7b", "zaaktype": "http://example.com/catalogi/api/v1/zaaktypen/b95c1626-5178-4780-b5c0-9210d82ec078", "omschrijving": "OMSCHRIJVING!", "omschrijving_generiek": "Adviseur"}]`

In cases 1 and 3, the `omschrijving_generiek` is chosen from the dropdown and have the correct lower case value. In case 2 and 5 a validation error is raised. In case 4, the `omschrijving_generiek` is  also copied as a lower case string.

**Comment by sergei-maertens** [comment]
Okay, possibly this is because of stale data then that wasn't used yet which only showed up now. Closing it, and if it turns out to still happen, I'll reopen.
