### ISSUE TITLE
The command register_kanaal does not work in In Open Notificaties

### ISSUE THREAD

**Issue by joeribekker** [open-zaak/open-zaak#740]
**Describe the bug**
`register_kanaal` does not work and complains about the Sites-framework in a default Docker setup. This can be because of the Site.objects.get_current(), but the default site seemed configured.

**To Reproduce**
1. Run a clean ON Docker-Compose
2. `src/manage.py` register_kanaal --help

**Expected behavior**
Register kanaal works or gives a proper error message.

**Comment by sergei-maertens** [comment]
`register_kanaal` is something that must be run from the providing API, not from Open Notificaties. Specifically, Open Zaak is the one that should run this command.

**Comment by joeribekker** [comment]
Ok ok, I added #743 instead.
