### ISSUE TITLE
Statics don't show correctly on a default Open Notificaties docker

### ISSUE THREAD

**Issue by joeribekker** [open-zaak/open-zaak#741]
**Describe the bug**
Seems the URL path is resolved to //static or so. This is caused by SUB_PATH in Docker-compose. If you remove it, it works fine.
However, it does work in Open Zaak with that variable and the value that is also in ON.

**To Reproduce**
1. Start clean ON docker compose
2. Go to /admin/

**Expected behavior**
Layout presents itself as it should

**Comment by sergei-maertens** [comment]
Check if this is still an issue

**Comment by sergei-maertens** [comment]
It was indeed still a problem, and it is for Open Zaak as well. Patch coming in soon.
