### ISSUE TITLE
As user, I want put a case on hold (opschorten)

### ISSUE THREAD

**Issue by TjerkVaags** [open-zaak/open-zaak#747]
So it is possible to put a case on hold (opschorten) by using the PUT /zaken API. But in the backend it doesn't do anything. 

For example. When an assignee of a case misses some documents from the initiator, it must be possible for the assignee to put the case on hold. What needs to be done next is that Open Zaak extends the scheduled enddate (einddatumGepland) for each day until the "On Hold" is lifted. 

I have tested the on hold option, but I do not anything happening in Open Zaak. Am I missing information to execute this action in my usercase?

**Comment by sergei-maertens** [comment]
It's correct that the behaviour of setting this flag is not described and as such nothing happens now. The desired behaviour seems appropriate, but we'll also have to bring this in to the upstream standard.
