### ISSUE TITLE
Request product steering team membership on behalf of Tiltshift

### ISSUE THREAD

**Issue by jgroenen** [open-zaak/open-zaak#748]
Tiltshift is a software design company for public sector organizations. We work on multiple projects that use OpenZaak as (one of the) backend(s). I would like to join the openzaak product steering team calls.

**Comment by joeribekker** [comment]
Hi Johan, apologies for not picking this up earlier. We haven't got a smoothlined process yet to get new members invited for these meetings. I'll be in touch on Slack to get your email.
