### ISSUE TITLE
Als gemeente wil ik dat een register registreert (en dus niet valideert) 

### ISSUE THREAD

**Issue by erikdelepper** [open-zaak/open-zaak#758]
Het valt op dat de openzaak API’s op verschillende punten gegevens valideren (tegen bijvoorbeeld ook zichzelf). Dit is vanuit een architectureel oogpunt onwenselijk. Registratie API’s op laag 1 en 2 dienen verschoont te zijn van business logica. De grens hiervoor ligt wat ons betreft  binnen de OAS types.
Het register kan zelf wel controleren of een string een string is, lengte’s kloppen etc. Een mooi bijvoorbeeld is emailadres. of een emailadres technisch valide is (het moet een @ bevatten en na de @ moet minimaal één punt voorkomen en dat mag niet het laatste karakter zijn) valt binnen de controle van het register. Of het emailadres ook daadwerkelijk bestaat, valt daar buiten.. Binnen open zaak lijkt dit wel te gebeuren; zo lijkt een object te worden gecontroleerd op beschikbaarheid, maar lijken zaken ook inhoudelijk te worden getoetst aan het zaaktype. Het is echter de vraag of het zaakregistratiecomponent, waarin het zaaktype van de zaak is vastgelegd, toegang moet hebben tot het zaaktyperegistratiecomponent. Ik zou zeggen dat dat geen randvoorwaarde is. Dataconsistentie tussen verschillende registers moet je dus niet in de registers of de API's regelen, maar in de businesslaag of eventueel in een convenience api. 

Vanuit een gebruiksoogpunt begrijpen we echter wel de behoefte aan dergelijke validatieystematiek, maar die zouden dan moeten worden ondergebracht in een convenience API de je als gemeente/applicatie wel of niet gebruikt.

**Comment by Hugo-ter-Doest** [comment]
OpenZaak volgt de standaard. Als we willen dat er niet gevalideerd wordt moet dat in de standaard worden aangepast. Ik stel voor dat je daar een user story inschiet.

**Comment by erikdelepper** [comment]
Ik heb dit niet kunnen terugvinden in de standaard. Kun je mij aangeven waar dat dan staat? Dan zal ik daar een issue aanmaken en  deze hier sluiten.

**Comment by Hugo-ter-Doest** [comment]
Bijvoorbeeld hier: https://vng-realisatie.github.io/gemma-zaken/standaard/zaken/index#zrc-001

Maar er zijn er meer.

**Comment by hanspluimers** [comment]
In de specificaties van de zaken-api (https://zaken-api.vng.cloud/api/v1/schema/#operation/zaakinformatieobject_list) staat dat er bepaalde validaties uitgevoerd moeten worden voordat een toevoeging of wijziging mag worden opgeslagen.  Ik zie dat het wel beschreven is voor zaakinformatieobjecten (=documenten) maar niet voor zaakobjecten.

Het lijkt mij echter zeer gewenst dat de component die de opslag van  informatie verzorgt controleert of de opgeslagen informatie correct is (dus de geldigheid/bereikbaarheid van een URL of URI controleren lijkt mij een taak van de opslagcomponent.  Dus controle/validatie van de technische juistheid lijkt mij een taak van een API. 

Er staan echter ook inhoudelijke controles (waarde moet voorkomen in vastgestelde lijst) en dan wordt het wat lastiger. Want om dit actie uit te kunnen voeren moet een opslag-api dan vaak een zaaktype-api of catalogus-api bevragen.

Als we dit echter niet goed gaan regelen dan is niemand verantwoordelijk voor de kwaliteit van de data want laag 1 en 2 kunnen aangestuurd worden vanuit verschillende componenten (van verschillende organisaties die door verschillende ontwikkelteams gemaakt zijn).  Dus de kernvraag is wie bewaakt de technische en functionele kwaliteit/juistheid van de data die wordt opgeslagen binnen 1 opslagcomponent/api?

**Comment by Hugo-ter-Doest** [comment]
Dit is een hele goede discussie, en die moet gevoerd worden bij de standaard. De argumentatie die @hanspluimers geeft heeft ons er destijds toe gebracht de validaties op te nemen. Graag wil ik het gesprek voortzetten bij https://github.com/VNG-Realisatie/gemma-zaken

**Comment by sergei-maertens** [comment]
Ook nog aanvullend perspectief: client-developers willen ook garanties. Eisen die beschreven worden maar niet technisch afgedwongen leiden tot dialecten en inconsistenties, en het is dan aan de client-developers om dat rommeltje op te ruimen. Een register moet ook data-integriteit borgen tot zover dit redelijk haalbaar is, en dat is de insteek van de standaard.

**Comment by sergei-maertens** [comment]
Closing this because of the `wontfix` label. If the upstream standard changes, we can revisit.
