### ISSUE TITLE
Multiple enkelvoudiginformatieobject can have the same identificatie for the same organisation

### ISSUE THREAD

**Issue by EduardWitteveen** [open-zaak/open-zaak#768]
**Describe the bug**
Multiple enkelvoudiginformatieobject can have the same identificatie for the same organisation.
Documents should have an unique identifier, and this is nog checked by the system.

**To Reproduce**
1. Create a enkelvoudiginformatieobject with identificate 12345
2. Create a enkelvoudiginformatieobject with identificate 12345

**Expected behavior**
The expected behavour would be that i would get the following error from OpenZaak. 
Something like the error for zaak:
```
{
"type":"https://fieldlab.westeurope.cloudapp.azure.com/ref/fouten/ValidationError/",
"code":"invalid",
"title":"Invalid input.",
"status":400,"detail":"",
"instance":"urn:uuid:252dde99-ba35-4ce3-b7c7-c8907d34ce5a",
"invalidParams":[{
"name":"identificatie",
"code":"identificatie-niet-uniek",
"reason":"Deze identificatie bestaat al voor deze bronorganisatie"
}
```

**Comment by SilviaAmAm** [comment]
This works as intended when Alfresco is used as the DMS. So it would be good to have more information about how Corsa's behaviour differs :slightly_smiling_face:

**Comment by EduardWitteveen** [comment]
This happens on the default installation, not the installation with CMIS

**Comment by joeribekker** [comment]
Good find Eduard. I was pretty sure this was covered by a database constraint but it appears we accidentally overruled this constraint by defining another constraint! Easy to overlook in the framework we use but [documented ](https://docs.djangoproject.com/en/2.2/topics/db/models/#meta-inheritance) :)

@SilviaAmAm We should add a management command to detect duplicates. This command can then be used if a database migration fails. We can do something like this:

```
$ manage.py detect_duplicate_eio
Checking 300 records...
Found 2 duplicate records.

1) Show duplicate records.
2) Delete duplicate records (the oldest record(s) will be deleted).
3) Quit

Choose your action [1-3]: 1

* RSIN: 123456788, Identificatie: 000000001, UUID: a6af61-741- [...]
* RSIN: 123456788, Identificatie: 000000001, UUID: 9b5a77-e18- [...]

1) Show duplicate records.
2) Delete duplicate records (the oldest record(s) will be deleted).
3) Quit

Choose your action [1-3]: 2

* Deleted: RSIN: 123456788, Identificatie: 000000001, UUID: 9b5a77-e18- [...]

1) Show duplicate records.
2) Delete duplicate records (the oldest record(s) will be deleted).
3) Quit

Choose your action [1-3]: 3

Done.
```
