### ISSUE TITLE
CI plan for Open Zaak

### ISSUE THREAD

**Issue by joeribekker** [open-zaak/open-zaak#773]
Currently, Open Zaak and Open Notificaties uses Travis CI for automated testing and pushes to Docker hub. Travis CI has changed their free plan to be very limited. This causes Open Zaak not to be tested and stalls development and PRs.

We can do a few things:

1) Use a paid CI plan at Travis-CI.com (budget needed)
2) Change to Github actions (takes time to rewrite -> budget needed)
3) "Force" CG/VNG to offer a solution for Open Source initiatives.
4) Other...

**Comment by LBozarov** [comment]
Change to GitHub of GitLab

**Comment by joeribekker** [comment]
@LBozarov All fine, but someone needs to rewrite CI to Github actions in that case.

**Comment by sergei-maertens** [comment]
I've done that for Utrecht this week - it seems doable for Open Zaak in one day.
