### ISSUE TITLE
Validation error during the import of exported catalogi data

### ISSUE THREAD

**Issue by alisihab** [open-zaak/open-zaak#775]
**Describe the bug**
I tried to import data which is exported from some other instance. I got the following:

![image](https://user-images.githubusercontent.com/10929856/99552183-ff5ff000-29bc-11eb-9c7e-fa20e70a99d8.png)

**To Reproduce**
try to import 
https://github.com/Sudwest-Fryslan/OpenZaakBrug/blob/develop/examples/soap/Swf%20Suites4SociaalDomein/B1026%20-%20Midoffice-productie%20name%20Minimaregeling%20aanvraag%20-%20Aanvraag%20minima%20-%20OpenZaak%20Export.zip

**Expected behavior**
Import exported data without an error.

**Comment by sergei-maertens** [comment]
Do you know the versions of Open Zaak of both instances?

**Comment by alisihab** [comment]
Both instances were from the master branch (version 1.3.1)

**Comment by sergei-maertens** [comment]
I think this was fixed at some point, will verify that it can no longer be reproduced.
