### ISSUE TITLE
Update GOVERNANCE.md related to product steering

### ISSUE THREAD

**Issue by felixfaassen** [open-zaak/open-zaak#781]
The GOVERNANCE.md file describes how we as a community govern the OpenZaak codebase. 
Currently the technical steering group has made efforts to update the GOVERNANCE.md and have the content reflect how technical steering is organized at this moment.

As product steering group we should also take a look at and update it where needed with the correct information so we can remove the DRAFT label and update the GOVERNANCE.md together as we move forward with our work.

**Comment by Ainali** [comment]
Could someone perhaps add a note of what was said in the last meeting with the Kern groep when the product steering was discussed? @joeribekker perhaps?

**Comment by joeribekker** [comment]
Unfortuntaly, I wasn't there. The issue that was discussed before the "kerngroep" meeting was about the use, mandate and goal of the product steering group.

My personal thought is that a product steering group is perhaps a little out of place for a technical registration component such as Open Zaak. The technical steering group still has periodic meetings and steers the product as well, which is perhaps logical for Open Zaak.

**Comment by Ainali** [comment]
Thanks for the update anyway! Perhaps @Hugo-ter-Doest can add something then?
