### ISSUE TITLE
Deleting Zaak requires Accept-Crs header

### ISSUE THREAD

**Issue by stevenbal** [open-zaak/open-zaak#80]
**Describe the bug**
When trying to delete a `Zaak`, the API gives an HTTP 412 if the header `Accept-Crs: EPSG:4326` is missing in the request, which should not be required when deleting a `Zaak`.

**Comment by annashamray** [comment]
@stevenbal Can you please try it now? 
I can't reproduce this in Postman

**Comment by stevenbal** [comment]
you're right, the issue was fixed in a newer version of vng_api_common, so I will close this issue
