### ISSUE TITLE
The field "Producten of Diensten" in the Catalogi/Zaaktypen admin interface is required

### ISSUE THREAD

**Issue by joeribekker** [open-zaak/open-zaak#806]
**Describe the bug**
The field "product_of_diensten" is marked as required in the API. Unfortunately, the API and the UI use 2 different meanings:

* In the API, "required" means: You must provide the field in the body and/or it must be present in the response (as far as I can find).
* In the Admin, "required" means: The field cannot be empty.

In OAS, you can mimic the same behaviour as the admin by setting: `minItems=1`. See also: https://swagger.io/docs/specification/data-models/data-types/ Or, we can remove required from the API.

**To Reproduce**
1. Create Zaaktype in API with `product_of_diensten=[]` (provided, but with empty array)
2. This should succeed
3. Open Zaaktype in Admin and try to save it.
4. An error shows that the field `product_of_diensten` is required.

**Expected behavior**
Behaviour should be consistent.

**Comment by sergei-maertens** [comment]
Shouldn't we just comply with the standard and make the field `blank=True` in the admin? That's the straight-forward solution.

**Comment by joeribekker** [comment]
@sergei-maertens yep
