### ISSUE TITLE
Getting internal server error bij posting a new zaaktype at the catalogi api

### ISSUE THREAD

**Issue by adriaanvanloon** [open-zaak/open-zaak#850]
**Describe the bug**
At the catalogi api when you use the webservicecall ' maak een zaaktype aan' if you set the 'verlengingMogelijk'  on true but don't set a ' verlengingstermijn' (its not mandatory) you'll get a internal server error as response (http 500) 

**To Reproduce**
1. Create a SOAPUI webservicecall ' maak een nieuw zaaktype aan' 
2. Fill in all the required field and set ' verlengingmogelijk' on true
3. Don't define verlengingstermijn (like not even the attribute) 
4. POST the json message to open zaak catalogi api '/catalogi/api/v1/zaaktypen/' 

**Expected behavior**
I expect a JSON message back with that when you set verlengingmogelijk on true you need to define a verlengingstermijn instead of a mysterious internal server error (http status 500). Now i had to check in de Open-Zaak logs what went wrong.

**Comment by sergei-maertens** [comment]
Note: this is probably also a bug in the upstream reference implementation.

**Comment by shea-maykinmedia** [comment]
I checked the upstream reference implementation and this bug does also happen there so I'll create an issue in gemma-zaken
