### ISSUE TITLE
Updating a zaaktype (PUT) raises an IntegrityError on gerelateerdeZaken

### ISSUE THREAD

**Issue by adriaanvanloon** [open-zaak/open-zaak#851]
**Describe the bug**
When we've already got a zaaktype on concept and we want to publish it (publicatieIndicatie set on true) we get an internal server error. The message in Open-Zaak log:

_django.db.utils.IntegrityError: duplicate key value violates unique constraint "catalogi_zaaktypenrelati_zaaktype_id_gerelateerd__215fe641_uniq"
DETAIL:  Key (zaaktype_id, gerelateerd_zaaktype)=(379, http://open-zaak.gemeentenet.local/catalogi/api/v1/zaaktypen/81256657-d7b1-4ddb-88de-054fccb0edfc) already exists._

It seems that we also need to update the attribute 'gerelateerdeZaaktypen'. Is this truly mandatory??? Can't we just keep the zaaktype the same and just publish it? 

**To Reproduce**
1. Insert a zaaktype and let it stay on concept
2. Create a PUT call where you set the ' publicatieIndicatie' of the zaaktype of step 1 on true
3. PUT the call to http://open-zaak.gemeentenet.local/catalogi/api/v1/zaaktypen/{uuid} (UUID of the zaaktype at step 1)

**Expected behavior**
A http status 200 with a message that the zaaktype is now published or een error where it says that you can't have the same value at the attribute 'gerelateerdeZaaktypen'

**Comment by sergei-maertens** [comment]
Publishing a zaaktype is done by making a `POST` call to `http://open-zaak.gemeentenet.local/catalogi/api/v1/zaaktypen/{uuid}/publish` - not by toggling the `publicatieIndicatie` field (it has the meaning that zaken of that zaaktype should be published somewhere, not that the zaaktype itself is being published).

However, those integrity errors need to be looked into.
