### ISSUE TITLE
Als technisch beheerder bij een gemeente, wil ik één installatiepakket... 

### ISSUE THREAD

**Issue by RvdKlip** [open-zaak/open-zaak#86]
... zodat ik makkelijk en snel een Open-Zaak omgeving kan neerzetten in onze OTAP omgevingen.

**Comment by Hugo-ter-Doest** [comment]
Er worden Docker containers en een VM geleverd. Dat is niet echt een installatiepakket maar zijn eenheden die uitgerold kunnen worden naar een omgeving.
