### ISSUE TITLE
Better security: don't run as root user in container

### ISSUE THREAD

**Issue by sergei-maertens** [open-zaak/open-zaak#869]
The Dockerfile does not drop privileges to a non-privileged user, while it's perfectly possible.

**Comment by sergei-maertens** [comment]
Note: could be useful/needed for Podman support

**Comment by ericherman** [comment]
From Tech Steering: This has an impact on deployed containers, we can limit impact by doing it sooner.

**Comment by sergei-maertens** [comment]
Fix was added, but to be able to run in Kubernetes with `podSecurityContext.fsGroup`, we need to assign a non-root group as well.
