### ISSUE TITLE
Als low code developer binnen een gemeente, wil ik gemakkelijk en snel kunnen werken met Open-Zaak...

### ISSUE THREAD

**Issue by RvdKlip** [open-zaak/open-zaak#87]
...zodat ik snel over de Open-Zaak data kan beschikken in mijn applicatie.

- zonder diepgaande kennis te hoeven hebben over de api's
- zonder diepgaande kennis te hoeven hebben over het informatiemodel
- zonder diepgaande kennis te hoeven hebben over de in volgorde uit te voeren calls e.d.
- low code aanhaken en eenduidig 'standaardfunctionaliteit' uit Open Zaak kunnen gebruiken

**Comment by Hugo-ter-Doest** [comment]
OpenZaak implementeert standaard API's voor ZGW. De gevraagde eigenschappen horen thuis bij de standaard.
