### ISSUE TITLE
As municipality, I want to be able to distribute 'Maatschappelijke Activiteiten' in object type (Zaakobjecten)

### ISSUE THREAD

**Issue by OlavAllema** [open-zaak/open-zaak#876]
**General information**
Open Zaak version: 1.3.1

**Describe the bug**
In the list 'object type' under zaakobjecten, the option for 'Maatschappelijke Activiteiten' is missing. The NHR (Nationaal Handelsregister) works/will work with multiple object types. The most important ones are 'Vestigingen' (VES), 'Niet-Natuurlijke Personen' (NNP) and 'Maatschappelijke Activiteiten' (MA). The first two are already in the object type list, but MA isn't.

![image](https://user-images.githubusercontent.com/75848616/109276845-d3070b80-7816-11eb-81d1-65108a04e734.png)
![image](https://user-images.githubusercontent.com/75848616/109277031-0ba6e500-7817-11eb-9ab9-9713ac2aa636.png)

**To Reproduce**
1. Go to Voorpagina › Zaakobjecten › zaakobject toevoegen
2. Select the list Object type and search for MA (you'll see it isn't there).

**Expected behavior**
Add 'Maatschappelijke Activiteiten' to the list of object types.

**Comment by OlavAllema** [comment]
I understand it's actually adding a betrokkeneType: https://dev-openzaak.tezza.eu/zaken/api/v1/schema/#operation/rol_create

**Comment by joeribekker** [comment]
You mean `RolType` probably, and yes :)

The `betrokkeneTypes` are well defined and directly match the underlying information model.

If this solves you problem, please close the ticket :)

**Comment by OlavAllema** [comment]
I understand, from you answer, that I need to go to the VNG with this question. Thanks Joeri
