### ISSUE TITLE
Als deelnemende betalende gemeente, wil ik - naast de gebruikelijke scrumteam demo en reviewmomenten - regelmatig een managementrapportage van Dimpact...

### ISSUE THREAD

**Issue by RvdKlip** [open-zaak/open-zaak#88]
...waarmee het management van de gemeente op de hoogte wordt gehouden over koers, status, uitnutting en voortgang, zodat zij haar eigen koers hierop kan bijsturen.

- dit zonder bij scrumsessies aanwezig te hoeven zijn

**Comment by Hugo-ter-Doest** [comment]
Via mail doorgezet naar mijn collega's.

**Comment by RvdKlip** [comment]
Deze kan dicht.
