### ISSUE TITLE
[FEATURE-REQUEST]Teller op opschorten van lopende zaak

### ISSUE THREAD

**Issue by TjerkVaags** [open-zaak/open-zaak#885]
## Gegevens aanvrager / information applicant

Organisatie / Organization: Contezza
Naam / Name: Tjerk Vaags
Telefoonnummer / Phone number (OPTIONAL):
E-mailadres / e-mail address: tjerk.vaags@contezza.nl

### Omschrijving / Summary
Op dit moment kan een lopende zaak worden opgeschort door 'Indicatie opschorting (boolean)' op true te zetten. Daarbij kan een 'Reden opschorting (string, max 200 char)' worden gegeven . In de backend gebeurd er verder niets met de "Einddatum gepland" of andere einddata:

### Probleem beschrijving / Problem description
Volgens de manier van werken moet bij het opschorten de zaak op pauze worden gezet. Als de opschorting wordt opgeheven moet het aantal dagen dat de lopende zaak is opgeschort bij de Einddatum gepland worden toegevoegd.

### Oplossingsrichting / Solution direction
Een soort Cron-job te plaatsen die kijkt of zaken opgeschort zijn. Onder water start er een teller die de dagen bijhoudt dat de lopende zaak op 'indicatie opschorting: true' staat.

### Gebruikers criteria / User criteria
De eindgebruiker wenst dat de einddatum gepland wordt aangepast nadat opschorting is opgeheven.

### Consequentie nul-optie / Cost of not doing this request
Zie beschrijving bij urgentie.

### Details feature / details of feature
Extra metadata-veld die teller bijhoud. schorting.counter of iets dergelijks.

### Urgentie / Priority
4, op zich heeft het geen hoge prio, maar het is wel zo dat iedere UI App die gebruik maakt van Open Zaak zelf ergens een teller moet realiseren en dus zelf ergens die teller-data moet opslaan.

**Comment by felixfaassen** [comment]
Closed:
Besproken in de Product Steering meeting en we willen geen expliciete business logica in Open Zaak zetten. Er moet een feature request komen in de ZGW Standaard en vervolgens kan dit wellicht geimplementeerd worden.
