### ISSUE TITLE
Als technisch applicatie beheerder, low code developer en 'laag4/5' applicatie bij een gemeente, wil ik inzicht hebben in de wijze waarop we een upgrade en update kunnen uitvoeren passend in ons onderhoudswindow...

### ISSUE THREAD

**Issue by RvdKlip** [open-zaak/open-zaak#89]
...zodat alle applicaties en de IT infrastructuur ongestoord en bedrijfszeker (beschikbaarheid, performance, veiligheid, etc) blijft doordraaien.

Ik bedoel uiteraard een upgrade en update van dd OpenZaak software

**Comment by sergei-maertens** [comment]
Documentatie over updaten is hier te vinden: https://open-zaak.readthedocs.io/en/latest/installation/updating.html

**Comment by sergei-maertens** [comment]
Closing this issue, as the update procedure is documented.

It depends on your target environment whether you can do this with zero downtime or not, and it's up to the organization/service provider to properly prepare for updates to minimize downtime.
