### ISSUE TITLE
Als architect van een gemeente wil ik graag een archimate tekening (gele, groene en blauwe laag) van OpenZaak...

### ISSUE THREAD

**Issue by RvdKlip** [open-zaak/open-zaak#90]
...zodat ik weet welke services, functies, e.d. ondersteund worden en ik deze kan toepassen binnen de gemeentelijk architectuur.

**Description**
Describe the user story in more detail.

**Comment by Hugo-ter-Doest** [comment]
Staat in de README van de repo.
