### ISSUE TITLE
Openen documenten via zaak lukt niet

### ISSUE THREAD

**Issue by jgabrieldelft** [open-zaak/open-zaak#911]
Het openen van de documenten via de zaak lukt niet.
Als je bij de zaak het informatieobject opent via ‘wijzigen’, vervolgens op het informatieobject klikt, en vervolgens op de link bij ‘inhoud’ klikt, krijg je:
**Sorry, the requested page could not be found (404)**

Via documenten/informatieobjecten of de API gaat het wel goed.
![openzaakmelding](https://user-images.githubusercontent.com/78357209/112167856-132c9480-8bf1-11eb-95d0-0d77621624e8.png)

**Comment by sergei-maertens** [comment]
Bedankt voor de duidelijke screenshots, daar kunnen we wat mee!

Even kijken of deze nog mee kan met de release van komende donderdag :-)
