### ISSUE TITLE
Als CIO van een gemeente wil ik weten welke leveranciers OpenZaak in de cloud of on premise leveren, hosten en na levering ondersteunen...

### ISSUE THREAD

**Issue by RvdKlip** [open-zaak/open-zaak#92]
...zodanig dat ik mijn ICT dienstverlening gegarandeerd kan blijven leveren aan de gemeente en haar afnemers en ketenpartners.

**Description**
Describe the user story in more detail.

**Comment by sergei-maertens** [comment]
Service providers are documented here: https://open-zaak.readthedocs.io/en/stable/support/index.html#service-providers

What seems to be the problem now, is that service providers don't seem aware that they can add themselves to this list :)

**Comment by RvdKlip** [comment]
Okee, dank. Dit is ook een zinvolle doorontwikkeling voor https://componentencatalogus.commonground.nl/ van de VNG. Dus ik knikker hm hier dicht en zet hm daar ergens op een todo lijstje.
