### ISSUE TITLE
Catalogus 'NAAM' is not imported correctly 

### ISSUE THREAD

**Issue by haarlem-dvh** [open-zaak/open-zaak#920]
**General information**
Open Zaak version: 1.3.4

**Describe the bug**
I have exported a catalogus. When importing it, the catalogus and zaaktypes are imported correctly. But the catalog's NAAM is empty. Which makes it impossible to open/edit the catalogus itself because the link to it is not created. 

[Example after import](https://imgur.com/fFjmatM)

**To Reproduce**
1. Create an catalogus
2. Export the catalogus
3. Remove the catologus
4. Import the catalogus

**Expected behavior**
The field 'NAAM' should contain the NAAM of the catalogus after importing a catalogs

**Comment by joeribekker** [comment]
You can still open it by hovering over the "space"-character.

This is a "known issue". The export uses the Catalogi API specification which does not define a "naam" property. When imported, there is no name to set for the catalog.

We added the name for management purposes and it is therefore ONLY available in Open Zaak directly. We probably need to make the default name "(unnamed)" or something.

**Comment by haarlem-dvh** [comment]
Ah, that makes sense. Or you could add the hyperlink to one of the fields that are imported, like UUID.

**Comment by sergei-maertens** [comment]
See also #891

**Comment by joeribekker** [comment]
Ah, in that case closing this in favor of #891
