### ISSUE TITLE
When registering a webhook fails it causes a 500 error

### ISSUE THREAD

**Issue by joeribekker** [open-zaak/open-zaak#921]
**General information**
Open Zaak version: 1.3.5

**Describe the bug**
If you registering a webhook and something goes wrong, a HTTP 500 is given.

**To Reproduce**
1. Create invalid webhook subscription
2. Register it

**Expected behavior**
 The underlying error should be shown as a message in the admin instead (invalid permissions, cannot reach server, etc.)

**Comment by adgerrits** [comment]
In the [Open Notificaties manual](https://open-notificaties.readthedocs.io/en/stable/manual/subscriptions.html#) it looks as if the only way to create a subscription is to do this manual via the Admin-panel. Is it also possible to do this programmatically as described in the [Tutorial nofificeren](https://vng-realisatie.github.io/gemma-zaken/ontwikkelaars/handleidingen-en-tutorials/notificeren#ik-wil-als-consumer-notificaties-ontvangen)?

**Comment by joeribekker** [comment]
ofcourse it is :)

**Comment by adgerrits** [comment]
Documentation is a love letter that you write to your future self. - Damian Conway

**Comment by joeribekker** [comment]
It could be more clear.... but:

1. https://open-notificaties.readthedocs.io/en/latest/api/index.html (click **1.0**)
2. https://notificaties-api.vng.cloud/api/v1/schema/#operation/abonnement_create ("Maak een ABONNEMENT aan.")

Ofwel, [RTFM](https://en.wikipedia.org/wiki/RTFM) 😉

**Comment by annashamray** [comment]
I can't reproduce it in the admin both locally and on the hosted Open Notificaties:
* if setting `TEST_CALLBACK_AUTH` is `False` (default for development env) then the callback url is not even checked and it's saved as it is
* if setting `TEST_CALLBACK_AUTH` is `True` (default for production env) then the callback url is checked but the error is rendered correctly in the page without crashing the admin)

@joeribekker Could you still reproduce it?

**Comment by joeribekker** [comment]
I trust in your judgement seeing we are 5 minor versions further than when this was reported.
