### ISSUE TITLE
A developer I would like the helm chart to contain packages and be available on artifacthub.io

### ISSUE THREAD

**Issue by rubenvdlinde** [open-zaak/open-zaak#923]
So that I can make them available on https://artifacthub.io/ which in turn allows me to install this project trough standardized helm tooling  

Organisatie / Organization:  Conduction
Naam / Name: Ruben van der Linde
Telefoonnummer / Phone number (OPTIONAL):
E-mailadres / e-mail address: ruben@conduction.nl

### Omschrijving / Summary

Making charts available on https://artifacthub.io/ provides for easy installations trough tools that use that helm repository. It also means that cloud native foundation guidelines are more strictly followed (cloud native foundation maintains artifact hub) ensuring a future proof is installation process on kubernettes (also and not accidently a cloud native project).

Furthermore it makes this project more findable as an opensource project, thereby providing additional value to one of the key concepts behind the project.

### Acceptatie criteria / Acceptance criteria

Al charts are available  on  https://artifacthub.io/

**Comment by sergei-maertens** [comment]
@bartjkdp do you have any idea about the impact for this to be possible? I'm thinking of:

* manual actions required
* CI setup required for automatic publishing
* ???

**Comment by bartjkdp** [comment]
I just created an Open Zaak organization and repository on Artifact Hub:

![image](https://user-images.githubusercontent.com/5213690/113319862-2dadee80-9312-11eb-8024-950bdaf94580.png)

Artifact Hub will take care of syncing with the repository of Open Zaak.

**Comment by sergei-maertens** [comment]
@bartjkdp I've got an account there now, username is `sergei-maertens`

@open-zaak/technical-steering-group I suggest you all also sign in with your github account so that we can make all members owner of the Helm package

**Comment by shazada** [comment]
I've signed-in with my github account. username is `shazada`

**Comment by sergei-maertens** [comment]
@bartjkdp I can see that I'm in the organization, but I don't see the repositories in my repository tab. Do I need to claim ownership or something?

**Comment by bartjkdp** [comment]
@sergei-maertens probably you need to switch context:

![image](https://user-images.githubusercontent.com/5213690/114703937-4365df80-9d26-11eb-8615-265b6c2196d0.png)

**Comment by sergei-maertens** [comment]
This appears to be set up properly now, let us know if that's not the case!
