### ISSUE TITLE
New resultaattype link in zaaktype gives 404 when internal referencecount > 1000

### ISSUE THREAD

**Issue by EduardWitteveen** [open-zaak/open-zaak#928]
When the internal number of the zaaktype > 100  the add new resultaattypes url contains a . inside the number.
This will cause a 404 error, since the server doenst understand the number (because of the . in the number)

**Comment by sergei-maertens** [comment]
Direction for fix: disable localisation (see https://docs.djangoproject.com/en/2.2/topics/i18n/formatting/#std:templatefilter-unlocalize) in the templates outputting these URLs

**Comment by sergei-maertens** [comment]
This was fixed in Open Zaak 1.3.2 already, see c9742f858 and #587 

Please specify your Open Zaak version when submitting bug reports - the template https://github.com/open-zaak/open-zaak/issues/new?assignees=joeribekker&labels=bug&template=bug_report.md&title= includes this :)
