### ISSUE TITLE
Importeer "catalogus" dus not work

### ISSUE THREAD

**Issue by EduardWitteveen** [open-zaak/open-zaak#929]
[gemeente-sudwest-fryslan.zip](https://github.com/open-zaak/open-zaak/files/6227089/gemeente-sudwest-fryslan.zip)
I exported an catalogus from our test enviroment, when i try to import it on an other system i get an error. [](url)

**Comment by sergei-maertens** [comment]
Possibly related to #775 and/or #593

**Comment by annashamray** [comment]
The archive has several resultaattypen, which `selectielijstklasse` attributes don't match the related `zaaktype.selectielijst_procestype`. 
Some of their urls: 
* http://testtsjinstbus.sudwestfryslan.nl/zgw/catalogi/api/v1/resultaattypen/ad99fb44-7bd9-4dc2-a934-6d45a0f24810
* http://testtsjinstbus.sudwestfryslan.nl/zgw/catalogi/api/v1/resultaattypen/62704a98-5edc-4531-b756-23ba39681067
* http://testtsjinstbus.sudwestfryslan.nl/zgw/catalogi/api/v1/resultaattypen/7de144d4-1b26-4b5a-a6bd-18f61a172db5

Once they were removed from the archive it was correctly. 
I've attached the archive without them which I imported without any error
[gemeente-sudwest-mod.zip](https://github.com/open-zaak/open-zaak/files/11833207/gemeente-sudwest-mod.zip)

Note: for now importing doesn't work if the source and target Open Zaken are hosted with different prefixes
I don't think it's a bug, more like a room for enhancement

@joeribekker what do you think?

**Comment by joeribekker** [comment]
We think the data from the source was simply incorrect due to a lack of validation we had in Open Zaak before. Importing this incorrect data would trigger validation and the data would be denied.

Closing this until it becomes a problem again and the reason is different than described above.
