### ISSUE TITLE
When CMIS is enabled, a service for the Document API is required

### ISSUE THREAD

**Issue by SilviaAmAm** [open-zaak/open-zaak#938]
Currently, both the following have to be defined:
- Service for the Document API
- Applicatie to authorize the service to access openzaak

This is required because the documents in the DMS are considered 'external' so open-zaak expects a service to be able to reach them.

It would be good to not have to use these extra service/application.

**Comment by sergei-maertens** [comment]
@SilviaAmAm is this requirement documented anywhere?

**Comment by SilviaAmAm** [comment]
In the configuration section of the cmis-adapter: https://open-zaak.readthedocs.io/en/latest/installation/config/cmis.html it specifies which services are needed. Although, there it still says that also the Zaken API and the Catalogi API services are needed, so I should update it.
