### ISSUE TITLE
Als informatiearchitect wil ik weten hoe MS Office365 applicaties en andere applicaties van niet Nederlandse leveranciers gekoppeld kunnen worden aan OpenZaak...

### ISSUE THREAD

**Issue by RvdKlip** [open-zaak/open-zaak#94]
...zodat ook deze applicaties gebruik kunnen maken van gemeentelijke api's

**Description**
Describe the user story in more detail.

**Comment by CMasselink** [comment]
@RvdKlip ik heb hier recent met Microsoft en o.a. één van hun partners (Motion10) over gesproken. Er lijken wel mogelijkheden te zijn, zal ik je hier binnenkort een keer over bijpraten?

**Comment by Hugo-ter-Doest** [comment]
Het is bekend hoe gekoppeld kan worden met de API's voor ZGW. Dit is een integratievraagstuk dat met andere leveranciers moet worden besproken.
