### ISSUE TITLE
500 error indien Status.datumStatusGezet en Status.Zaak al voorkomen

### ISSUE THREAD

**Issue by joeribekker** [open-zaak/open-zaak#960]
*Gemeld door Martijn van Genetics*

**General information**
Open Zaak version: 1.3.5

**Describe the bug**
Deze unique constraint wordt niet afgevangen door de API. Is dit ook een eis in de standaard?

**To Reproduce**
1. Zet status A bij Zaak op datum/tijd X
2. Zet status B bij Zaak op dezelfde datum/tijd X
3. Error

**Expected behavior**
400 error with proper message.

**Comment by sergei-maertens** [comment]
Yes, the reference implementation has this same constraint: https://github.com/VNG-Realisatie/zaken-api/blob/master/src/zrc/datamodel/models/core.py#L393

**Comment by sergei-maertens** [comment]
Sorry, label should exist since this should just result in a validation error
