### ISSUE TITLE
500 response code for the request to zaken/api/v1/statussen

### ISSUE THREAD

**Issue by alisihab** [open-zaak/open-zaak#961]
**General information**
Open Zaak version: 

**Describe the bug**
I am trying to update a zaak during the request reply chain I get 500 internal server error. This tells me nothing about what happened. 

If I send a POST request to zgw/zaken/api/v1/statussen with the body:
{
"zaak":"https://REPLACED/zgw/zaken/api/v1/zaken/58b78d3a-1158-4cdc-bb66-bcc67769fa66",
"statustype":"https://REPLACED/zgw/catalogi/api/v1/statustypen/7057fb56-fe4a-4c86-bd00-fa9fe936307b",
"datumStatusGezet":"2021-04-23T00:00:00.000000Z",
"statustoelichting":"Afgehandeld"
}

I am getting the following:
{
"type":"https://REPLACED/zgw/ref/fouten/APIException/",
"code":"error",
"title":"Er is een serverfout opgetreden.",
"status":500,"detail":"Internal Server Error",
"instance":"urn:uuid:b8ed90ef-75da-45d4-8c8f-f28d7ecd3104"
}

**To Reproduce**
For more information please
Contact to me or Eduard from gemeente Sudwest fryslan

**Expected behavior**
A clear and concise description of what happened to my request :) .
I don't know the Open zaak version. Could it be a good idea to mention the Open zaak version somewhere in the exception message in the response?

**Comment by sergei-maertens** [comment]
@alisihab 

> I don't know the Open zaak version. Could it be a good idea to mention the Open zaak version somewhere in the exception message in the response?

The Open Zaak version is displayed in the bottom left in the footer of the homepage, for example https://test.openzaak.nl/ is on 1.3.5

On the right you have the commit hash of that version, you can also include that.

The container logs should have a traceback from this request, and if you are making use of Sentry, then there should also be a traceback there. Can you look those up?

**Comment by alisihab** [comment]
We can only access /admin and zgw apis. I think the latest version is installed by Maykin Media.

**Comment by sergei-maertens** [comment]
@joeribekker any chance this is related to #960?

**Comment by joeribekker** [comment]
Yes, this is 99% certain the same as #960. The solution/workaround is to not set statusses with the exact same time as the previous one. If you only set dates you can for example do `<date>00:00+status volgnummer` to make sure the datetime differs from the previous status

**Comment by joeribekker** [comment]
It is maybe a good idea to pass the OZ version as header, making a new issue for that.

@alisihab Can you confirm my previous comment is the issue? And if so, close this ticket?

**Comment by joeribekker** [comment]
I think we should at least return a 400 error and describe the error.

**Comment by joeribekker** [comment]
Closing this as deuplicate.
