### ISSUE TITLE
Bug #863 still present in 1.4.0

### ISSUE THREAD

**Issue by jgabrieldelft** [open-zaak/open-zaak#976]
Cannot create 2 IOTs with the same description, in the same Catalog but with different dates #863 
(could not find how to reopen that bug)

Happens when using Catalogi Importer, importing iNavigator export to replace already present and published items.

**Comment by sergei-maertens** [comment]
Possibly fixed by #995, need to verify

**Comment by sergei-maertens** [comment]
Verified - this is fixed from Open Zaak 1.5.0 onwards
