### ISSUE TITLE
Verwijderen zaaktypen of catalogus niet mogelijk

### ISSUE THREAD

**Issue by jgabrieldelft** [open-zaak/open-zaak#977]
Open Zaak 1.4.0. Ik ben admin met stafstatus en superuserstatus.

Verwijderen van zaaktypecatalogus, zaaktypen of informatieobjecten is niet mogelijk, zie bijlage voor melding.
![2021-05-11 10_26_26-catalogus kan niet worden verwijderd _ Open Zaak en nog 2 andere pagina's - Prof](https://user-images.githubusercontent.com/78357209/117825483-a7b98780-b26f-11eb-923a-095ead07c263.png)

Verwijderen via API kan wel voor Zaaktypen en Informatieobjecten.

**Comment by sergei-maertens** [comment]
De bug hier is dat ze wel via API verwijderd kunnen worden, dat zou ook niet mogen geloof ik.

**Comment by joeribekker** [comment]
@annashamray make sure there is a test that checks if you can not delete a zaaktype via the API when its published (or, not a concept).

**Comment by annashamray** [comment]
@joeribekker I've made some research. So, `zaaktypen`, `besluittypen` and `informatieobjecttypen` api checks if the token has permission scope `"catalogi.geforceerd-verwijderen"`. If they don't have it then 400 error with code "non-concept-object" is returned.
Reference implementation has the same logic.
This looks very deliberate and covered with tests. Should I add some changes to it?

**Comment by joeribekker** [comment]
Let's keep it this way. Publishing zaaktypen is not a lightweight operation because Zaken can depend on it. Maybe we should add something to "hide" catalogs that are no longer needed from an admin perspective (and still keep them available in the API).
