### ISSUE TITLE
Zaken should not be deleted when deleting the related zaaktype

### ISSUE THREAD

**Issue by joeribekker** [open-zaak/open-zaak#979]
**General information**
Open Zaak version: 1.4.0

**Describe the bug**
Resources between API's should be PROTECTED or SET_NULL*. Thus, we should only be allowed to delete a Zaaktypen if no cases are related.

\* SET_NULL is the most accurate because if Zaken en Catalogi were different components, the Catalogi API zaaktype would not have a db relation to a zaak in the Zaken API.

**To Reproduce**
1. Create Zaaktype
2. Create Zaak of above Zaaktype
3. Delete Zaaktype
4. Observe deleted Zaak

**Expected behavior**
Hmm, not sure :(

**Comment by sergei-maertens** [comment]
I think that introducing nullable `Zaak.zaaktype` completely beats the point of using Open Zaak for performance and data integrity reasons, which distributed services DON'T have. Other than that, we cannot tell if a `null` zaaktype came from a delete or from a bug, and our serializers still have to emit data conforming to the API spec even if the zaaktype is null, which I just don't see as possible.

So `models.PROTECT` it will be.

**Comment by sergei-maertens** [comment]
Also note that this is only possible if you allow creation of zaken from non-published *typen, since only non-published *typen can be deleted according to the standard.
