### ISSUE TITLE
Als vakafdeling (bijvoorbeeld proces eigenaar meldingen Openbare Ruimte) wil ik een hoge beschikbaarheid (99,99%) van de API's 24x7...

### ISSUE THREAD

**Issue by RvdKlip** [open-zaak/open-zaak#98]
... zodat bedrijfszekerheid van mijn dienstverlening gewaarborgd blijft.

**Comment by Hugo-ter-Doest** [comment]
Beschikbaarheid is afhankelijk van een aantal factoren waaronder software (maar bijv. ook beschikbaarheid van systemen en netwerk). Wat betreft software laat ik de user story ook hier staan. 

Wsch. beste te behandelen door uit te leggen welke maatregelen zijn genomen bij de ontwikkeling om fouten die tot harde crashes leiden te voorkomen.

**Comment by Hugo-ter-Doest** [comment]
Beschikbaarheid wordt bepaald door aantal factoren waaronder kwaliteit van de software, maar ook hosting. We gaan uit van goede kwaliteit van de software. Dan blijft over hosting als factor. En dit is buiten scope van dit project. Als kwaliteit van de software een rol gaat spelen heropenen we dit issue.
