### ISSUE TITLE
Non concept object type's, property 'eindeGeldigheid' can't be set to null

### ISSUE THREAD

**Issue by mindaugask** [open-zaak/open-zaak#981]
**General information**
Open Zaak version: 1.4.0

**Describe the bug**
'eindeGeldigheid' field for published object types (case type, information object type and etc) can't be set to 'null' value when doing patch object type request.
[Here](https://vng-realisatie.github.io/gemma-zaken/standaard/catalogi/index#ztc-009) it is specified that this field is allowed to be updated for published object types, and I would assume it should accept all values supported by it including 'null'.

**To Reproduce**
1. Have a published object type
2. Do a patch request on a object type with body:
`{
    "eindeGeldigheid": null
}`
3. Error (sometimes errors, depending on object type) returned indicating that concept object can't be updated.

**Expected behavior**
'eindeGeldigheid' field set to null value.

**Comment by joeribekker** [comment]
This seems indeed to conflict with the standard. I'm not 100% sure this behaviour is desired so I will pass it by VNG just to be sure.

**Comment by mindaugask** [comment]
Yes I was also not sure about it as it doesn't explicitly say so, it's good that you can confirm if it actually should be like this.

**Comment by sergei-maertens** [comment]
Discussed with Joeri - the case of setting the einddatum back to `null` was not explicitly on the radar when the standard was designed, but we see sufficient use case to not consider this a problem. The only constraint is that if the `einddatumGeldigheid` is reset from a particular value back to `null` (or any other value), there may still not be overlap between FOOtype.
