### ISSUE TITLE
Not possible to update concept case type which is related to published information object types

### ISSUE THREAD

**Issue by mindaugask** [open-zaak/open-zaak#983]
**General information**
Open Zaak version: 1.4.0

**Describe the bug**
It is not possible to update concept case type using PUT/PATCH methods when case type is connected to already published information object types.
[Here ](https://vng-realisatie.github.io/gemma-zaken/standaard/catalogi/index#ztc-010) are the rules describing this behavior and while it is true that objects related to non concept objects should not be modified, the exception is in case type and object information type relation.

**To Reproduce**
1. Create new information object type (informatieobjecttypen) and publish it
2. Create new case type (zaakType)
3. Create new case type and information object type relation (zaaktype-informatieobjecttypen) with newly created objects
4. Try update case type using PATCH/PUT endpoints, error is returned: 'Objects related to non-concept informatieobjecttypen can't be updated'

**Expected behavior**
Case type gets updated, even if it has connections to already published information object types.

**Comment by joeribekker** [comment]
Hi @mindaugask and welcome to Open Zaak!

Thanks for pointing to the exact behaviour rule. Agree this is a bug in Open Zaak in conflict with the standard.

**Comment by mindaugask** [comment]
I think we might have misinterpreted this rule so you might also want to check this one with VNG, to see if it is actually how I've described it.

**Comment by sergei-maertens** [comment]
Confirmed bug in Open Zaak, I'm working on a patch!

**Comment by stevenbal** [comment]
Related issue in upstream: https://github.com/VNG-Realisatie/gemma-zaken/issues/2010
